### PR TITLE
LPS-108741 Remove AUI from Liferay.Portal.ToolTip | v2

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

A followup on https://github.com/wincent/liferay-portal/pull/153

Changes:
- Fixed source formatting errors.

I analyzed APIs of [ClayTooltip](https://github.com/liferay/clay/blob/master/packages/clay-tooltip/src/Tooltip.tsx), [TooltipProvider](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-tooltip-support-web/src/main/resources/META-INF/resources/index.js), [Liferay.Portal.Tooltip](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/portal.js) and [A.Tooltip](http://alloyui.com/api/files/alloy-ui_src_aui-tooltip_js_aui-tooltip-base.js.html#l14).

1. `ClayTooltip` has a very open API, where you can put pretty much any attribute or content.
1. `TooltipProvider` is an implementation of `ClayTooltip`, applying it globally. In it, we are just taking `title` attribute and showing it in tooltip. All other settings, such as position and events that trigger tooltip, are hardcoded. Any change that is input to util would need to be relayed here, for example through `data-` attributes.
1. `Liferay.Portal.Tooltip` has almost the same API as `A.Tooltip`. It just adds `stickDuration`, setting if we want to keep tooltip for longer. Do we want to support this?
1. `A.Tooltip` has a pretty big API. It defines 10 attributes (`animated`, `bodyContent` etc), but also inherits 11 other AUI widget interfaces (`A.WidgetCssClass`, `A.WidgetPosition` etc.), that inherit interfaces of their own. I didn't count them all but it's safe to say there are minimum of 30 attributes and methods that make up API.
1. Pretty much everything in `A.Tooltip` API can be implemented with `ClayTooltip`, by modifying `TooltipProvider`. If we don't want to change `TooltipProvider`, we cannot implement anything.

So, [the reasoning](https://github.com/wincent/liferay-portal/pull/153#issuecomment-592052769) to implement only what `ClayTooltip` API supports is not useful, as we can implement probably everything. I guess the question is: what do we think it is important to be customizable? In the `TooltipProvider` implementation, we didn't think anything was important. I pretty much agree with this, thinking that it is safe to cut legacy use to only base appearance and behavior. What do you think?

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by wincent** [comment]
> What do you think?

I concur. Not worth it. Thanks for doing the analysis! If this turns out to be the wrong decision and there is demand to expand the API, we can always do it in the future.

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/85596

**Comment by markocikos** [comment]
Closing, merged.

**Pull request closed without merging**
