### PR TITLE
LPS-113556 Deprecate `aui_sandbox`

### PR DESCRIPTION
**Pull request by julien**
`aui_sandbox` overrides the original `YUI.use` function as well as [defining an `AUI` global][0] on the `window` object.

In this change we're marking the module as deprecated, because both [the `use()` function][1] (which is the basic dependency loading mechanism in AUI), and the `AUI` global itself will eventually become unused as we work through [LPS-98564][2] ("Remove AUI / YUI from Liferay Portal").

[0]: https://github.com/liferay/liferay-portal/blob/9617f95b39dbb47f032785f08b71932038e1bb9e/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/aui_sandbox.js#L42-L44
[1]: https://yuilibrary.com/yui/docs/yui/#dynamic-loading-with-use
[2]: https://issues.liferay.com/browse/LPS-98564

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Thanks @julien!

> aui_sandbox overrides the original YUI.use function as well as defining some globals on the window object. In this change we're marking it as deprecated.

As I read this, I was thinking, got any analysis to add here as well? Obviously the code change is fine (it's a comment), but this is one of those "what happened" commit messages, but without an explanation of "why" it's ok to deprecate. I guess my questions would be the following, which I am sure you thought about and have answers for:

- What are the globals that get defined and why don't we need them any more? (Bonus points if you [link directly to them](https://github.com/liferay/liferay-portal/blob/9617f95b39dbb47f032785f08b71932038e1bb9e/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/aui_sandbox.js#L42-L49)).

The other point which is probably very obvious to you because you have been deep into deprecate-AUI-land for a while now, but which may not be obvious to somebody reading this from the outside, or six months form now, is *why* we aren't going to need this enhanced `use()` implementation in the future; again, bonus points for linking to provide more context:

> The [`use()`](https://yuilibrary.com/yui/docs/yui/#dynamic-loading-with-use) function is the basic dependency loading mechanism in AUI. We can deprecate it because, as we work through [LPS-98564](https://issues.liferay.com/browse/LPS-98564) ("Remove AUI / YUI from Liferay Portal"), eventually all code which transitively depends on `use()` will be removed or migrated away.

To save time (and seeing as CI is green) I'll just apply those suggested edits directly and forward.

**Comment by wincent** [comment]
Manual forward here: https://github.com/brianchandotcom/liferay-portal/pull/89276

**Pull request closed without merging**
