### PR TITLE
LPS-98032 Format JS in JSP files with Prettier

### PR DESCRIPTION
**Pull request by wincent**
Just putting this up here again so that we can see a full `ci:test` run on it.

Previous tests (just `ci:test:sf` and `ci:test:relevant`) can be seen in https://github.com/wincent/liferay-portal/pull/64

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test

**Comment by wincent** [comment]
cc @jbalsas — now, watch this PR go 💣 💥 🔥

**Comment by jbalsas** [comment]
popcorn

**Comment by wincent** [comment]
Corresponding "master-private" test PR: https://github.com/wincent/liferay-portal-ee/pull/2

**Comment by jbalsas** [comment]
nonono

**Comment by wincent** [comment]
Actual snippet of where it is blowing up:

```
$ liferay-npm-scripts build
Using pre-existing NODE_ENV: "development"
Compiling soy
Generated src/main/resources/META-INF/resources/management_toolbar/ManagementToolbar.soy.js
Finished compiling soy
Successfully compiled 2 files with Babel.


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:1152:7)
    at Object.resolveModuleFile (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/liferay-npm-build-tools-common/lib/packages.js:118:66)
    at replaceMainModule (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/liferay-npm-bundler-preset-standard/node_modules/liferay-npm-bundler-plugin-replace-browser-modules/lib/index.js:57:45)
    at Object.exports.default [as run] (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/liferay-npm-bundler-preset-standard/node_modules/liferay-npm-bundler-plugin-replace-browser-modules/lib/index.js:15:3)
    at /Users/greghurrell/code/portal/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/liferay-npm-bundler/lib/steps/util.js:162:10
    at Array.forEach (<anonymous>)
    at runPlugins (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/liferay-npm-bundler/lib/steps/util.js:148:10)
    at /Users/greghurrell/code/portal/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/liferay-npm-bundler/lib/steps/transform.js:146:37
    at new Promise (<anonymous>)
```

Seems unrelated to the JSP stuff, at least.

**Comment by wincent** [comment]
Replaced by: https://github.com/wincent/liferay-portal/pull/79

**Pull request closed without merging**
