### PR TITLE
LPS-98114 Create proper "main" entry points in DDM package.json files

### PR DESCRIPTION
**Pull request by wincent**
dynamic-data-mapping-form-field-type no longer has a misleading "main" field, or any "main" field at all, in fact; I removed it because nothing else in liferay-portal is importing from it.

In dynamic-data-mapping-form-renderer, I added a valid "main" entry pointing to a new "index.js" file. Given that a couple of projects outside of dynamic-data-mapping import files from this project, I felt the safest thing to do was to limit the things in the index in the following way:

- Only things that are actually imported by other projects.
- Only modules that don't have any side-effects (like registering Soy templates); it might be bad for other projects to trigger such side-effects unintentionally just by importing the index, but they can still do so explicitly by importing the specific files further down the tree.

I'm updating liferay-npm-scripts here too because in order to test all this I found inconsistencies with the way we importing Soy files (eg. some ".soy" and some ".soy.js"). I made changes to ensure we handle both, but I also swept through the repo and standardized on ".soy". I'll be adding a lint to auto-enforce that shortly.

Found some existing broken tests in app-builder-web while working on this, so I fixed those too.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@jbalsas: this is the change I was showing you earlier. Relevant liferay-npm-scripts changes are:

- https://github.com/liferay/liferay-npm-tools/pull/361/commits/12d9bc435bb522e19755ecb45c2047c04eaf30ff
- https://github.com/liferay/liferay-npm-tools/commit/8fb9ee54076a4de4a1489f565cb8c27ba8d01ddc

@john-co: I think the changes of the Soy imports are good (tests are green, my own crude build testing and manual QA seem fine), but Chema was a little nervous about it so I'd appreciate it if you could flag anything that looks off. For what it's worth, we had 93 places where we imported as ".soy" and 65 where we used ".soy.js", so I think either should "work", but it's obviously desirable for us to be consistent regardless.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
cc @brunobasto

**Comment by john-co** [comment]
ci:test:bundle

**Comment by brunobasto** [comment]
Awesome @wincent! Looks great. Thank you

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
- modules-semantic-versioning-jdk8 version warning looks possibly related. Rerunning `ci test relevant`
```     [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.dynamic.data.mapping.util              MINOR      2.0.0      2.0.0      2.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.dynamic.data.mapping.util.DDMFormValuesToMapConverter
     [exec] 		+   access     abstract
     [exec] 		+   method     convert(com.liferay.dynamic.data.mapping.storage.DDMFormValues,com.liferay.dynamic.data.mapping.model.DDMStructure)
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.Map
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.dynamic.data.mapping.api-6.2.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.dynamic.data.mapping.api/6.1.0/d8bc573ad996e8ac56516476839ca5da515947f7/com.liferay.dynamic.data.mapping.api-6.1.0.jar
```

- Functional test failures are unrelated.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
The modules-semantic-versioning test failure exists in upstream.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Thanks for looking this over @john-co. Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/84022

**Pull request closed without merging**
