### PR TITLE
LPS-112298 Update Liferay.Util.selectEntity utility

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

Going into this task, I was planning to make new versions of `selectEntity` and `selectEntityHandler` utilities. However, I found that we can massively simplify code, by only using `openModal`, exending its API with the `onSelect` callback. In this PR, we are updating usages in `fragment-web`.

To test fragment entry move 1
1. Open Control Panel → Site → Site Builder → Page Fragments
1. Add two sample collections and a sample fragment component in the first
1. Click component dropdown → Move
1. Select second collection

To test fragment entry move 2
- The same as previous, except use management toolbar instead of component dropdown (select a card to open toolbar)

To test fragment entry copy 1
1. On Page Fragments page, open Basic Components
1. Click component dropdown → Copy To
1. Select previously created sample collection

To test fragment entry copy 2
- The same as previous, except use management toolbar

I was not able to test fragment composition move, I could not find this in UI. WIP maybe? You need to create fragment composition somehow, and then it is the same dropdown as in the first test. I am pretty confident this would work, it is the same change as in other usages. Product team should be able to test this.

Sidenote: What bugged me a bit is that `onSelect` seems deceptively generic, similar to unambiguous `onClose`. However, it requires very specific structure to work, `.selector-button` elements in content with data attributes. It inherits this from `selectEntity` util, which has equally hardcoded implementation requirements, that user of utility must know. Maybe it would make sense to have a more generic API, at least with custom trigger class and custom attribute. But, I opted to to keep it closer to original way of using it, at least for now. We can always easily extend API later on, if we want to.

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @markocikos!

> I found that we can massively simplify code

Sounds promising!!

Keep in mind when asking questions that the design here might be tricky depending on the pieces involved. Usually, we have a calling site (`selectEntity`) and a callee in a JSP inside an iframe. 

Communication used to go in and out of the iframe via the real API `eventName` through `Liferay.getOpener().Liferay.fire` and `Liferay.on`. So, the key API is that `eventName` event emission and not the `.selector-button` which is rather a forced convention. Someone not using that could still just fire their custom entity result and get it selected.

Since this is what it is, and it hasn't evolved in time... it's unlikely it will now, but people from other teams actually own the ItemSelector, so we might want to ping them about this, just to be on the same page.

@adolfopa, anyone from your team might have insight or interest int his topic?

**Comment by markocikos** [comment]
> Keep in mind when wondering about the design and the decisions in there that it might be tricky depending on the pieces involved. Usually, we have a calling site (`selectEntity`) and a callee in a JSP inside an iframe.
> 
> Communication used to go in and out of the iframe via the real API `eventName` through `Liferay.getOpener().Liferay.fire` and `Liferay.on`. So, the key API is that `eventName` event emission and not the `.selector-button` which is rather a forced convention. Someone not using that could still just fire their custom entity result and get it selected.

`.selector-button` is a key part in `Liferay.Util.selectEntityHandler`, see [here](https://github.com/liferay/liferay-portal/blob/ad9a7eb092afbc7f345a66c4b0202854b4cc9fbb/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1299), delegation is defined on it. Util in this PR inherits the same behavior. Custom event name is fired in that delegation execution, and on it we execute callback, see [here](https://github.com/liferay/liferay-portal/blob/ad9a7eb092afbc7f345a66c4b0202854b4cc9fbb/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1415). I found this pattern to be unnecessary. Just like multiple utilities can reuse custom event from one jsp, the same utilities can reuse selector elements data from the same jsp. Is there a use case where custom event would be beneficial?

**Comment by jbalsas** [comment]
> .selector-button is a key part in Liferay.Util.selectEntityHandler, see here [...]

Believe it or not... and rusty as I may be... I know how this and most of the other parts of the system work 😂 

> [...] I found this pattern to be unnecessary [...]

As unnecessary as this seems, you're now switching from an explicit API to an implicit one. Let me walk you through this.

The concept of an `ItemSelector` is a very generic one in that it allows a developer to implement a view that can be used to select an `Item`.

To that end, we offer a very generic API. We tell developers this in our documentation (more or less)

> You can implement your custom view and register it to be used in an item selector. The way you signal the system of your selection is by emitting the event `eventName` that's injected in your view by the system and passing in it your selected entity like this:
>
> ```javascript
> const eventName = '<%= HtmlUtil.escapeJS(eventName) %>';
> 
> Liferay.Util.getOpener().Liferay.fire(eventName, entity);
> ```

That means, regardless of how you implement your view, the HTML it renders and how the logic works, you can always signal the system that you're done selecting an entity via one explicit API.

This is the key architectural design and principle and a simple enough contract we offer and can easily maintain over time.

---

Now, we step away from infrastructure and move into view implementation. Team Echo goes and implements `select_fragment_collection.jsp `... other teams see this first implementation and copy it to build their own... over time, patterns start emerging!!

We realize that **IN OUR STANDARD VIEWS** we always sort of have a "Select" button and the data needs somehow to be passed down from the Server to the Client.

So, as an infra team (at the time), we take this **PARTICULAR BOILERPLATE** and encapsulate in a util and tell **OUR INTERNAL TEAMS** that they can abstract from the generic API if they follow this convention:
1. They need a `<button class=".selector-button">`
2. All the `data-*` attributes in that trigger button will be passed down as your result to the system
3. If you follow the above points, just run `Liferay.Util.selectEntityHandler(...)` to set it all up for you

This is just an additional layer **on top of the designed API** aimed at speeding up development for our internal teams.

--- 

With this change as is, we're basically breaking a generic API that allows for any view implementation for a specific and very restrictive one that forces a specific design and UX. 

It works because of how views are right now, but as soon as that changes, we'll be forced to heavily change the `onSelect` implementation to account for it. 

Imagine that rather than from a button, you want to trigger the select from a JS function, through a remote validation, after a random animation... 

As a final note. I really like the `onSelect` API. I also like to simplify views implementation as much as we can, that's why we offered the `selectEntityHandler` API. We can benefit from our strong conventions to offer small utilities that help our teams set things up, but we also need to account and design the right APIs for customization and future evolution.

**Comment by jbalsas** [comment]
Just to reiterate a point that might not be clear from yesterday's dissertation:
1. We code our call to `selectEntity` (or `openModal`) in DXP.
2. That call usually points to an item-selector-like URL
3. We implement our out of the box item-selector-compatible views to select our entities
4. Customers can inject their own views into that modal which will show as tabs

It's because of 4 that 1 needs to offer an API and 3 rely on it in the end.

**Comment by markocikos** [comment]
See https://github.com/wincent/liferay-portal/pull/263

**Pull request closed without merging**
