### PR TITLE
LPS-111241 Replace <liferay-ui:input-editor> with  <liferay-editor:editor> in frontend-taglib

### PR DESCRIPTION
**Pull request by julien**
The goal of [this](https://github.com/wincent/liferay-portal/commit/79045a8d3dfa4adbeab491357f6dcc2fa1881bc0) change is to replace [`<liferay-ui:input-editor>`](https://github.com/liferay/liferay-portal/blob/ad1be5795224c2d6e22f8939b81427742a55740c/util-taglib/src/com/liferay/taglib/ui/InputEditorTag.java) 
(which was deprecated in 7.1.0) with [`<liferay-editor:editor>`](https://github.com/liferay/liferay-portal/blob/ad1be5795224c2d6e22f8939b81427742a55740c/modules/apps/frontend-editor/frontend-editor-taglib/src/main/java/com/liferay/frontend/editor/taglib/servlet/taglib/EditorTag.java).

### CODE REVIEW

**Comment by julien** [comment]
I forgot to mention that this PR passed the CI tests [here](https://github.com/julien/liferay-portal/pull/260)

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@wincent another thing I forgot to mention is how to test this change:

From the **Control Panel** navigate to **Configuration** > **Instance Settings** and search from "email"

You should see something like this 

notification_settings

The editor for the content of the notification is now using `<liferay-editor:editor>`, and updating the message in that editor by clicking on the "Save" button at the end of the page shouldn't throw any errors.

You'll also notice that there are various places that are affected by this change:
Account Created Notification
Email Verification Notification
Password Changed Notification
Password Reset Notification

If you need any more details, please let know.

Thanks!

**Comment by jbalsas** [comment]
Hey @julien, @wincent!

> [...] by clicking on the "Save" button at the end of the page shouldn't throw any errors.

I would also expect that the content (with changes) is saved properly and can be edited again... just saying that "not throwing errors" might not be a safe assertion on its own 😉

**Comment by julien** [comment]
@jbalsas you're right, I updated my description

**Comment by jbalsas** [comment]
Also... alignment seems off in that screenshot... @drakonux, @victorvalle, can you confirm what should be the right alignment and size? This is likely an inherited issue, but just so we can track it down in the future...

**Comment by jbalsas** [comment]
All green!! 😱 

sisteract

**Comment by wincent** [comment]
I tested this and can confirm edit/save/reload cycle works, and no alignment problems in Chrome on this PR or in master at the screen width I'm using.

Master:

Screen Shot 2020-04-01 at 17 41 34

PR:

Screen Shot 2020-04-01 at 17 41 40

**Comment by wincent** [comment]
ci:forward

**Comment by jbalsas** [comment]
mexicanwave

**Comment by victorvalle** [comment]
Could you remove the left and right margin/padding that makes it look indented?
The distance to the form borders should be 24px

**Comment by wincent** [comment]
Thanks for the review @victorvalle. I created https://issues.liferay.com/browse/LPS-111414 to track the fix.

**Pull request closed without merging**
