### PR TITLE
LPS-112480 Add focus styles and fix border

### PR DESCRIPTION
**Pull request by carloslancha**
Adding focus styles to CKEditor and fixing nicked borders.

Before:
image

After:
image

How to test it:
Go to any app with an editor (i.e: Content & Data > Web Content > Add new Basic Web Content)

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Chema likes it

**Comment by jbalsas** [comment]
> [exec] apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_editor_ckeditor.scss: BAD

Prettier likes it... NOT!

**Comment by wincent** [comment]
love-me

**Comment by carloslancha** [comment]
SF hates me

image

Sent this to Marcos anyway, I free you from this one so you can... don't know, eat?

**Comment by wincent** [comment]
> Sent this to Marcos anyway

i-love-it

**Pull request closed without merging**
