### PR TITLE
LPS-115202 Site Selector icon becomes difficult to see when hovering over it in the 7.0 theme

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-115202

From @wanderlast: 

> This fixes an issue that specifically is only visible in the DXP 7.0 theme, but not in the current theme in Master where the site item selector icon can become difficult to see/invisible when hovering over it. This is caused by the CSS using the default .product-menu > a > &:hover color since icon-sites only specifies a color for a link, not hovering over a link. We fix this by explicitly setting a color while hovering over it.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Looks reasonable to me, but would be good to get @marcoscv-work to take a look to.

**Comment by marcoscv-work** [comment]
@ChrisKian this bug is only reproducible on DXP 7.0, since this version has its own design version of the product menu (color inverted).

image

The change should be done in the specific DXP 7.0 theme contributor and the PR should be reviewed by @antonio-ortega

Closing this PR.
Thank you!!

**Pull request closed without merging**
