### PR TITLE
LPS-96615 Use event delegation in side_navigation.es.js

### PR DESCRIPTION
**Pull request by wincent**
I tried to fix this in a few different ways until finally finding one that works. Showing my work here but will squash before I forward upstream.

The main trade-offs here:

- We really need an "id" to do event delegation reliably, but we don't want to have to cut a Clay release just to jam one in to the management toolbar (although I could potentially have found a way to do it locally in the liferay-portal copy of the toolbar, I prefer to keep the changes inside of `side_navigation.es.js` because the plug-in should "take care of" things like this).
- This is fragile but we only use an id-less toggle button in one place, and we're not going to be adding any more metal components, or making big changes to the management toolbar etc. Basically, until everything is moved over to React, I don't expect any significant changes in this area — and even if we do make changes, there's a good chance this will still work.
- The old version worked only because the management toolbar prevented the plug-in from getting the click event (via `preventDefault()`) and did the toggling itself. I removed that in https://github.com/liferay/liferay-portal/commit/b0ec2fe8bff558f094382186e2b66a6f09858206 because I didn't realize exactly what it was hacking around; but I'd rather keep the workaround inside the plug-in than out in "user space". Having to manage the toggle state from the outside partially defeats the purpose of the plug-in.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
@julien and @jbalsas: here is the "final fix".

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Sounds good to me!

**Comment by wincent** [comment]
Upstream: https://github.com/brianchandotcom/liferay-portal/pull/74362

**Pull request closed without merging**
