### PR TITLE
LPS-111501 Update liferay-npm-scripts to v29.0.0

### PR DESCRIPTION
**Pull request by john-co**
This one was stuck in CI limbo for several days at: https://github.com/wincent/liferay-portal/pull/199

Original message:

---

[Release notes](https://github.com/liferay/liferay-npm-tools/tree/liferay-npm-scripts/v29.0.0):

- "import-extensions" rule catches more problems.
- Make storybook work in contexts that need frontend-js-react-web.

JIRA: https://issues.liferay.com/browse/LPS-111501

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:foward

**Comment by wincent** [comment]
Trying again, as system seemed to ignore that comment, even after 11 hours.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
```
Target exception: java.lang.RuntimeException: Unable to rebase john-co-200-LPS-111501 to master
error: Failed to merge in the changes.
```

I'm going to rebase this manually.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
4 hours and still hasn't finished, so I think it may be suffering from the problems described in `#ci`:

> We had an incident in CI last night that caused 4 out of 24 of our Jenkins masters to go down. They are currently offline awaiting restart by IT. If you have observed any strange behavior (i.e. pull request tests failing to complete), please try running your test again.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
