### PR TITLE
LPS-111878 Enable addition of SCSS files in frontend-js-web

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/liferay-echo/liferay-portal/pull/218

I don't think it makes sense to send modal API extension without application sample, but we can take care of this change separately. That should hopefully remove a layer of confusion from the whole thing. When this is merged, we can followup with the rest to the Echo team.

This change is needed for modals because without it we cannot add an `.scss` file to `frontend-js-web`.

Please review the code.

Thank you!

/cc @jbalsas

---

Ancestry:

- https://github.com/wincent/liferay-portal/pull/192
- https://github.com/jbalsas/liferay-portal/pull/2154
- https://github.com/markocikos/liferay-portal/pull/182
- https://github.com/wincent/liferay-portal/pull/198
- https://github.com/wincent/liferay-portal/pull/203
- https://github.com/liferay-echo/liferay-portal/pull/156
- https://github.com/liferay-echo/liferay-portal/pull/218 and spin-offs:
  - https://github.com/markocikos/liferay-portal/pull/183
  - https://github.com/markocikos/liferay-portal/pull/184
  - https://github.com/markocikos/liferay-portal/pull/185
- https://github.com/wincent/liferay-portal/pull/204

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Your call if you want to ship this separately, @markocikos. Go ahead and `ci:forward` if you want.

**Comment by markocikos** [comment]
All tests green! I don't remember last time I've seen this!


beautiful

**Comment by markocikos** [comment]
ci:forward

**Comment by wincent** [comment]
> All tests green! I don't remember last time I've seen this!

dont-know-how-to-feel

**Pull request closed without merging**
