### PR TITLE
LPS-112182 [DO NOT MERGE] Update to Prettier v2.0.4

### PR DESCRIPTION
**Pull request by wincent**
This is a "DO NOT MERGE" demo of a PR that touches many files (about 1450), for the purposes of stress-testing CI.

Passing the test means that we should re-do this The Right Way(tm) before actually merging; ie. via an update to liferay-npm-scripts.

Why are there so many changes? Because this is the first v2 release we're using.

See: https://prettier.io/blog/2020/03/21/2.0.0.html

Related: https://github.com/liferay/liferay-npm-tools/issues/418

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
@hhuijser: does https://github.com/wincent/liferay-portal/pull/211/commits/ea0a861b5c94ef9b4fff8360a31d14e6e5e01852 look ok to you? I had to teach `JSPWhitespaceCheck` to leave `function` formatting alone in order for it to be compatible with Prettier v2.

[4 SF failures here](https://github.com/wincent/liferay-portal/pull/211#issuecomment-616583751), but they are unrelated to my changes and I figure they only got surfaced because I made a change in `modules/util/source-formatter` and that caused every thing to be rechecked.

**Comment by wincent** [comment]
@hhuijser: sorry, correct commit link is actually: https://github.com/wincent/liferay-portal/commit/279056f704f54295539e5e291ddfff47709f82cf

**Comment by wincent** [comment]
Three hours since I asked for `ci:test:relevant` to run and the bot added the "pending" labels but there is no evidence of the build being in the queue (that I can see), so I'm going to try issuing that again.

CleanShot 2020-04-20 at 18 03 31@2x

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@john-co: Can you please give your assessment on the `ci:test:relevant` failures above?

This is an example of the kind pull that I'd to discuss with Brian on the weekly sync call (specifically, because it is a large change that touches > 1,000 files, but because it is a fully automated formatting change only it should be "safe" and not break anything).

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
**Analysis:**
- [Unrelated] modules-compile-jdk8 - known issue in upstream - https://issues.liferay.com/browse/LPS-112206 - https://testray.liferay.com/home/-/testray/case_results/1120019224/history?tab=result&hideFilterPin=true
- [Unrelated] modules-integration - the blogs errors are no longer reproducible in upstream but there are other common failures that still remain
- [Unrelated] modules-unit-jdk8 - no longer reproducible in upstream

These should be listed as in common and not unique failures. I will reach out to CI team to take a look.

**Comment by john-co** [comment]
Maybe until then, we'll need to manually determine if tests are related or are reproducible with base branch/upstream. If not related, we can directly send to BChan.

**Comment by john-co** [comment]
Hi @wincent, I asked CI team about timeframe on https://issues.liferay.com/browse/LRCI-1208, and it looks like this won't be a quick and easy way to implement. It's currently a medium priority. So I think the best route for now is to manually send to BChan for these kind of scenarios as you did in https://github.com/wincent/liferay-portal/pull/217#issuecomment-617745901

**Comment by wincent** [comment]
Ok, once https://github.com/izaera/liferay-portal/pull/139 gets forwarded, I'll update liferay-npm-scripts to use the new version of Prettier and will send this for real. Closing this on in the meantime. Thanks for your help @john-co!

**Comment by wincent** [comment]
Ok, real deal is queued for testing at: https://github.com/wincent/liferay-portal/pull/233

**Pull request closed without merging**
