### PR TITLE
LPS-111979 Center CKEditor dialogs

### PR DESCRIPTION
**Pull request by julien**
The goal of this fix is to "center" CKEditor's dialogs.

Since our recent change to use CKEditor in more places, CKEditor dialogs
are now aligned in the top left corner instead of being centered.

The only previous commit I could find concerning this file is in
[https://github.com/liferay/liferay-portal/commit/a4df2c65a8fb39c139e0e9781078b2092c868f68](https://github.com/liferay/liferay-portal/commit/a4df2c65a8fb39c139e0e9781078b2092c868f68),
when the file was initially added.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@julien: Can you explain *why* this change fixes things? I can see you removed the `if (window.top != window.self)` guard, which I interpret to mean:

- Code used to adjust position if "current" window is an iframe.
- New code adjusts position unconditionally.

Why did the old code only want to do it conditionally?

**Comment by julien** [comment]
> Code used to adjust position if "current" window is an iframe.
> New code adjusts position unconditionally.
> Why did the old code only want to do it conditionally?

That's also how I interpreted it.

I tested this code in `master`, `7.2.x` and a `7.3.1-ga2` bundle, adding a breakpoint inside the `if (window.top != window.self)` block but it never gets hit.

Once difference is that in previous versions, the dialogs would be centered automatically when shown, and in master it appears in the top left corner until the "title bar" is clicked. On the CKEditor4 [demo](https://ckeditor.com/ckeditor-4/demo/index.html) the dialogs also appear "centered" so something must have changed on our side, but I can't find what (I might have to do something with styles, i.e. some elements have a `display: flex` property and that wasn't the case in `7.2..x` for example).

I searched in CKEditor4's' repository as well to check but I couldn't find anything relevant.

To also reflect what we were saying over in slack, I think this fixes something that is currently broken so it can't be worse than it is now.

**Comment by wincent** [comment]
> I think this fixes something that is currently broken so it can't be worse than it is now.

While it's not super satisfying not to know why we originally added the conditional 5 years ago, I think this is the key point: you're unlikely to make things worse by shipping this PR, and you tested it as extensively as you could.

**Comment by wincent** [comment]
ci:forward

**Comment by jbalsas** [comment]
My bet is that used to do something when CKEditor was (or wasn't) inside an Iframe

**Comment by wincent** [comment]
Yeah, I already mentioned the iframe thing. The question is, what is the "something"?

**Comment by wincent** [comment]
Or rather, we know what the "something" is (it moves the dialog) — what we don't know is *why* it used to be needed only conditionally (based on iframe-ness), vs now, when it seems to be necessary in all cases.

**Comment by jbalsas** [comment]
So, here's my process:

1. Go to JIRA
2. Type `ckeditor dialog center`
3. See [CKEditor dialog windows are incorrectly positioned when the editor instance is running in a dialog panel or pop-up](https://issues.liferay.com/browse/LPS-30384)
4. Navigate to [Git Pull Request](https://github.com/natecavanaugh/liferay-portal/pull/854)
5. See changes in [LPS-30384 CKEditor dialog windows are incorrectly positioned when the editor instance is running in a dialog panel or pop-up](https://github.com/natecavanaugh/liferay-portal/pull/854/commits/e705439247b627e38cd8d157809c8d067d96a218)

**Comment by jbalsas** [comment]
> what we don't know is why it used to be needed only conditionally (based on iframe-ness), vs now, when it seems to be necessary in all cases.

Yup, just trying to put my process out there so @julien can find more context in the future

**Pull request closed without merging**
