### PR TITLE
LPS-105707 | Remove jQuery from product-navigation-site-administration

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This one is interfering with my testing and is a quick win.

Please review the code.

Thank you!

### CODE REVIEW

**Comment by wincent** [comment]
Looks good to me, although we should keep track of the number of individual event listeners we are adding in this way. A small number might be ok, but if that number grows to large, I think we'll want to switch to something that uses event delegation instead.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
CI seems to be asleep... 🤔

**Comment by markocikos** [comment]
@wincent To test this, click on "Go to Other Location" arrows icon in product navigation.

**Comment by wincent** [comment]
Thanks @markocikos!

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/81965

**Pull request closed without merging**
