### PR TITLE
LPS-94712 | Make a utility that encapsulates common 'fetch' configuration and use

### PR DESCRIPTION
**Pull request by markocikos**
Hi @wincent ,

Please review the code. Thank you!

@jbalsas I think this should be the final utility, without any additional convenience methods, as I previously suggested in https://github.com/jbalsas/liferay-portal/pull/1787#issuecomment-495207844. After taking a long look on the way we use `fetch` and `A.io.request`, I found many cases of irregular behavior when we would default have to default to `Lifery.Util.fetch`, or write a very extensive API, which defeats the purpose. I also tried few ways to implement response type as a part of init, but I was not happy with results: readability was not significantly improved, and I got ugly flashbacks of working with AUI and uncertainty what the API allowed or not. It does not help that we have a third `PortletBase.fetch` API, that looks similar, but is quite different. By sticking as close as possible to vanilla JS, we will only minimally increase the confusion.

How do we proceed with applying this to the portal? There are ~100 uses of `fetch` and ~100 uses of `A.io.request`. Is there a risk of code being backported to a portal version without `Liferay.Util.fetch`? Surrounding every single use with `if (Liferay.Util.fetch)` seems less than ideal. Is it maybe possible to ensure backport of this util to all supported versions? Do we wait for release, as this is a rather risky change? Do we apply only to `frontend-js-web`?

### CODE REVIEW

**Comment by wincent** [comment]
> Is there a risk of code being backported to a portal version without `Liferay.Util.fetch`?

I am sure @jbalsas will have the definitive answer on this one, but given that this module is relatively small, it seems that backporting is within the realm of possibility. If we wanted to minimize the risk of backporting a behavior change (new defaults) that might have unanticipated side effects, we could effectively just backport a tiny stub that did nothing more than `Liferay.Util.fetch = fetch` (ie. the global `fetch`, which I know we polyfill for IE currently, and would just want to check that we do it back in 7.1, 7.0 as well).

**Comment by jbalsas** [comment]
We will backport this to 7.2.x. It's unlikely (but not impossible) that code depending on it will make it even further, but then we should be able to backport this piece too, so we probably needn't worry about this much.

**Comment by markocikos** [comment]
@jbalsas To be 100% clear, is it ok that we:
1. Replace all `fetch` usages in portal to `Liferay.Util.fetch`
1. Replace all `A.io.request` in portal with `Liferay.Util.fetch`

**Comment by jbalsas** [comment]
Sounds good to me, yeah 👍

**Comment by markocikos** [comment]
Great! 

@wincent If all is ok with PR, please forward it to Brian. I will followup with several PRs with usage updates, sending them to responsible people of the modules being updated.

**Comment by wincent** [comment]
@markocikos: Sounds good. I'll do an SF and send onwards.

**Comment by wincent** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/74096

**Pull request closed without merging**
