### PR TITLE
LPS-113636 The Setup Wizard page is displayed incorrectly

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/marcoscv-work/liferay-portal/pull/320, an alternative solution.

We are reverting addition of iframe class in theme template. This will fix the issue of the ticket, as well as styles on any other page that used modal template outside modal.

After revert, we again have the issue that modal navigation sometimes does not set iframe body classes. What I discovered today is we do not have this issue if use SPA-enabling `Liferay.Util.navigate` util. So, [the changes in onLoadHandler](https://github.com/wincent/liferay-portal/commit/da4b8eada9cf84ec32a38f67f028139cb1f8e031#diff-45c988fca3398d3143e41f2f53e309a7R316-R327) are not needed if we [make this change](https://github.com/wincent/liferay-portal/commit/a7f32fcde8e858cdf981847f45f5a7d084e8ef95). However, there are two problems with this:
1. There are probably other usages where we directly set url and open it in modal. I didn't find any, it seems that most open top window url, but they do likely exist.
1. People can turn off SPA.

So, we are providing a solution for raw url change, but in it there is still a small issue. To reproduce:
- Revert [this line](https://github.com/wincent/liferay-portal/commit/a7f32fcde8e858cdf981847f45f5a7d084e8ef95). The issue is fixed in that line, but it will exist on the same type of usage.
- Open configuration of Web Content Display app.
- Browse tabs. Note - footer looks the same.
- Select a web content, choose one.
- Note - footer looks the same. The class this time was set on onload event. We have a spinner so there is no glitching.
- Browse tabs. Note - footer styles break, the class on body is not set.

I think we can move forward with this, as the existing issue is a minor one, specially compared to the one in the ticket. The issue will eventually be completely fixed, as a part of usages update.

Please review the code.

Thank you!

/cc @jbalsas @marcoscv-work

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Thanks @markocikos.

> I think we can move forward with this, as the existing issue is a minor one, specially compared to the one in the ticket. The issue will eventually be completely fixed, as a part of usages update.

Sounds reasonable. I'll test this once I can download the bundle, which probably means tomorrow morning.

**Comment by jpince** [comment]
ci:test:relevant not sure what happened, portal-impl/bnd.bnd already shows version `5.10.2`

**Comment by wincent** [comment]
Tested this with bundle as follows:

1. Added `setup.wizard.enabled=true` to `portal-setup-wizard.properties` (also to `portal-ext.properties` because I don't actually know which one I was supposed to put it in).
2. Took screenshot.

Screenshot 2020-05-19 -115922-IXpneh6g@2x

3. Spot checked some other modals in liferay-portal to make sure they don't look broken.

CI is green, so this looks good to forward.

**Comment by wincent** [comment]
ci:forward

**Comment by jpince** [comment]
Thanks, @wincent!
> Added setup.wizard.enabled=true to portal-setup-wizard.properties (also to portal-ext.properties because I don't actually know which one I was supposed to put it in).

I believe to activate the setup wizard, you delete `portal-setup-wizard.properties` and set the property to true in `portal-ext.properties`, OR make sure the property is _not_ set in `portal-ext.properties` (since it's set to true by default in `portal.properties`).

**Pull request closed without merging**
