### PR TITLE
LPS-123515 Update @liferay/npm-scripts to v36.1.1-pre.4

### PR DESCRIPTION
**Pull request by wincent**
To test out this commit, principally:

    fix(npm-scripts): try formatting JS in JSP inside build

    Just testing the claim made in this Slack thread:

    https://liferay.slack.com/archives/C04D8HMEF/p1606323974062700?thread_ts=1606233408.059000&cid=C04D8HMEF

    that the reason why my earlier attempts to minify-in-place inside
    "build/" may have seemed to not be working due to Gradle caching.

    While the cache may cause problems, I am skeptical that this will work
    because in my testing I found that `processResources` happens too late
    (after `npm-scripts` runs), but in the interests of thoroughness I am
    going to try this out and test it in a full `ant all` run anyway.

With some follow-up fixes discovered while testing, as seen [on the corresponding PR](https://github.com/liferay/liferay-frontend-projects/pull/251).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Testing now with latest version of https://github.com/liferay/liferay-frontend-projects/pull/251 and https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.1.1-pre.1

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Trying again with: https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.1.1-pre.2

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Last try for today, coming up: https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.1.1-pre.3

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Bah, even with basically _everything_ turned off, I am seeing this in a module-specific build:

```
> Task :apps:journal:journal-web:jar FAILED
warning: Unable to determine whether the annotation org.osgi.annotation.versioning.ProviderType applied to type com.liferay.portal.kernel.notifications.BaseModelUserNotificationHandler is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
warning: Unable to determine whether the annotation org.osgi.annotation.versioning.ProviderType applied to type com.liferay.portal.kernel.template.BaseTemplateHandler is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
error  : Invalid filter syntax in requirement osgi.extender=filter:="(&(osgi.extender=jsp.taglib)(uri=<%= themeDisplay.getURLCurrent() %>))". Reason Malformed query () %>))
```

Not sure if stale artifacts are involved though (that was with `gradlew clean deploy -a --rerun-tasks`); will see what an `ant all` does. Meanwhile, you can see the changes made like so:

```
cp build/node/packageRunBuild/resources/article/template.jsp src/main/resources/META-INF/resources/article/template.jsp
gradlew formatSource
git diff
```

That shows:

```diff
diff --git a/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/article/template.jsp b/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/article/template.jsp
index 1e87528f928a..b773e1059f74 100644
--- a/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/article/template.jsp
+++ b/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/article/template.jsp
@@ -71,13 +71,10 @@ DDMTemplate ddmTemplate = journalEditArticleDisplayContext.getDDMTemplate();
 			<portlet:param name="groupId" value="<%= String.valueOf(article.getGroupId()) %>" />
 			<portlet:param name="articleId" value="<%= String.valueOf(article.getArticleId()) %>" />
 			<portlet:param name="version" value="<%= String.valueOf(article.getVersion()) %>" />
-		</portlet:renderURL>
-
-		var previewWithTemplate = document.getElementById(
+		</portlet:renderURL> var previewWithTemplate = document.getElementById(
 			'<portlet:namespace />previewWithTemplate'
 		);
-
-		if (previewWithTemplate) {
+		if (previewWithTemplate)
 			previewWithTemplate.addEventListener('click', function (event) {
 				var url = '<%= previewArticleContentTemplateURL %>';
 
@@ -92,39 +89,29 @@ DDMTemplate ddmTemplate = journalEditArticleDisplayContext.getDDMTemplate();
 						ddmTemplateId = ddmTemplate.getTemplateId();
 					}
 				}
-				%>
-
-				var ddmTemplateId = '<%= ddmTemplateId %>';
-
+				%> var ddmTemplateId =
+					'<%= ddmTemplateId %>';
 				if (
+					'' !=
 					document.<portlet:namespace />fm1.<portlet:namespace />ddmTemplateId
-						.value != ''
-				) {
+						.value
+				)
 					ddmTemplateId =
 						document.<portlet:namespace />fm1
 							.<portlet:namespace />ddmTemplateId.value;
-				}
-
 				url = Liferay.Util.addParams(
 					'<portlet:namespace />ddmTemplateId=' + ddmTemplateId,
 					url
 				);
-
 				var languageId = '<%= themeDisplay.getLanguageId() %>';
-
 				var inputComponent = Liferay.component(
 					'<portlet:namespace />titleMapAsXML'
 				);
-
-				if (inputComponent) {
-					languageId = inputComponent.getSelectedLanguageId();
-				}
-
+				if (inputComponent) languageId = inputComponent.getSelectedLanguageId();
 				url = Liferay.Util.addParams(
 					'<portlet:namespace />languageId=' + languageId,
 					url
 				);
-
 				Liferay.Util.openSelectionModal({
 					onSelect: function (selectedItem) {
 						changeDDMTemplate(selectedItem);
@@ -134,66 +121,49 @@ DDMTemplate ddmTemplate = journalEditArticleDisplayContext.getDDMTemplate();
 					url: url,
 				});
 			});
-		}
-	</c:if>
-
-	function changeDDMTemplate(newDDMTemplate) {
+	</c:if> function changeDDMTemplate(newDDMTemplate) {
 		var oldDDMTemplateId =
 			'<%= (ddmTemplate != null) ? ddmTemplate.getTemplateId() : 0 %>';
-
 		if (
+			'' !=
 			document.<portlet:namespace />fm1.<portlet:namespace />ddmTemplateId
-				.value != ''
-		) {
+				.value
+		)
 			oldDDMTemplateId =
 				document.<portlet:namespace />fm1.<portlet:namespace />ddmTemplateId
 					.value;
-		}
-
-		if (!newDDMTemplate || oldDDMTemplateId != newDDMTemplate.ddmtemplateid) {
+		if (!newDDMTemplate || oldDDMTemplateId != newDDMTemplate.ddmtemplateid)
 			if (
 				confirm(
 					'<%= UnicodeLanguageUtil.get(request, "editing-the-current-template-deletes-all-unsaved-content") %>'
 				)
 			) {
 				var uri = '<%= themeDisplay.getURLCurrent() %>';
-
 				var ddmTemplateId =
 					(newDDMTemplate && newDDMTemplate.ddmtemplateid) || -1;
-
 				uri = Liferay.Util.addParams(
 					'<portlet:namespace />ddmTemplateId=' + ddmTemplateId,
 					uri
 				);
-
 				document.<portlet:namespace />fm1.<portlet:namespace />ddmTemplateId.value = ddmTemplateId;
-
 				document.<portlet:namespace />fm1.<portlet:namespace />ddmTemplateKey.value =
 					(newDDMTemplate && newDDMTemplate.ddmtemplatekey) || '';
-
 				document.<portlet:namespace />fm1.<portlet:namespace />ddmTemplateName.value =
 					(newDDMTemplate && newDDMTemplate.name) || '';
-
 				submitForm(document.<portlet:namespace />fm1, uri, false, false);
 			}
-		}
 	}
-
 	var clearDDMTemplateButton = document.getElementById(
 		'<portlet:namespace />clearDDMTemplate'
 	);
-
-	if (clearDDMTemplateButton) {
+	if (clearDDMTemplateButton)
 		clearDDMTemplateButton.addEventListener('click', function (event) {
 			changeDDMTemplate();
 		});
-	}
-
 	var selectDDMTemplateButton = document.getElementById(
 		'<portlet:namespace />selectDDMTemplate'
 	);
-
-	if (selectDDMTemplateButton) {
+	if (selectDDMTemplateButton)
 		selectDDMTemplateButton.addEventListener('click', function (event) {
 			Liferay.Util.openSelectionModal({
 				onSelect: function (selectedItem) {
@@ -205,23 +175,18 @@ DDMTemplate ddmTemplate = journalEditArticleDisplayContext.getDDMTemplate();
 					'<portlet:renderURL windowState="<%= LiferayWindowState.POP_UP.toString() %>"><portlet:param name="mvcPath" value="/select_ddm_template.jsp" /><portlet:param name="ddmStructureId" value="<%= String.valueOf(ddmStructure.getStructureId()) %>" /></portlet:renderURL>',
 			});
 		});
-	}
-
 	var editDDMTemplateLink = document.getElementById(
 		'<portlet:namespace />editDDMTemplate'
 	);
-
-	if (editDDMTemplateLink) {
+	if (editDDMTemplateLink)
 		editDDMTemplateLink.addEventListener('click', function (event) {
 			if (
 				confirm(
 					'<%= UnicodeLanguageUtil.get(request, "editing-the-current-template-deletes-all-unsaved-content") %>'
 				)
-			) {
+			)
 				Liferay.Util.navigate(
 					'<portlet:renderURL><portlet:param name="mvcPath" value="/edit_ddm_template.jsp" /><portlet:param name="redirect" value="<%= themeDisplay.getURLCurrent() %>" /><portlet:param name="ddmTemplateId" value="<%= (ddmTemplate != null) ? String.valueOf(ddmTemplate.getTemplateId()) : StringPool.BLANK %>" /></portlet:renderURL>'
 				);
-			}
 		});
-	}
 </aui:script>
\ No newline at end of file
```

Some of the whitespace changes might be problematic. For example, collapsing `</portlet:renderURL>` and the following `var` statement onto a single line... That's probably rendering out to something like `var previewArticleContentTemplateURL = 'blah' var previewWithTemplate = ...` I'll poke around a bit and see if I can avoid that undesired whitespace stripping at that point...

I'm also a bit surprised to see it stripping `braces` even with `defaults: false` in the minification settings. Maybe need a `braces: true` to force that, although I don't know whether this is one of the problems.

**Comment by jbalsas** [comment]
> Bah, even with basically everything turned off, I am seeing this in a module-specific build:

I think we can officially say you're falling through the rabbit hole ;)

rabbithole

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Closing this one as it served its purpose (of testing).

**Pull request closed without merging**
