### PR TITLE
LPS-114132 Remove charset attribute from link elements according to W3C recommendations

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
W3C validator reports:

> The charset attribute on the link element is obsolete. Use an HTTP Content-Type header on the linked resource instead.

[W3C guidelines](https://www.w3.org/International/questions/qa-css-charset)

We actually have a `TEXT_CSS_UTF8` constant with the desired `Content-Type` string (`text/css; charset=UTF-8`) and can just use that. In fact, we used to use it. It was added in [liferay@091f945](https://github.com/liferay/liferay-portal/commit/091f945e9cf3e) (in 2007) and we stopped using it in [liferay@9296f4a](https://github.com/liferay/liferay-portal/commit/9296f4aab29a6f370c2c8820d4f12af5492a840d) (in 2012), for reasons that are non-obvious, at least based on a reading of the related LPS, [LPS-30963](https://issues.liferay.com/browse/LPS-30963). It was probably dropped by accident.

### CODE REVIEW

**Comment by wincent** [comment]
@georgel-pop-lr code change looks fine to me but I'd like to confirm a couple of things:

- Is there a guarantee that we're definitely setting the correct `Content-Type` on this resource? Is there a place we can link to in liferay-portal showing that this is the case? 
- If it is not the case — for example, if it depends on application server set-up or other environmental factors — will we need to provide documentation about how to configure things correctly?

Just snooping around `.css` files served up from my local tomcat, I am not seeing encoding being set in `Content-Type` headers in general.  Random example (not related to font-awesome; it's just the first CSS request I clicked on in the inspector):
 
Screenshot 2020-05-21 -181544-25iYkJub@2x

Says `Content-Type: text/css;`, not Content-Type: text/css; charset=utf-8`.

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr code change looks fine to me but I'd like to confirm a couple of things:
> 
> * Is there a guarantee that we're definitely setting the correct `Content-Type` on this resource? Is there a place we can link to in liferay-portal showing that this is the case?
> * If it is not the case — for example, if it depends on application server set-up or other environmental factors — will we need to provide documentation about how to configure things correctly?
> 
> Just snooping around `.css` files served up from my local tomcat, I am not seeing encoding being set in `Content-Type` headers in general. Random example (not related to font-awesome; it's just the first CSS request I clicked on in the inspector):
> 
> Screenshot 2020-05-21 -181544-25iYkJub@2x
> 
> Says `Content-Type: text/css;`, not `Content-Type: text/css; charset=utf-8`.

Hi @wincent,

Thanks for taking a look, I have not found any docs regarding this change, I found this  https://issues.liferay.com/browse/LPS-111517 and I took this as a good example. 
Not sure if I understand correctly, but you think that we might need to change the attribute `Content-Type: text/css; charset=utf-8`? 
After my change and inspecting it looks like this:
Screen Shot 05-22-20 at 09 08 AM

**Comment by wincent** [comment]
> Not sure if I understand correctly, but you think that we might need to change the attribute `Content-Type: text/css; charset=utf-8`?

Yes, that's exactly what I was saying, and especially the  *might* bit... 😂

My concern is that this issue got opened because a customer ran a validator that said "you should be using the `Content-Type` header to communicate the encoding instead of the `charset` attribute (and the validator says this because [the guidelines](https://www.w3.org/International/questions/qa-css-charset) say so).

So, we remove the `charset` attribute, which makes the validator happy, but we don't *actually* follow its recommendation to put the encoding in the `Content-Type` instead, which means that we might end up closing a ticket, but *may* have actually made things worse, because we're not following through with a 100% implementation of the recommended practice.

About the `charset` attribute, the guidelines say:

> The HTML 4.01 specification describes a `charset` attribute that can be added to the `link` element to indicate the encoding of the document you are linking to. However, the use of this attribute on a `link` element is currently obsoleted by the HTML5 specification, so you shouldn't use it.

The [HTML4 spec says](https://html.spec.whatwg.org/multipage/obsolete.html#attr-link-charset):

> The following attributes are obsolete (though the elements are still part of the language), and must not be used by authors:
>
> ...
>
> `charset` on `link` elements
>
> Use an HTTP `Content-Type` header on the linked resource instead.

So there is some annoying ambiguity in there (guideline says "should", spec says "must"), but if in doubt, I'm inclined to follow the spec. Annoyingly, despite its use of the word "must", the spec seems to [require pretty clearly](https://html.spec.whatwg.org/multipage/links.html#link-type-stylesheet:attr-link-charset) that the browser support the `charset` attribute:

> If the element has a `charset` attribute, get an encoding from that attribute's value. If that succeeds, return the resulting encoding.

All of this may be moot anyway because I don't know if the font-awesome stylesheet contains anything beyond the basic ASCII subset of UTF-8 (at least, a quick inspection of the CSS downloaded from [here](https://fontawesome.com/v4.7.0/get-started/) doesn't contain anything beyond ASCII), so I don't *think* that anything would actually break as a result of not explicitly including the encoding info in the `Content-Type`.

I'd like a second opinion on this so I'm going to ping my team channel, but I think on the balance I'm inclined to accept this change.

**Comment by wincent** [comment]
Ok, chatted a bit about this in the team channel.

Roughly speaking, there are a few places where we set CSS `Content-Type`, and we have a constant for "text/css". These are the hits for `TEXT_CSS`:

- [modules/apps/frontend-css/frontend-css-rtl-servlet/src/main/java/com/liferay/frontend/css/rtl/servlet/internal/RTLServlet.java:180](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/modules/apps/frontend-css/frontend-css-rtl-servlet/src/main/java/com/liferay/frontend/css/rtl/servlet/internal/RTLServlet.java#L180)
- [portal-impl/src/META-INF/javadocs-all.xml:263904](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/META-INF/javadocs-all.xml#L263904)
- [portal-impl/src/META-INF/javadocs-all.xml:263907](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/META-INF/javadocs-all.xml#L263907)
- [portal-impl/src/com/liferay/portal/servlet/ComboServlet.java:286](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java#L286)
- [portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java:431](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java#L431)
- [portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java:453](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java#L453)
- [portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java:456](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java#L456)
- [portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java:149](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java#L149)
- [portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java:151](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java#L151)
- [portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java:88](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java#L88)
- [portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java:90](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java#L90)

The main place of interest is `DynamicCSSFilter.java`, but `AggregateFilter.java` and possibly `ComboServlet.java` are also worth a look.

Funnily, I noticed that we actually have a `TEXT_CSS_UTF8` constant with the desired  `Content-Type` string (`text/css; charset=UTF-8`) and could probably use that.  In fact, we used to use it. It was added in https://github.com/liferay/liferay-portal/commit/091f945e9cf3e (in 2007) and we stopped using it in https://github.com/liferay/liferay-portal/commit/9296f4aab29a6f370c2c8820d4f12af5492a840d (in 2012), for reasons that are non-obvious to me, at least based on my reading of the related LPS, [LPS-30963](https://issues.liferay.com/browse/LPS-30963). I think it was probably dropped by accident.

So I think the solution may actually be to update some or all current usages of `TEXT_CSS` to use `TEXT_CSS_UTF8` instead and then push-and-pray and see if anything breaks. Probably a good time to do this now, seeing as we just cut the GA.

cc'ing @jbalsas and @izaera who were the ones I was chatting with about this in the channel. Anything to add there?

**Comment by jbalsas** [comment]
> cc'ing @jbalsas and @izaera who were the ones I was chatting with about this in the channel. Anything to add there?

I think you got pretty much all. I wasn't even around when these changes happened, so I can't add more to the background. Seems reasonable that if we're always adding `charset` elsewhere, that we can safely define it as `ContentType`... 🤷

**Comment by georgel-pop-lr** [comment]
> Ok, chatted a bit about this in the team channel.
> 
> Roughly speaking, there are a few places where we set CSS `Content-Type`, and we have a constant for "text/css". These are the hits for `TEXT_CSS`:
> 
> * [modules/apps/frontend-css/frontend-css-rtl-servlet/src/main/java/com/liferay/frontend/css/rtl/servlet/internal/RTLServlet.java:180](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/modules/apps/frontend-css/frontend-css-rtl-servlet/src/main/java/com/liferay/frontend/css/rtl/servlet/internal/RTLServlet.java#L180)
> * [portal-impl/src/META-INF/javadocs-all.xml:263904](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/META-INF/javadocs-all.xml#L263904)
> * [portal-impl/src/META-INF/javadocs-all.xml:263907](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/META-INF/javadocs-all.xml#L263907)
> * [portal-impl/src/com/liferay/portal/servlet/ComboServlet.java:286](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java#L286)
> * [portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java:431](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java#L431)
> * [portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java:453](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java#L453)
> * [portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java:456](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java#L456)
> * [portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java:149](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java#L149)
> * [portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java:151](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-impl/src/com/liferay/portal/servlet/filters/dynamiccss/DynamicCSSFilter.java#L151)
> * [portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java:88](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java#L88)
> * [portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java:90](https://github.com/liferay/liferay-portal/blob/b7fae260a08f/portal-kernel/src/com/liferay/portal/kernel/util/ContentTypes.java#L90)
> 
> The main place of interest is `DynamicCSSFilter.java`, but `AggregateFilter.java` and possibly `ComboServlet.java` are also worth a look.
> 
> Funnily, I noticed that we actually have a `TEXT_CSS_UTF8` constant with the desired `Content-Type` string (`text/css; charset=UTF-8`) and could probably use that. In fact, we used to use it. It was added in [liferay@091f945](https://github.com/liferay/liferay-portal/commit/091f945e9cf3e) (in 2007) and we stopped using it in [liferay@9296f4a](https://github.com/liferay/liferay-portal/commit/9296f4aab29a6f370c2c8820d4f12af5492a840d) (in 2012), for reasons that are non-obvious to me, at least based on my reading of the related LPS, [LPS-30963](https://issues.liferay.com/browse/LPS-30963). I think it was probably dropped by accident.
> 
> So I think the solution may actually be to update some or all current usages of `TEXT_CSS` to use `TEXT_CSS_UTF8` instead and then push-and-pray and see if anything breaks. Probably a good time to do this now, seeing as we just cut the GA.
> 
> cc'ing @jbalsas and @izaera who were the ones I was chatting with about this in the channel. Anything to add there?

Hi @wincent,

I finally got a chance to do a quick test, and all seems to work just fine. Had some problems in the beginning, but seems to have been caused by some cache and cookies on my local environment. Let's pray that all works fine. Thanks for your support. 

Regards.

**Comment by wincent** [comment]
Looks good to me. Going to take it for a spin and then forward.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Bah, I'll pull this down and run SF to see if we can keep this moving along.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
CI hates this, so trying again. Manual test after local `ant all` looks good to me:

Screenshot 2020-05-27 -194937-ye3J8LyH@2x

**Comment by wincent** [comment]
I will have to disconnect soon, so going to try kicking off a forward and see if it gets lucky while I'm away overnight.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
