### PR TITLE
LPS-113411 Modals with iframe but no footer have unnecessary bottom padding

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/wincent/liferay-portal/pull/261

I reverted some unnecessary changes on fixed header, the footer styles commit is the same.

I left in the awkward 1271px width. I just cannot explain why 1280px is bigger in header row. Computed width in dev tools shows the same size. Maybe @marcoscv-work can help here. With the 1271px width, the appearance is pixel-perfect on Chrome, but 1-2 px off on Firefox.

The width change should not be a blocker to push PR. The change is limited in scope and still better than current full width size. Alternative solution would be to revert table width to 100% like it used to be, but that can be considered and maybe done in a separate task.

The changes on dialog-footer are riskier, we might want to wait for extra review on those.

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Thanks @markocikos. I mentioned @marcoscv-work in the Slack channel because I suspect GitHub notifications are getting buried. I'll take this for a spin tomorrow.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by markocikos** [comment]
@marcoscv-work I force-pushed changes. I reverted the needless change that was causing the width issue.

**Comment by wincent** [comment]
Going to re-run tests.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Optimistically assuming that CI is going to be green, going to issue `ci:forward` while I wait for the run to finish.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
