### PR TITLE
LPS-112983 Remove unused tree.scss and it's references

### PR DESCRIPTION
**Pull request by julien**
`.portlet-journal-tree` is no longer referenced, so these styles can be removed.

Original description, for posterity, from before we discovered that the styles were dead:

---

The `Liferay.BrowserSelectors` AUI module, adds css classes to the `document.documentElement` containing information about the operating system (`android`, `ios`, `linux`, `mac`, `sun`, `win`), the only usage for the `win` prefix in CSS was added in https://github.com/liferay/liferay-portal/commit/e1e9eac2d4db10ce955926a552d5809bea6b6d78 and we think it's safe to remove it.

For more information, the original discussion started in https://github.com/wincent/liferay-portal/pull/249, and more specifically [here](https://github.com/wincent/liferay-portal/pull/249#issuecomment-624717901) and [here](https://github.com/wincent/liferay-portal/pull/249#issuecomment-628042992)

I found out that this file is actually served, and this can be seen [here](https://github.com/liferay/liferay-portal/blob/ade287ef5708ee3a30962d0b2ebdb81d8fc2f0da/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/portlet/JournalPortlet.java#L108) so I just removed the `.win` prefix from the stylesheet

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> the only usage for the `win` prefix in CSS was added in [liferay@e1e9eac](https://github.com/liferay/liferay-portal/commit/e1e9eac2d4db10ce955926a552d5809bea6b6d78) and we think it's safe to remove it.

Added in a commit called "Source Format"... 😀 

> I found out that this file is actually served, and this can be seen [here](https://github.com/liferay/liferay-portal/blob/ade287ef5708ee3a30962d0b2ebdb81d8fc2f0da/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/portlet/JournalPortlet.java#L108) so I just removed the `.win` prefix from the stylesheet

Can you walk me through what this means? The file gets served up, but what does that have to do with the `.win` class?

**Comment by julien** [comment]
> Can you walk me through what this means? The file gets served up, but what does that have to do with the .win class?

Yes of course, in this [comment](https://github.com/wincent/liferay-portal/pull/249#issuecomment-628042992) Chema suggested removing the file entirely, and I just wanted to point out that this file is being served.

**Comment by jbalsas** [comment]
> Can you walk me through what this means? The file gets served up, but what does that have to do with the .win class?

I concur... the fact that is being served doesn't mean it's needed. In some of our earlier discussions I mentioned that I found no trace of the `.portlet-journal-tree` being used anywhere. That being the case, it should be safe to remove both the file and the annotation in the portlet and call it a day.

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
And after approximately 24 minutes, Git has the answer for us: 5891b9fe2dc62695c12e2d438d3e4eb3488688df

**Comment by jbalsas** [comment]
Let's FYI the echo team in the PR just so they're aware of this!

**Comment by julien** [comment]
@liferay-echo notifying you here so that you're aware of this change.

**Pull request closed without merging**
