### PR TITLE
LPS-100144 Removes no longer necessary soy/AssetTagsSelectorTag class

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
I think that, unless @carloslancha or @julien object, we can squash this before sending it over to @ealonso.

I'd say, just put everything in `asset/asset-taglib` under LPS-100139 to @carloslancha and the rest under LPS-100144 under @julien and then we're good to go :D

Or we can leave this as is :D

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Did the squash as suggested and uploaded here: https://github.com/wincent/liferay-portal/pull/74

Now will actually review it... 😁

**Comment by jbalsas** [comment]
👍

**Pull request closed without merging**
