### PR TITLE
LPS-112983 Deprecate liferay-browser-selectors

### PR DESCRIPTION
**Pull request by julien**
Previously:

- https://github.com/wincent/liferay-portal/pull/294
- https://github.com/wincent/liferay-portal/pull/291
- https://github.com/wincent/liferay-portal/pull/249

---

This is a follow up on #294, and is what I did since then:

- Fixed the source formatting for the files we mentioned [here](https://github.com/wincent/liferay-portal/pull/294#discussion_r430252746) 
- Deprecated the `liferay-browser-selectors` AUI module

I also checked for usages for the remaining css classes: 

For `.safari`:

I didn't find any usages in CSS, and for JavaScript usages, we have: 

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L305

- This doesn't depend on the classes added to `document.documentElement` by `Liferay.BrowserSelectors.run`, it uses `A.UA.safari` which is defined [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L116), and get's modified [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L318), and "reset" [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L389)
	
- It's in `frontend-js-aui-web` and we'll end up migrating or deprecating this function as well

For `.secure` this is the only usage I found:

https://github.com/liferay/liferay-portal/blob/8abc9337c7f4acd55e8ef803632f26090cafe3be/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/session.js#L362

- It doesn't depend on the classes added to `document.documentElement` by `Liferay.BrowserSelectors.run`, it uses `A.UA.secure` which is defined [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L231) and get's set [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L286) (and it looks like an "easy" replacement)
- It's in `frontend-js-aui-web` and we'll end up migrating or deprecating this function as well

For `.touch` as @jbalsas mentioned, we have 3 usages in CSS and the JS usages have been updated to use `UA.touchEnabled`.

Thanks again for your help on this one

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Should we include an update to [BREAKING_CHANGES.markdown](https://github.com/liferay/liferay-portal/blob/master/readme/BREAKING_CHANGES.markdown) for this? Because we've removed the `Liferay.BrowserSelectors.run()` call that was formerly happening un conditionally, and we've moved the code to an "optional" module (which means that it is loaded right now, but it won't be loaded later when we get to the point where we turn off frontend-js-aui-web by default).

Summarizing the other changes in [LPS-112983](https://issues.liferay.com/browse/LPS-112983):

- https://github.com/brianchandotcom/liferay-portal/pull/88887: removes usage of `.win` class.
- https://github.com/brianchandotcom/liferay-portal/pull/88945: removes usages of `.firefox` class.
- https://github.com/brianchandotcom/liferay-portal/pull/88955: removes usage of `.mac` class (technical, inlines it independently of `Liferay.BrowserSelectors`).
- https://github.com/brianchandotcom/liferay-portal/pull/88980: removes usages of `.ie` class.
- https://github.com/brianchandotcom/liferay-portal/pull/89020: removes usages of `.js` class.

So, after this PR, the removal of the `Liferay.BrowserSelectors.run()` call means that there are a number of other classes that clients will no longer get unless you add the call back somewhere. The PR adds back (via another means, and on `body` instead of `html`) some classes (`.chrome`/`.ie`/`.edge`/`.firefox`/`.other` and `.mobile`) but not all of them (see the analysis on the original PR, [#249](https://github.com/wincent/liferay-portal/pull/249) for what is probably a complete list). So this does feel like something that should be mentioned in the doc.

**Comment by wincent** [comment]
Did some testing:

Chrome on Mac:

Screenshot 2020-05-26 -142922-KSScYoI9@2x

Fake mobile:

Screenshot 2020-05-26 -142938-Dr7sen6h@2x

Fake windows + Firefox:

Screenshot 2020-05-26 -143042-r4AF6wSq@2x

**Comment by jbalsas** [comment]
> Should we include an update to BREAKING_CHANGES.markdown for this?

Yes, I think so. That's a good catch. Mis dieses

**Comment by wincent** [comment]
Thanks @julien. I pushed one tweak to the doc to your branch and will do a manual forward of this (to avoid waiting for another CI run) as soon as I see `ci:test:sf` green.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Manual forward is here: https://github.com/brianchandotcom/liferay-portal/pull/89223

**Pull request closed without merging**
