### PR TITLE
LPS-97682 | Deal with lint suppressions in product-navigation-control-menu-web

### PR DESCRIPTION
**Pull request by markocikos**
Hi Greg, <br><br>Please review the code.<br><br>Thank you!

### CODE REVIEW

**Comment by wincent** [comment]
Um, I don't think we can remove the import, can we? Isn't it begin required for its side effect?

That is to say, ac1b40d is right (other than I'd suggest we sort the imports), but 174f830 makes it wrong?

**Comment by markocikos** [comment]
@wincent I tested it and it works. Is it some local caching or setup that makes it work for me? How to reproduce failure of no side effect?

**Comment by wincent** [comment]
My guess is that as long as *something* on the page registers the `Modal`, it will work, and we use the  `Modal` all over the place, so maybe you just got lucky. @jbalsas may be able to confirm that theory.

**Comment by markocikos** [comment]
Got it. I'll resend PR without the change.

**Pull request closed without merging**
