### PR TITLE
LPS-98391 portal-web: Prevent adding default delta to URL

### PR DESCRIPTION
**Pull request by oliv-yu**
http://issues.liferay.com/browse/LPS-98391

@thektan
Just interested in a sanity check before this gets forwarded! https://github.com/oliv-yu/liferay-portal/pull/40

### CODE REVIEW

**Comment by wincent** [comment]
Looks fine to me. I don't see a clean test run on the original one so I'll just fire that off here. Feel free to `ci:forward` when it's done.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
Thanks! PR was sent to bchan

**Pull request closed without merging**
