### PR TITLE
LPS-113561 Avoid use of Liferay.provide in asset-list-web

### PR DESCRIPTION
**Pull request by wincent**
PR 1 of the 6 described here: https://github.com/wincent/liferay-portal/pull/320#issuecomment-641223200

Details provided in the commit messages.

cc @julien

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
I'm not going to re-test this. I think the description in your commit messages of the testing you did is enough.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Actually, on second thought, before we forward this, there is something I want to talk through on the [next PR](https://github.com/wincent/liferay-portal/pull/327). Going to see if I can stop.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
*Reassuring silence from bot...*

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Sigh... oh well. If it forwards anyway we can always send a follow-up. 🤷‍♂️

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:stop

**Comment by julien** [comment]
Re-sent [here](https://github.com/wincent/liferay-portal/pull/335)

**Comment by julien** [comment]
ci:close

**Pull request closed without merging**
