### PR TITLE
LPS-113848 Branches URL creation to avoid passing undefined as the base param

### PR DESCRIPTION
**Pull request by wincent**
Based on experimentation, `new URL(url, undefined)` throws a TypeError error in latest Safari Version 13.1 (13609.1.20.111.8). As a result, we avoid calling the constructur with 2 parameters when the second is not set as a string.

Previously: https://github.com/wincent/liferay-portal/pull/278

cc @jbalsas @jpince

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Shaming me with that awful commit I see!!

okayIsee

**Comment by wincent** [comment]
Forwarded as per Slack discussion: https://github.com/brianchandotcom/liferay-portal/pull/88898

Leaving tests running in the meantime.

> Shaming me with that awful commit I see!!

Nah, if it was awful, I would have done:

wat

**Comment by jbalsas** [comment]
😂 You'r just too kind!!

**Comment by wincent** [comment]
Yay. It was #0f0.

**Pull request closed without merging**
