### PR TITLE
LPS-102549 | Update FieldMappings component #2

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

Followup on https://github.com/wincent/liferay-portal/pull/88

Changes:
- added missing dependency to `frontend-js-react-web`
- rewrote editor to a component that prevents updates
- dom queries are stored in refs

I could not make `PureComponent` solution work, it continued to render on each parent state change. `shouldComponentUpdate` worked though, exactly as expected.

Please review the code.

Thank you!

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
@John-Co: Could you give us some input on whether any of these unique failures are legit?

**Comment by vicnate5** [comment]
@wincent Failures are unrelated.

**Comment by wincent** [comment]
Thanks @vicnate5.

@markocikos: I rebased this and forwarded to @arboliveira here: https://github.com/arboliveira/liferay-portal/pull/784

**Pull request closed without merging**
