### PR TITLE
LPS-113848 Branches URL creation to avoid passing undefined as the base param

### PR DESCRIPTION
**Pull request by jbalsas**
Not sure what else to say about this... fix for the `new URL(base, undefined)` problem in Safari 13.1.

This branches the URL creation... roughly tested and edited, so feel free to do this properly :D

### CODE REVIEW

**Comment by wincent** [comment]
Would you be angry with me if I suggested removing the comment? I have a feeling Brian is going to consider it superfluous, and I only add comments for stuff like this when I think there's a risk of somebody looking at it and saying, "I am going to refactor this code" but break it because they don't understand why it is the way it is. In this, case, what do you think the risk is that somebody is going to see:

```js
	let url;

	if (baseUrl.startsWith('/')) {
		url = new URL(baseUrl, location.href);
	}
	else {
		url = new URL(baseUrl);
	}
```

and turn it back into:

```js
	const url = new URL(
		baseUrl,
		baseUrl.startsWith('/') ? location.href : undefined
	);
```

?

I think if I saw it and wanted to get rid of the `let` I would change it to:

```js
	const url = baseUrl.startsWith('/')
		? new URL(baseUrl, location.href)
		: new URL(baseUrl);
```

but I probably wouldn't do the `undefined` thing... What do you think?

**Comment by jbalsas** [comment]
LOL, yeah, go with your thing :D

```javascript
	const url = baseUrl.startsWith('/')
		? new URL(baseUrl, location.href)
		: new URL(baseUrl);
```

**Comment by jbalsas** [comment]
yourpoinion

**Comment by jbalsas** [comment]
Will close, just to make sure it's clear I 100% approve of your proposal and don't want this merged!

**Comment by wincent** [comment]
Ok, I'll pull, tweak and send.

**Comment by wincent** [comment]
Updated: https://github.com/wincent/liferay-portal/pull/278

**Pull request closed without merging**
