### PR TITLE
LPS-113562 Deprecate `deprecated.js`

### PR DESCRIPTION
**Pull request by julien**
`deprecated.js` has a [comment](https://github.com/liferay/liferay-portal/blob/9b4e4366ad5f71fc89f88fe351d8f0d96d9056cb/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/deprecated.js#L15)
which mentions [LPS-2155](https://issues.liferay.com/browse/LPS-2155), in which
it is said that `deprecated.js` was added to [`portal.properties`](https://github.com/liferay/liferay-portal/blob/4ae164e4f5859d26a26c7a2600dd40044aad0aa8/portal-impl/src/portal.properties)
in order to allow deprecating JavaScript.

There's no mention of `deprecated.js` in this [`portal.properties`](https://github.com/liferay/liferay-portal/blob/4ae164e4f5859d26a26c7a2600dd40044aad0aa8/portal-impl/src/portal.properties)
file, or at least not anymore because it was removed in [`60256e30d160`](https://github.com/liferay/liferay-portal/commit/60256e30d160).
(Found with: `git log -G'\bdeprecated\.js\b' -p`)

Searching for usages of this file, with:

`git grep -G "\b\/deprecated\.js\b"`

shows this result:

`modules/apps/frontend-js/frontend-js-aui-web/src/main/java/com/liferay/frontend/js/aui/web/internal/servlet/AUITopHeadResources.java: "/liferay/deprecated.js"`

Here's a list of the usages of the constants and functions declared in
`deprecated.js`

- `Liferay.Util.MAP_HTML_CHARS_ESCAPED`: *2 usages*

`modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/bbcode/bbcode_parser.js: var entities = A.merge(Liferay.Util.MAP_HTML_CHARS_ESCAPED, {`
`modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/bbcode/bbcode_utils.js: var entities = A.merge(Liferay.Util.MAP_HTML_CHARS_ESCAPED, {`

- `Liferay.Util.actsAsAspect`: 0 usages
- `Liferay.Util.addInputFocus`: 0 usages
- `Liferay.Util.addInputType`: 0 usages
- `Liferay.Util.camelize`: 0 usages
- `Liferay.Util.clamp`: 0 usages

- `Liferay.Util.escapeHTML`: *8 usages*

`modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/input_asset_links/page.jsp: Liferay.Util.escapeHTML(`
`modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/input_asset_links/page.jsp: Liferay.Util.escapeHTML(`
`modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/input_asset_links/page.jsp: Liferay.Util.escapeHTML(`
`modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/input_localized.js: helpMessage = Liferay.Util.escapeHTML(helpMessage);`
`modules/apps/sharing/sharing-web/src/main/resources/META-INF/resources/dynamic_include/bottom.jsp: title: Liferay.Util.escapeHTML(title),`
`modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/src/main/resources/META-INF/resources/admin/js/main.js: currentName = Liferay.Util.escapeHTML(currentName);`
`modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/src/main/resources/META-INF/resources/admin/process/fields.jsp: Liferay.Util.escapeHTML(ddmStructureName)`
`modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/src/main/resources/META-INF/resources/admin/process/workflow.jsp: title: Liferay.Util.escapeHTML(event.title),`

 - `Liferay.Util.isEditorPresent`: 0 usages
 - `Liferay.Util.randomMinMax`: 0 usages
 - `Liferay.Util.randomMinMax`: 0 usages
 - `Liferay.Util.selectAndCopy`: 0 usages
 - `Liferay.Util.setBox`: 0 usages
 - `Liferay.Util.startsWith`: 0 usages
 - `Liferay.Util.textareaTabs`: 0 usages
 - `Liferay.Util.uncamelize`: 0 usages
 - `Liferay.Util.unescapeHTML`: 0 usages
 - `Liferay.Util._escapeHTML`: 0 usages
 - `Liferay.Util._unescapeHTML`: 0 usages

Some other functions, are defined via [`Liferay.provide`](https://github.com/liferay/liferay-portal/blob/4ae164e4f5859d26a26c7a2600dd40044aad0aa8/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/dependency.js#L60-L152) on the `Liferay.Util` global object.

 - `Liferay.Util.check`: 0 Usages
 - `Liferay.Util.disableSelectBoxes`: 0 usages
 - `Liferay.Util.disableTextareaTabs`: 0 usages
 - `Liferay.Util.enableTextareaTabs`: 0 usages
 - `Liferay.Util.removeItem`: 0 usages
 - `Liferay.Util.resizeTextarea`: 0 usages
 - `Liferay.Util.setSelectedValue`: 0 usages
 - `Liferay.Util.switchEditor`: 0 usages

Both `Liferay.Util.MAP_HTML_CHARS_ESCAPED` and `Liferay.Util.escapeHTML` have
been moved to the `frontend-js-web` module and `deprecated.js`
has been marked as deprecated.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@julien: I forwarded a copy to @jbalsas [here](https://github.com/jbalsas/liferay-portal/pull/2193) because I am failing to keep up with my code review responsibilities and I don't want you to end up waiting too long for a review.

**Comment by julien** [comment]
@wincent thanks

**Comment by julien** [comment]
@wincent I'm going to close this because it has been forwarded. Sorry for the noise

**Pull request closed without merging**
