### PR TITLE
 LPS-101626 Deprecate Liferay.Util.isFunction

### PR DESCRIPTION
**Pull request by julien**
Here are the reasons why we are removing this method:

- It's basic JavaScript

- We already have `isFunction` provided by AUI (see `Lang.isFunction`), metal.js, as well as other inline definitions.

Previously reviewed at: https://github.com/wincent/liferay-portal/pull/207

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hey @John-Co, when you have a chance, could you please confirm that the CI failure is not related to these changes? Thanks

**Comment by wincent** [comment]
Don't know if it can be trusted, but CI says:

CleanShot 2020-04-20 at 18 13 42@2x

(in any case, I can't imagine how this code change could break anything at all.)

**Comment by john-co** [comment]
Hi @julien, Looks unrelated and seems like an existing regression on upstream https://issues.liferay.com/browse/LPS-112137

**Comment by julien** [comment]
@wincent that's what I saw too but wasn't 100% sure, but what @john-co makes it clear.
I was basically asking this so that we could type `ci:foward` at one point. Thanks guys.

**Comment by wincent** [comment]
Now I want to know what `ci:forward` does when CI isn't green (but no unique failures)... does it retry and forward, forward without retrying, or reject? 😂

**Comment by john-co** [comment]
@wincent, there's a request for that feature https://issues.liferay.com/browse/LRCI-1208.

Unfortunately, it will still reject it if we try `ci forward` with common failures...

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
