### PR TITLE
LPS-110184 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-110184

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @manoelcyreno... this is going to get over 2 weeks soon... started back in https://github.com/wincent/liferay-portal/pull/177 and we're still seeing relevant failures...

@john-co is working around the clock, but this is clearly not enough to unblock a trivial PR such as this... can you guys do anything to speed this up?

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
We might need to send this directly same as https://github.com/bryceosterhaus/liferay-portal/pull/64#issuecomment-606800748...

**Comment by manoelcyreno** [comment]
yes, please.

@john-co , create the JIRA LRQA for the QAs of each team to investigate these issues, please.

**Comment by jbalsas** [comment]
Pushed to Brian https://github.com/brianchandotcom/liferay-portal/pull/87110

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
