### PR TITLE
LPS-110925 Update modal usages in fragment-web | WIP

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent 

 **! Work in progress !** 

The main reason I'm sending this PR early is to showcase the problem I have with CSS.

To reproduce the issue live:
1. Go to Control Panel > Site > Site Builder > Page Fragments
1. In dropdown menu next to 'Collections +', choose 'Import'

You'll see [this](https://i.imgur.com/eDS90bV.png).

We didn't see this issue in `segments-web`, because that page didn't have any unrelated AUI modals in it. This one does. If AUI modal exists, `aui-modal.css` file is loaded and affects styles globally, in our case the `.modal-dialog` class. Since removing all AUI at once is not an option, we want to override the styles. A related issue is that `ClayModal` hardcodes height of iframe to 160px. In the case of `fragments-web`, this is unacceptable. A workaround would be to revert to `full-screen` size. But, if we go that way, we will continue running into the same issue, we might as well call full size the new Lexicon recommendation.

So, overriding styles seems the best way to go. But how?
1. We cannot override styles inline, since `ClayModay` API only allows modifying styles (`otherProps`) on the top container. The styles we need to affect is on levels below.
1. We could modify `ClayModal`, to be more permissive, or to use more unique class names, but I'm guessing that's not ideal.
1. We could add styles to theme globally, but I would like to avoid this if possible.
1. We could add a custom CSS file, which I tried to do but hit a wall.

I tried [adding the CSS file](https://github.com/wincent/liferay-portal/commit/b8df98cf2d67b44a8f70b2c4ec7ccc5b7386b912#diff-c80118a1eb166c685e7c1f0675ffdf2cR20) in the same simple way [you did for Treeview component](https://github.com/liferay/liferay-portal/blob/61601e89b64240db742eceaf82e86460620bcd97/modules/apps/frontend-js/frontend-js-components-web/src/main/resources/META-INF/resources/treeview/Treeview.js#L24), but it's not working. SASS is not transpiled correctly and all I get is an error. Do we need to configure something somewhere, on module or component level? Do I need to put a different import path?

Is there maybe a better way to override syles, without adding a file?

/cc @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
> I tried [adding the CSS file](https://github.com/wincent/liferay-portal/commit/b8df98cf2d67b44a8f70b2c4ec7ccc5b7386b912#diff-c80118a1eb166c685e7c1f0675ffdf2cR20) in the same simple way [you did for Treeview component](https://github.com/liferay/liferay-portal/blob/61601e89b64240db742eceaf82e86460620bcd97/modules/apps/frontend-js/frontend-js-components-web/src/main/resources/META-INF/resources/treeview/Treeview.js#L24), but it's not working. SASS is not transpiled correctly and all I get is an error. Do we need to configure something somewhere, on module or component level? Do I need to put a different import path?

Hm, I don't know why it didn't work. In theory, you get the loader configured in most modules for free because:

- Modules are built with [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts), which uses [this `.npmbundlerrc` base config](https://github.com/liferay/liferay-npm-tools/blob/897e19e955d8c8e671a79603ea6978f9cb863a41/packages/liferay-npm-scripts/src/config/npm-bundler.json) by default.
- That config [says](https://github.com/liferay/liferay-npm-tools/blob/897e19e955d8c8e671a79603ea6978f9cb863a41/packages/liferay-npm-scripts/src/config/npm-bundler.json#L2) to use [liferay-npm-bundler-preset-liferay-dev](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-bundler-preset-liferay-dev).
- The preset [says](https://github.com/liferay/liferay-npm-tools/blob/897e19e955d8c8e671a79603ea6978f9cb863a41/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L276-L285) to use the [css-loader](https://github.com/liferay/liferay-js-toolkit/tree/9b40cb4354715c0d3c399f414bcd678785131d46/packages/liferay-npm-bundler-loader-css-loader).
- Almost all modules use the preset — there are very [few exceptions](https://github.com/liferay/liferay-portal/search?q=liferay-npm-bundler-preset-standard&type=Code) which instead use [liferay-npm-bundler-preset-standard](https://github.com/liferay/liferay-js-toolkit/tree/9b40cb4354715c0d3c399f414bcd678785131d46/packages/liferay-npm-bundler-preset-standard), and [frontend-js-web](https://github.com/liferay/liferay-portal/tree/4cee53e133d8e2744c43ff333cd8af844ae249e3/modules/apps/frontend-js/frontend-js-web) isn't one of them.

Now, note that the `css-loader` just injects CSS into the browser; it isn't responsible for compiling SCSS to CSS. I don't actually know what is responsible for that. When I look at the build output in `frontend-js-components-web`, I see these CSS-related tasks running:

```
> Task :apps:frontend-js:frontend-js-components-web:cleanBuildCSS
> Task :apps:frontend-js:frontend-js-components-web:cleanCopyCSS
> Task :apps:frontend-js:frontend-js-components-web:copyCSS
> Task :apps:frontend-js:frontend-js-components-web:buildCSS
```
Compared with `frontend-js-web`:

```
> Task :apps:frontend-js:frontend-js-web:cleanBuildCSS UP-TO-DATE
> Task :apps:frontend-js:frontend-js-web:cleanCopyCSS
> Task :apps:frontend-js:frontend-js-web:copyCSS NO-SOURCE
> Task :apps:frontend-js:frontend-js-web:buildCSS NO-SOURCE
```

(Those on current `master`, not your PR) — makes it look to me like all this is supposed to happen "automagically" (the `frontend-js-components-web` [build.gradle](https://github.com/liferay/liferay-portal/blob/4cee53e133d8e2744c43ff333cd8af844ae249e3/modules/apps/frontend-js/frontend-js-components-web/build.gradle) is empty, and it all works); and the `NO-SOURCE` there makes it look like if there were `.scss` files in the source tree, they would have been copied/built.

Don't know if any of this helps, but it might provide a hint of the right direction to investigate. We have a [`SassCompiler` class](https://github.com/liferay/liferay-portal/blob/4cee53e133d8e2744c43ff333cd8af844ae249e3/modules/util/sass-compiler-api/src/main/java/com/liferay/sass/compiler/SassCompiler.java), but I have no idea how it's all wired up or even if that's the one involved in the build process. Of course, I bet @jbalsas knows exactly how SCSS builds work. 🤔

---

About the larger question of how best to resolve this style conflict, I don't have any bright ideas; it all seems a big mess. Might be good to call in a couple of other opinions on this one (eg. @marcoscv-work, @bryceosterhaus: any recommendations).

**Comment by markocikos** [comment]
I forgot to mention above, to reproduce the CSS import issue:
1. Add a `Modal.scss` file in the same dir as `Modal.es.js`. It can contain any sample style, it does not matter.
1. Uncomment [import](https://github.com/wincent/liferay-portal/pull/192/commits/b8df98cf2d67b44a8f70b2c4ec7ccc5b7386b912#diff-c80118a1eb166c685e7c1f0675ffdf2cR21) 
1. Redeploy
1. Open Page Fragments, or any page using `frontend-js-web`. I am getting this error:

```
Modal.scss.js?languageId=en_US:1 Uncaught ReferenceError: module is not defined
```

**Comment by jbalsas** [comment]
Keep in mind `frontend-js-web` uses a different preset. You'll need to configure the css loader.

**Comment by wincent** [comment]
> Keep in mind `frontend-js-web` uses a different preset. You'll need to configure the css loader.

I thought so too, but I can't find any evidence of how it is applied. Look in its [`.npmbundlerrc`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/.npmbundlerrc).

**Comment by jbalsas** [comment]
> I thought so too, but I can't find any evidence of how it is applied. Look in its .npmbundlerrc.

You're right... and yes, `BuildCSSTask` should be triggered... I can take a look at the PR later to see if I can figure out what's going on...  🤔

**Comment by markocikos** [comment]
> I can take a look at the PR later to see if I can figure out what's going on...

See https://github.com/jbalsas/liferay-portal/pull/2154

**Comment by bryceosterhaus** [comment]
We could add the ability to add additional props to the `ClayModal.Body` component on the Clay side of things. Currently we don't add any additional props to the container, but if we could add both `...otherProps` to the container element and then additionally add a prop specifically for the props on the iframe element(`iframeProps`). Do you think that would help your case? This would allow you to add inline styles to the iframe element and the `ClayModal.Body` component as needed.

**Comment by jbalsas** [comment]
This should now be at https://github.com/markocikos/liferay-portal/pull/182

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
