### PR TITLE
LPS-113561 Avoid use of Liferay.provide in users-admin-web

### PR DESCRIPTION
**Pull request by julien**
PR 2 of the 6 described here: [#320 (comment)](https://github.com/wincent/liferay-portal/pull/320#issuecomment-641223200)

Details provided in the commit messages.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
> I don't think you pushed your changes.
Yes, sorry I posted that comment in the wrong PR thread, it was actually for #347 

Concerning  `liferay-search-container` in this change:

I think your analysis is good, but I don't have a good answer on what to do to avoid a potential race.

**Comment by wincent** [comment]
Ok, marking this one as on hold until the others are done.

**Comment by jbalsas** [comment]
Ok, I think this is in fact trivial, but bear with me for a second... this is what we actually have here:

```jsp
<clay:sheet-section>
    <c:if test="<%= !portletName.equals(myAccountPortletId) %>">
        <aui:script sandbox="<%= true %>">
            selectRegularRoleLink.addEventListener('click', event => {
                Liferay.Util.selectEntity({...}, event => <portlet:namespace />selectRole(...));
            }
        </aui:script>
    </c:if>
</clay:sheet-section>

[...]

<clay:sheet-section>
    <c:if test="<%= !organizations.isEmpty() && !portletName.equals(myAccountPortletId) %>">
        <aui:script sandbox="<%= true %>">
            selectOrganizationRoleLink.addEventListener('click', event => {
                Liferay.Util.selectEntity({...}, event => <portlet:namespace />selectRole(...));
            }
        </aui:script>
    </c:if>
</clay:sheet-section>

[...]

<clay:sheet-section>
    <c:if test="<%= !portletName.equals(myAccountPortletId) %>">
        <aui:script use="liferay-search-container">
            A.one('#<portlet:namespace />selectSiteRoleLink').on('click', event => {
                Liferay.Util.selectEntity({...}, event => <portlet:namespace />selectRole(...));
            }
        </aui:script>
    </c:if>

    [...]

	<c:if test="<%= !portletName.equals(myAccountPortletId) %>">
		<aui:script>
			Liferay.provide(
				window,
				'<portlet:namespace />selectRole',
				{ ... },
				['liferay-search-container']
			);
                 </aui:script>
	</c:if>
</clay:sheet-section>
```

**Comment by jbalsas** [comment]
So, if you squeeze your eyes en move back and forth unfocusing... the following pattern emerges:
- Button 'click' events are added through JS, so there's already an initial race condition when the button does nothing
- There's 2 usages of `selectRole` inside `<aui:script>` with no dependencies
- There's 1 usage of `selectRole` inside `<aui:script use="liferay-search-container">`
- There's 1 additional `<aui:script use="liferay-search-container">` with other stuff

So... I think this can all be reordered inside one single and majestic `<aui:script use="liferay-search-container">` like:

```jsp
<aui:script use="liferay-search-container">
    // Oh, the beauty of closures...
    function selectRole(roleId, name, searchContainer, groupName, groupId, iconCssClass) { ... };

    <c:if test="<%= !portletName.equals(myAccountPortletId) %>"
        selectRegularRoleLink.addEventListener('click', event => {
            Liferay.Util.selectEntity({...}, event => <portlet:namespace />selectRole(...));
        }
    </c:if>

    // You get the jist...
</aui:script>
```

**Comment by jbalsas** [comment]
So...

> Refactor in some way (I don't know if possible) such that all potential calls to the functions that depend on liferay-search-container can themselves only originate from places that are already gated by <aui:script use>.

This 👆 ?

**Comment by jbalsas** [comment]
> Tolerate the race as unlikely (meh).

After giving it a full night sleep, I think just adding `use="liferay-search-container"` to the rest of `aui:script` tags (not the one defining the `selectRole` method) should negate the race condition since the `search-container` dependency is already required from the calling sites... as you say, `meh`, but probably the best cost-benefit solution...

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Concerning the test error: 

```
 [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:app-builder-workflow:app-builder-workflow-web:packageRunTest'.
     [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
```

I'm also getting errors in the master branch [`bed295e47f8cc686c9c28f8f4e6c9a6effe87b81 `](https://github.com/liferay/liferay-portal/commit/bed295e47f8cc686c9c28f8f4e6c9a6effe87b81)

**Comment by wincent** [comment]
This is what I get on master running `yarn test` from `modules/dxp/apps/app-builder-workflow/app-builder-workflow-web`:

```
Test Suites: 3 passed, 3 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        13.927s
Ran all test suites.
```

I'm going to move this over to liferay-frontend anyway; we'll see if it can be green there: https://github.com/liferay-frontend/liferay-portal/pull/9

**Pull request closed without merging**
