### PR TITLE
LPS-112623 Update formik to v2.1.4

### PR DESCRIPTION
**Pull request by boton**
Upgrading because [we want a version of formik](https://github.com/liferay/liferay-frontend-guidelines/issues/40#issuecomment-619014725) that we can use in conjunction with React hooks.

Currently we are only using formik in one place (segments-web), and we don't believe any of the issues noted in [the v2 migration guide](https://github.com/jaredpalmer/formik/blob/master/packages/formik/MIGRATING-v2.md) will affect us.

### CODE REVIEW

**Comment by boton** [comment]
SF tested boton#179

/cc @dgarciasarai

**Comment by boton** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I updated the description because when we `ci:forward` this the message will get copied over and I think it's useful to provide context.

Screenshot 2020-04-28 -140331-o93v0dlA@2x

In general, [always try to provide a description](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md#write-useful-descriptions-and-titles).

**Comment by wincent** [comment]
Going to re-run `ci:test:sf` here because it will need to run anyway before forwarding.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
I had to push one commit on top of this to dedupe the yarn.lock, so I rebased at the same time.

**Comment by wincent** [comment]
segments-web tests are green, and @boton did manual testing, so let's try to forward this.

Screenshot 2020-04-28 -141906-kEuh60ea@2x

**Comment by wincent** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
You will need this 🍀

**Pull request closed without merging**
