### PR TITLE
LPS-115139 Make sure polyfills are loaded before used

### PR DESCRIPTION
**Pull request by julien**
As described in [LPS-115139](https://issues.liferay.com/browse/LPS-115139), the call to `Object.entries` [here](https://git.io/Jfy4v) is throwing an error on IE11.

We think it shouldn't because we have a polyfill for this function in the [frontend-compatibility-ie](https://git.io/Jfy4U) module, but it seems that the polyfill is loaded after it is used.

So in this change, we change the location of where those scripts will be loaded.

Previously: https://github.com/wincent/liferay-portal/pull/323

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
he-is-right-you-know

**Comment by julien** [comment]
@wincent, he's right I know, sorry about that - `yarn checkFormat` didn't catch any errors or change the file, but `gradlew formatSource` did.

**Comment by julien** [comment]
ci:test:sf

**Comment by wincent** [comment]
> @wincent, he's right I know, sorry about that - `yarn checkFormat` didn't catch any errors or change the file, but `gradlew formatSource` did.

Yeah, `yarn checkFormat` only looks at `.js`, `.jsp`, `.jspf`, and `.scss`.

**Comment by wincent** [comment]
So as discussed on Slack, there is some risk in this change (because it is moving a large chunk of code around on IE), but polyfills should go first, so let's do it and find out what, if anything, breaks. In any case, seeing as sign in is currently broken on IE, we can't exactly make things too much worse.

Thanks for going beyond the quickfix (refactoring away the `Object.entries` call) and taking the time to fix the underlying problem instead. It was a "footgun" which was sure to hurt us again in the future.

I'm going to fire off an optimistic `ci:forward` while we wait for CI to finish.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
["No unique failures"](https://github.com/wincent/liferay-portal/pull/325#issuecomment-641269651) so going to forward manually.

**Pull request closed without merging**
