### PR TITLE
WIP Adds a dark and a light theme for the sidebar but don't apply these themes. This is a WIP :/

### PR DESCRIPTION
**Pull request by jbalsas**
For context, only relevant commit here is [WIP Adds a dark and a light theme for the sidebar but don't apply these themes. This is a WIP :/](https://github.com/wincent/liferay-portal/pull/166/commits/88a2997a6fe5d77dd41f6e8988f42e288d946652) which belongs to [LPS-109094 - Create a light style of MultiPanelToolbar](https://issues.liferay.com/browse/LPS-109094).

PR is a WIP, and we might want to apply it only after the sidebar feature has been merged and even maybe after the sidebar component has been abstracted to a common location.

/cc @diegonvs

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Hey guys, about the use of CSS BEM pattern, we try to follow the Boostrap concession and our own guidelines about how to write CSS, in this case, the modifier class to create a dark/light component version:

https://github.com/liferay/liferay-frontend-guidelines/blob/master/css/when_and_how_to_create_a_new_css_component.md#modifier-classes

**Comment by p2kmgcl** [comment]
https://github.com/wincent/liferay-portal/pull/243

**Comment by p2kmgcl** [comment]
https://github.com/wincent/liferay-portal/pull/243

**Comment by wincent** [comment]
Superseded by https://github.com/wincent/liferay-portal/pull/243

**Pull request closed without merging**
