### PR TITLE
LPS-108648 Remove AUI from Liferay.Portal.Tabs | WIP

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

**WIP, do not forward!**

This is a followup on https://github.com/jbalsas/liferay-portal/pull/2138

As I've said in the previous PR, the biggest problem is where to place `Liferay.publish`. @jbalsas [mercilessly cut down](https://github.com/jbalsas/liferay-portal/pull/2138#issuecomment-588186874) the suggestion in the previous PR to put it in `events.js` :) 

In this PR, I placed it in `tabs.es.js`, but I'm running into problems with tests in this approach. `Liferay.publish` is undefined. IIUC, 'import' is executing code that is in the file root, and, in test's case, this happens before we can set a mock in `beforeEach`.

There is a clean solution for this: to rewrite `Liferay.publish` to a vanilla JS util. Currently, it is AUI, more precisely [vanilla YUI](https://yuilibrary.com/yui/docs/event-custom/). This is already something we want to do, https://issues.liferay.com/browse/LPS-108645. But, before I start on this path, I would like to hear your opinion. Am I missing something? Is the path correct? I am suspecting that there is a hack to workaround this, like global mock, but is it worth compared to the clean solution? 

What do you think?

### CODE REVIEW

**Comment by wincent** [comment]
> I am suspecting that there is a hack to workaround this, like global mock

I agree with your assessment that the problem is that the `import` in the tests:

```javascript
import showTab from '../../../src/main/resources/META-INF/resources/liferay/portal/tabs.es';
```

Causes [this code](https://github.com/wincent/liferay-portal/blob/03c3ae2ac5956eaf241994573f9a39dc87911033/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/portal/tabs.es.js#L46-L96) in the implementation to be eagerly evaluated.

```javascript
Liferay.publish('showTab', {
    // ...
});
```

I don't know much about YUI, but my understanding of the purpose of this `Liferay.publish` call (based on [the docs](https://yuilibrary.com/yui/docs/event-custom/#complex-event-lifecycle)) is to run the `defaultFn` whenever the `showTab` event fires, after any other handlers, as long as none of them did a `preventDefault()`. So maybe, just maybe, we could fake something equivalent.

eg.

```javascript
export function showTab(...args) {
   // blah, blah...

   try {
     Liferay.after('showTab', afterShowTab);
     Liferay.fire('showTab', details);
  } finally {
     Liferay.detach('showTab', afterShowTab);
  }
}

function afterShowTab(event) {
   // ... all the code you currently have in that `defaultFn` that you pass to `Liferay.publish`...
}
```

That's the first idea that occurs to me anyway. The second one is, like you say, globally mocking `Liferay.publish`, but that sounds complicated, and in the long term counterproductive (because I doubt we want to encourage the continued use of that API — there are only 10 call sites in liferay-portal).

**Comment by markocikos** [comment]
@wincent The problem is that, fundamentally, there needs to be some code that executes immediately. `Liferay.publish`, or any variant of code that replaces it, needs to immediately execute to define a global listener for a custom event. Your snippet above contains code definition, but not execution. It may work in a test, but not as a solution. [The current solution](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/portal.js) works because it is wrapped in a self-executing function. On a sidenote, using any other functions from YUI's API, such as `Liferay.after` or `Liferay.fire` would result in the same issue.

I see only one way around it: to replace all custom events handling with vanilla JS. I have already started working on it, in no small part through analysis how to fix this issue. As I said earlier, this is something we want to do in any case.

As for this PR, it can be on hold and sent as the first use case for the new custom events utils. Alternatively, we can do a temporary step and migrate everything in this PR except the `Liferay.publish`. It would stay where it is for now, in `portal.js`.

**Comment by wincent** [comment]
> Your snippet above contains code definition, but not execution. It may work in a test, but not as a solution.

Are you sure? It seems like it would work. Consider:

Current solution:

- (Eagerly) uses `Liferay.publish` to configure code that will be run after `showTab` is fired.

Proposed hack:

- (Lazily) uses `Liferay.after` to configure code that will be run after `showTab` is fired.

There is exactly *one* place in all of liferay-portal where we `fire` the `showTab` event — both in the existing implementation and in your new one — so I can't see why *eager* registration would be required. Doing it just before firing would be enough. Are you worried that somebody else (a client) might call `Liferay.fire('showTab')` directly and bypass the `showTab` API? That seems unlikely and not like something we would or should support.

> On a sidenote, using any other functions from YUI's API, such as `Liferay.after` or `Liferay.fire` would result in the same issue.

I don't really get this point. Your code is already using `Liferay.fire`.

> I see only one way around it: to replace all custom events handling with vanilla JS.

That's certainly desirable, but I was just offering you an interim solution that seems like it would work, given that overhauling all event handling is probably a pretty big undertaking. I don't really understand why you think it wouldn't work.

**Comment by markocikos** [comment]
> Are you worried that somebody else (a client) might call `Liferay.fire('showTab')` directly and bypass the `showTab` API? That seems unlikely and not like something we would or should support.

Yep, I considered it a deal breaker if backwards compatibility was broken, consequently I considered it a hard requirement to keep permanent listener definition. I see your point though, if it's not a problem to drop support for this odd case, then your solution is perfectly fine.

I'll resend PR with it and the complete test.

**Pull request closed without merging**
