### PR TITLE
LRQA-57210 Ignore the test that is failing

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by Adriverforlife** [comment]
https://issues.liferay.com/browse/LRQA-57231 came up on the initial failure

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Created:
https://issues.liferay.com/browse/LRQA-57204
https://issues.liferay.com/browse/LRQA-57243

Rerunning tests on the mean time.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
