### PR TITLE
LPS-108270 Separate frontend-js-web and frontend-js-aui-web

### PR DESCRIPTION
**Pull request by wincent**
"Dangerous bits" split off from https://github.com/wincent/liferay-portal/pull/140 and stuck on the end.

The "safe bits" are the first 3 commits, that I am sending separately (or at least, I would if GitHub stopped giving me 500 errors every time I try... ah, at last — https://github.com/wincent/liferay-portal/pull/141).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
This one back to you @izaera, as per [comment](https://github.com/wincent/liferay-portal/pull/140#issuecomment-588316079).

> Yup, we can't have a visible UI toggle that makes portal break in such a catastrophic way. I expected us to make it so things would still working when those are disabled. If that's not the case now, then we shouldn't commit to the UI portion of this PR.
>
> We can do a silent config file (feature flag) until this is ready for prime time.

**Comment by izaera** [comment]
Just started reviewing :)

**Pull request closed without merging**
