### PR TITLE
LPS-113561 Avoid use of Liferay.provide in dynamic-data-lists-web

### PR DESCRIPTION
**Pull request by julien**
PR 4 of the 6 described here: [#320 (comment)](https://github.com/wincent/liferay-portal/pull/320#issuecomment-641223200)

Details provided in the commit messages.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Per Slack, going to try to just outright remove all the AUI deps here.

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Moving this over to https://github.com/liferay-frontend/liferay-portal/pull/12, where I will give the CI another chance to bless this PR. I still have to re-review it though because I haven't looked at the recent changes.

**Pull request closed without merging**
