### PR TITLE
LPS-115139 Avoid using `Object.entries` which throws errors on IE

### PR DESCRIPTION
**Pull request by julien**
As described in [LPS-115139](https://issues.liferay.com/browse/LPS-115139),
the `Object.entries` function throws an error on IE11, so in this
change we use `Object.keys`.

As a result, after deploying this change there should be no errors in
IE11's console when loading the page and it should be possible to sign in.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Do you know why our core-js polyfill isn't providing `Object.entries` here? Is it running too late relative to this module initialization code? (core-js has polyfilled `Object.entries` [since forever](https://github.com/zloirock/core-js/issues/110), and `git grep Object.entries` shows us using `Object.entries` just fine in over 30 places).

**Comment by julien** [comment]
You're right it's weird, because `Object.entries` does work on IE11 with the core-js polyfill

object-entries-ie

Let me see if I can't find what's happening

**Comment by julien** [comment]
At the moment when the error occurs `Object.entries` is not available

object-entries-error-01

**Pull request closed without merging**
