### PR TITLE
LPS-110927 Update Liferay.Portlet.openWindow utility

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/wincent/liferay-portal/pull/230, with a side trip to https://github.com/markocikos/liferay-portal/pull/187.

Changes from https://github.com/wincent/liferay-portal/pull/230:
- Moved `<Iframe>` to be a top level component. This fixed the issue of unwanted unmounting and re-rendering. `shouldComponentUpdate` was not even needed, default rendering is smart enough to ignore it with no props change. Interestingly, top level functional component did not work, there was still a render after load that killed delegation.
 - `iframe` visibility can now be managed through inner state
 - Reverted unneeded header changes

Please review the code.

Thank you!

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> Target exception: java.lang.RuntimeException: Unable to rebase markocikos-234-LPS-110927-3 to master
error: Failed to merge in the changes.

dissapointment

**Comment by wincent** [comment]
I expect rebase problem is probably my own "fault" (caused by https://github.com/brianchandotcom/liferay-portal/pull/88053). I'll take of rebasing this and retrying.

**Comment by wincent** [comment]
Rebased, going to retrigger tests.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 3 minutes 51 seconds 405 ms

Ha, I ran `yarn format` in `frontend-js-aui-web`... should have run it in `frontend-js-web`... 🤦‍♂️

**Comment by wincent** [comment]
ci:test:sf

**Comment by markocikos** [comment]
@john-co I took a look at CI failures, they are all relevant. They are looking for attributes that no longer exist. We could modify code to past these tests, but it's a better and cleaner solution if we updated tests themselves.

```
Element is not present at "//iframe[contains(@class,'dialog-iframe-node')]"
```
This class was internally added by AUI modal, we no longer expect it to be present. Test can look for `dialog-iframe-popup`, a custom default class we add in util. This error is in three places.


```
Element is not present at "//iframe[contains(@id,'configurationIframeDialog')]"
```
Original util [set this ID](https://github.com/liferay/liferay-portal/blob/620887c4b57b1ae75673102707a3e6e6d1329135/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/portlet.js#L715), but I didn't migrate it to new util as it serves no purpose. We can remove this test, or it can look for `dialog-iframe-popup`.


```
Element is not present at "//div[contains(@class,'dialog-iframe-bd')]/iframe[contains(@src,'portlet_configuration')]"
```
`dialog-iframe-bd` is no longer expected. `portlet_configuration` in `src` is still a good test.

**Comment by wincent** [comment]
(Mostly) repeated the initial test plan from https://github.com/wincent/liferay-portal/pull/219.

Notifications config:

Screenshot 2020-04-28 -161356-VEW82XNr@2x

Hello world config:

Screenshot 2020-04-28 -161451-ed8BAkAC@2x

Staging:

Screenshot 2020-04-28 -161331-3Bs2iUOs@2x

Export/import:

Screenshot 2020-04-28 -161320-fUkbFgPk@2x

Loading spinners:

Screenshot 2020-04-28 -161350-r30wXxXH@2x

Screenshot 2020-04-28 -161444-pPCdyvXA@2x

Screenshot 2020-04-28 -161304-oq88R5Qn@2x

@markocikos: I think we should probably vertically center the spinner, to match what we don on master; here's a master screenshot for comparison:

Screenshot 2020-04-28 -165020-fYym2S2p@2x

I don't think we need to dive deep on those `ci:test:relevant` failures until we get to the final version of this PR, but mentioning @john-co that we might need to call you in for some help when the time comes.

**Comment by markocikos** [comment]
> @markocikos: I think we should probably vertically center the spinner, to match what we don on master; here's a master screenshot for comparison:

There is nothing in [Lexicon guidelines](https://liferay.design/lexicon/core-components/loading-indicator/) about vertical alignment. Default styles for loading indicator do not vertically align it. I am not sure if that was intentional, or just because it is difficult to achieve in all contexts. Could somebody from Lexicon team confirm this? 

I'm not sure who to ping here. Is there something like `@lexicon-team`, like we have `@echo-team`?

**Comment by wincent** [comment]
We can ping @drakonux — but even if it is not defined, it seems reasonable and desirable to maintain the existing behavior.

**Comment by wincent** [comment]
I found [this](https://liferay.design/lexicon/core-components/modals/#loading-content):

> Modals could need time to load the content in the body. This situation is solved by placing the loading indicator (medium size) to the middle of the body both horizontally and vertically.

**Comment by drakonux** [comment]
Hey guys, @laugardie worked on this case weeks ago (she is on moving house leave today). 

Anyway, she added this information to the Lexicon Site recently. [Modals: Loading Content](https://liferay.design/lexicon/core-components/modals/#loading-content)

image

**Comment by markocikos** [comment]
Pushed a commit with vertical align.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
pushed test fix to https://github.com/wincent/liferay-portal/pull/239

@markocikos, I changed the locators to target the `modal-body` class instead. The poshi macro waits for the iframe or modal to be visible, so the `dialog-iframe-popup` class didn't work since it was nested in the hidden `#document` element.

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
