### PR TITLE
LPS-112298 Update Liferay.Util.selectEntity utility

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent 

Task history:
https://github.com/wincent/liferay-portal/pull/262
https://github.com/wincent/liferay-portal/pull/263

Tiny change from the last version, I only removed the line with leftover unnecessary prop. Rebased, retested.

Please review the code, forwarding to Echo team. A reminder - there was one usage I didn't test live, related to fragment composition, so they should definitely doublecheck there.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Tested and forwarded: https://github.com/liferay-echo/liferay-portal/pull/654

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
