### PR TITLE
LPS-98032 Format JS in JSP files with Prettier

### PR DESCRIPTION
**Pull request by wincent**
Applies Prettier-powered formatting to JS inside of JSP files.

Previously tested at: https://github.com/wincent/liferay-portal/pull/61

And needs: https://github.com/brianchandotcom/liferay-portal/pull/78386

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@hhuijser: Thanks for your help in getting the source format checks in liferay-portal ready for this Prettier-powered formatting of JS in JSP. `ci:test:sf` is reporting quite a few errors still.

Looking at [the direct link to the raw console output](https://test-1-5.liferay.com/job/test-portal-source-format/2294/consoleText), I see complaints like this one about whitespace inside JSP scriptlets:

```
     [java] 				<%
     [java] 				[DecimalFormatSymbols decimalFormatSymbols = DecimalFormatSymbols.getInstance(locale);
     [java] ]				%>
     [java] 
     [java] 				decimalS...> but was:<...tio %>,
     [java] 
     [java] 				<%
     [java] 				[	DecimalFormatSymbols decimalFormatSymbols = DecimalFormatSymbols.getInstance(locale);
     [java] 	]				%>
```

and indeed if you look in [the source](https://github.com/wincent/liferay-portal/blob/90bd558694d6eefb3de9b27b4bc2eb64a89ce5d9/modules/apps/image-uploader/image-uploader-web/src/main/resources/META-INF/resources/view.jsp#L159-L161), you can see that the indent is wrong, but if you look at this PR you'll see [we didn't touch that whitespace](modules/apps/image-uploader/image-uploader-web/src/main/resources/META-INF/resources/view.jsp) so it was already wrong.

There is a lot of console output to parse through there, but in a quick skim that seems to be the most common class of reported issue.

On the JS tooling side, it considers everything well-formatted:

```
$ liferay-npm-scripts check
Prettier checked 3949 files

ESLint checked 1011 files, found 0 errors, found 0 warnings
```

(You can see it is checking way more files with Prettier than it is with ESLint, because at this stage we're using Prettier in the JS + SCSS + JSP files and ESLint only in JS files.)

**Comment by wincent** [comment]
Here's another interesting case; it doesn't like [this whitespace change](modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_public_render_parameters.jsp) inside an `<aui:script>` tag:

```diff
diff --git a/modules/apps/portlet-configuration/portlet-configuration-web/src/main/resou>
index f98cd66e4506..6f9bc68f036b 100644
--- a/modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/ME>
+++ b/modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/ME>
@@ -125,15 +125,17 @@ editPublicRenderParameterURL.setParameter("portletResource", portl>
 </div>

 <aui:script>
-
        <%
        for (PublicRenderParameterConfiguration publicRenderParameterConfiguration : pub>
        %>

-               Liferay.Util.disableToggleBoxes('<portlet:namespace /><%= PublicRenderPa>
+       Liferay.Util.disableToggleBoxes(
+               '<portlet:namespace /><%= PublicRenderParameterConfiguration.IGNORE_PREF>
+               '<portlet:namespace /><%= PublicRenderParameterConfiguration.MAPPING_PRE>
+               true
+       );

        <%
        }
        %>
-
 </aui:script>
\ No newline at end of file
```

Complaining thusly:

```
     [java] 35: ./modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_public_render_parameters.jsp expected:<...rue
     [java] 	);
     [java] 
     [java] 	<%
     [java] 	}
     [java] 	%>
     [java] [
     [java] ]</aui:script>> but was:<...rue
     [java] 	);
     [java] 
     [java] 	<%
     [java] 	}
     [java] 	%>
     [java] []</aui:script>>
```

**Comment by wincent** [comment]
This one might be tricky to resolve:

```
[java] 29: ./modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/organization/details.jsp
```

It is objecting to [these whitespace changes](modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/organization/details.jsp) ([gist in case that link doesn't work](https://gist.github.com/wincent/43c34806b210012fdb2be0566041c31e)).

It looks like we're changing [this](https://github.com/liferay/liferay-portal/blob/6de46ceb80510ccc69f49c70adc1733a28111814/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/organization/details.jsp#L156-L158) into [this](https://github.com/wincent/liferay-portal/blob/90bd558694d6eefb3de9b27b4bc2eb64a89ce5d9/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/organization/details.jsp#L153-L155), which is obviously not good, so I'll look into that.

Before:

```
						<%
						for (String curType : organizationsTypes) {
						%>
```

After:

```
					<%
						for (String curType : organizationsTypes) {
						%>
```

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Last test reported four formatting issues; now down to two, I think, with that latest commit.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Believe it or not, that last `ci:test:sf` run shows that things are actually working! Because it is using the prerelease instead of the current contents of https://github.com/liferay/liferay-npm-tools/pull/253

Going to cut a new prerelease to prove that it's green.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@wincent, didn't see your comments until now. Great work!

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Going to close this as it has served its purpose now. Will actually re-run and apply the formatting after we have cut SP1.

**Pull request closed without merging**
