### PR TITLE
LPS-113821 New Layout JSP Tags

### PR DESCRIPTION
**Pull request by jbalsas**
Fairly dense PR related to Layout JSP Tags. Kind of a follow up of https://github.com/brianchandotcom/liferay-portal/pull/88326 (which in itself was https://github.com/wincent/liferay-portal/pull/245)

This PR pushes forward the tags adding some of the feedback gathered in Clay's own [feat(@clayui/layout): create low-level layout utilities](https://github.com/liferay/clay/pull/3204).

So, without further ado... the PR:
- Creates an internal `BaseContainerTag` from which to extend further Layout components. This could be named `BaseLayoutTag`. Since it's internal, we can change it later if that makes more sense.
    - Controls the basic markup generation
    - Allows overriding `processClassName` so different tags can define which CSS classes are passed
    - Makes sure `className` is always supported and properly concatenated for all layout tags
    - Implements `containerElement` so it's possible to output something like `td class="autofit-row"` instead of always forcing a `div`
    - Adds support for `DynamicAttributes` so tags accept any HTML attribute even if not defined in the tld: `<clay:container foo="fasd" aria-rol="button" aria-title="bar">...</clay:container>`
- Makes `clay:container` more generic and creates a specific `clay:container-fluid` tag which is the one we specifically use in DXP
- Replaces all usages of `clay:container` with the new `clay:container-fluid`
- Creates `clay:content-col`, `clay:content-row` and `clay:content-section` for the `autofluid` use case
- Creates `clay:sheet`, `clay:sheet-footer`, `clay:sheet-header` and `clay:sheet-section` for the `section` case
- Replaces raw markup for layout tags in `blogs/blogs-web` to see examples of `clay:content*` tags
- Replaces raw markup for layout tags in `depot/depot-web` to see examples of `clay:sheet*` tags

@adolfopa, I think this is a fairly low risk PR, but would you mind having someone on your team take a look?

/cc @marcoscv-work, @bryceosterhaus, @eduardoallegrini

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I looked at all 333 files and didn't spot any problems, but that's not to say I didn't miss something... most of the usages here look fine. There was only one that stood out me as a bit awkward because it required the use of two attributes plus a classname (at which point it becomes no easier or less error prone than just sticking some classes on a div by hand), but this looks like it's a very rare occurrence, so that is a sign that we're on the right track with the defaults:

Screenshot 2020-05-18 -162813-njRIGIZq@2x

**Comment by jbalsas** [comment]
Hey @wincent, yeah, that's the case that motivated my question about [Behaviour of autofit-float-end and autofit-col-end](https://github.com/liferay/clay/issues/3230)

**Comment by marcoscv-work** [comment]
We shouldn't use `autofit-float-*` very frequently, I'm not sure if we use it more than twice in portal but it should be a minor issue, a quick solution could be not deprecating `autofit-col-end` since the new class use does not get the exact same behavior (item define itself float behavior)

**Comment by jbalsas** [comment]
> [...] a quick solution could be not deprecating autofit-col-end [...]

Yeah.. it's clearly not a good solution as seen in your snippet since it involves additional markup. Patrick did warn about this in his deprecation notice, but I doubt anyone properly followed through.

For reference, `git grep "autofit-col-end"` returns this:

```bash
asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry.jsp:                                                                   <div class="autofit-col autofit-col-end">
asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry_dynamic.jsp:                           <div class="autofit-col autofit-col-end inline-item-after">
asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry_manual.jsp:                            <div class="autofit-col autofit-col-end inline-item-after">
blogs/blogs-web/src/main/resources/META-INF/resources/blogs/entry_toolbar.jsp:  <div class="autofit-col autofit-col-end">
blogs/blogs-web/src/main/resources/com/liferay/blogs/web/template/dependencies/portlet_display_template_basic.ftl:                                              <div class="autofit-col autofit-col-end">
blogs/blogs-web/src/main/resources/com/liferay/blogs/web/template/dependencies/portlet_display_template_card.ftl:                                                               <div class="autofit-col autofit-col-end">
comment/comment-taglib/src/main/resources/META-INF/resources/discussion/page.jsp:                                                       <div class="autofit-col autofit-col-end">
fragment/fragment-web/src/main/resources/META-INF/resources/view.jsp:                                                                   <div class="autofit-col autofit-col-end">
fragment/fragment-web/src/main/resources/META-INF/resources/view.jsp:                                                           <div class="autofit-col autofit-col-end inline-item-after">
frontend-theme/frontend-theme-classic/src/templates/portlet.ftl:                                        <div class="autofit-col autofit-col-end">
frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portlet.ftl:                   <div class="autofit-col autofit-col-end">
layout/layout-page-template-admin-web/src/main/resources/META-INF/resources/view_layout_page_template_collections.jsp:                                                                  <div class="autofit-col autofit-col-end">
layout/layout-page-template-admin-web/src/main/resources/META-INF/resources/view_layout_page_template_collections.jsp:                                                  <div class="autofit-col autofit-col-end inline-item-after">
message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view.jsp:                                                <div class="autofit-col autofit-col-end">
message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view.jsp:                                                                <div class="autofit-col autofit-col-end">
message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view.jsp:                                                                <div class="autofit-col autofit-col-end">
message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view_message_content.jsp:                <div class="autofit-col autofit-col-end">
product-navigation/product-navigation-site-administration/src/main/resources/META-INF/resources/content/content.jsp:                                            <div class="autofit-col autofit-col-end">

**Comment by jbalsas** [comment]
Hey @john-co, this seems to be stuck forever in CI... can you check what's going on?

Thanks!

**Comment by jbalsas** [comment]
Oh, there it goes!! 

yay

**Comment by jbalsas** [comment]
>      [java] 1: Parameterize the generic type for 'java.util.Set: ./modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/servlet/taglib/BaseContainerTag.java 81 (Checkstyle:GenericTypeCheck)

slowlori

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @john-co, can you please take a look at this?

1. ProcessMetricResourceTest.testGetProcessMetricsPageWithSortString. This must be a fluke
2. test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8. I'm not sure what the issue is here... it's hard to know from the logs...

From this, I did realize the last classes we added were not under versioning since the packages were not properly exported... which also means it couldn't cause a baseline issue.

I've rebased and push-forced in any case. 

Could you please take a look and forward to Brian if safe?

Thanks!

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
The two failing tests look unrelated. @zhangyan0701, can you follow up on the next test run analysis?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Unfortunately, there's a rebase error...

Good news is **Test failures are unrelated**

- [flakey] ContentPageConverter#EditConvertedContentPageWithDecorator https://testray.liferay.com/home/-/testray/case_results/1169419232/history?tab=result&hideFilterPin=true
- [known issue] PermissionCheckerTest.testHasPermissionWithMissingResourcePermissions https://issues.liferay.com/browse/LPS-110425

cc/ @manoelcyreno

**Comment by jbalsas** [comment]
'kay... rebased and force-pushed... one last sanity check before pushing it to Brian 🙏

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
@adolfopa, last call, by the way 😉

**Comment by boton** [comment]
We are taking a look.
/cc @ambrinchaudhary

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
@ambrinchaudhary and I revised some changes superficially and all it´s ok apparently. 👍

**Comment by jbalsas** [comment]
Well... more failures than yesterday, but only one "unique" that looks like a fluke... let's get this over with maybe, @wincent ?

**Comment by wincent** [comment]
"Unique" failure seems unlikely to be related:

```
error An unexpected error occurred: "/usr/local/share/.cache/yarn/v4/npm-sver-compat-1.5.0-3cf87dfeb4d07b4a3f14827bc186b3fd0c645cd8/node_modules/sver-compat/.yarn-metadata.json: Unexpected token 
```

At least, when I reviewed it yesterday there were no changes to the Yarn set-up. Hard to see though because GitHub showing 1,167 files changed, even though I suspect the total of files with actual changes hasn't changed from yesterday (when it was 333 files).

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/88881

**Pull request closed without merging**
