### PR TITLE
LPS-111955 Update addParams usages

### PR DESCRIPTION
**Pull request by mateomustapic**
Hey @wincent 
The goal of this task is to update addParams utility usages in portal. 
This task is the continuation of work on modernising _addParams_ api which was done in LPS-101640.

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Now that I've seen how `addParams` [is actually used in liferay-portal](https://github.com/wincent/liferay-portal/pull/223/commits/e2fa1e0da14ba4e78459c49ee1fc54c8445e091a) in this PR it seems that [the previous change](https://github.com/wincent/liferay-portal/pull/224) is not correct.

For example, we routinely add string params of the form `'something=other'`.

The old implementation just appends them (ie. `http://example.com/` + `something=other` becomes `http://example.com/?something=other`).

The new implementation, because it uses `SearchParams.prototype.append(string, '')` would instead produce `http://example.com/?something%3Dother=`.

So here's what I propose we do:

1. Close both this and https://github.com/wincent/liferay-portal/pull/224
2. Stack them together in one pull so that the changes to the API go in with the changes to the usage sites in one pull (if we had done that in the first place, we would have caught this problem).
3. Expand the test coverage added in #224 to catch this regression, and fix it.
4. Send a new, combined pull.

Did you manually test this? It seems like it would be difficult to test this pull in itself because it is trying to import a function that is [not even exported from `frontend-js-web` on `master` yet](https://github.com/wincent/liferay-portal/blob/e2fa1e0da14ba4e78459c49ee1fc54c8445e091a/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/index.es.js). Did your testing involve cherry-picking this one on top of the other pull?

**Pull request closed without merging**
