### PR TITLE
LPS-94714 - Proposed changes to folder structure of Portlet URL utility

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by kresimir-coko** [comment]
@jbalsas can you take a quick peek at this too, the purpose of this is to call the PortletURL utilities without the `PortletURL` container following the pattern we introduced in the ES6 calls. So even in JSPs it's called `Liferay.Util.createPortletURL` instead of `Liferay.Util.PortletURL.createPortletURL`

**Comment by jbalsas** [comment]
Hey @kresimir-coko, I don't think this has such a big impact that we'd like to commit to it. We don't necessarily need to match APIs and file structure either. Furthermore, we want to see global usage of `Liferay.*` utils decrease rather than increase, so it does not matter as much.

Let's just keep this as is and focus on updating usages. We can always refactor if at any point this brings more value to the table.

What do you think?

**Comment by kresimir-coko** [comment]
I agree with what you said Chema, this just appeared as a possible oversight so I wanted to make sure we don't ignore it.

**Comment by wincent** [comment]
Sounds like a good plan.

**Pull request closed without merging**
