### PR TITLE
LPS-101646 Deprecate Liferay.Util.sortByAscending

### PR DESCRIPTION
**Pull request by wincent**
This is a rebase and resend of https://github.com/wincent/liferay-portal/pull/216, which got wedged in CI, and I had to add one additional commit on top anyway.

cc @julien

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
CI never started after 19 hours. So going to try again.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:relevant

**Comment by julien** [comment]
:crossed_fingers:

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
