### PR TITLE
LPS-108648 Remove AUI from Liferay.Portal.Tabs

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/wincent/liferay-portal/pull/144

Changes:
* Replaced `Liferay.publish` with the solution outlined in https://github.com/wincent/liferay-portal/pull/144#issuecomment-588899144. The only notable difference, I am using `on` instead of `after`, as there are places in the portal that subscribe with `after`, for example [here](https://github.com/liferay/liferay-portal/blob/ca27105132499eed21f10f8adcd565b5c0fc9907/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/form_builder.jspf#L286). 
* Added tests. For test purposes, I exposed `applyTabSelectionDOMChanges`, although it is strictly a private function. I guess if we ever discover a case where `showTab` is fired directly, we can offer replacing it with this function.

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
> The only notable difference, I am using `on` instead of `after`, as there are places in the portal that subscribe with `after`, for example [here](https://github.com/liferay/liferay-portal/blob/ca27105132499eed21f10f8adcd565b5c0fc9907/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/form_builder.jspf#L286).

Can you explain your reasoning a bit here? I'm assuming that YUI/AUI will call all the `on` listeners first, and then all the `after` listeners (provided nobody did `preventDefault()`, in the order that they were registered.

So that means that in the old code, the order was:

- All `on` listeners.
- The eagerly added "infra" `after` listener.
- The `after `listener registered by product team code.

And if you were to use `after` in your solution, then the order would be:

- All `on` listeners.
- The `after` listener registered by product team code.
- The lazily-added "infra" `after` listener.

And if you use `on` as you're doing here, it is:

- All `on` listeners.
- The lazily-added "infra" `on` listener.
- The `after` listener registered by product team code.

Does that sound right? If so, good catch. I'd seen those `after` listeners before but didn't realize there might be that kind of order dependency there.

**Comment by markocikos** [comment]
> Can you explain your reasoning a bit here? I'm assuming that YUI/AUI will call all the `on` listeners first, and then all the `after` listeners (provided nobody did `preventDefault()`, in the order that they were registered.
> 
> So that means that in the old code, the order was:
> 
> * All `on` listeners.
> * The eagerly added "infra" `after` listener.
> * The `after `listener registered by product team code.

See [docs](https://yuilibrary.com/yui/docs/event-custom/) for order of operation. For our purposes, the order was:
1. (1) on() subscribers are executed
1. (4) If not prevented, any configured defaultFn will execute.
1. (10) after() subscribers are executed.

So, basically, it was `on` > `publish` > `after`

> And if you were to use `after` in your solution, then the order would be:
> 
> * All `on` listeners.
> * The `after` listener registered by product team code.
> * The lazily-added "infra" `after` listener.
> And if you use `on` as you're doing here, it is:
> 
> * All `on` listeners.
> * The lazily-added "infra" `on` listener.
> * The `after` listener registered by product team code.
> 
> Does that sound right? If so, good catch. I'd seen those `after` listeners before but didn't realize there might be that kind of order dependency there.

Yes. It wouldn't be important if the product team code did something unrelated, but it relies on DOM changes made in util (ex publish).

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/85211

**Pull request closed without merging**
