### PR TITLE
LPS-102563 | Update SelectLayout component | v3

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/wincent/liferay-portal/pull/100

Changes:
- Fixed focusing in the Treeview component
  - I ended up gutting the whole logic around activation. It was implemented as a focus listener on a node list, I just couldn't make it work alongside default focus behavior and click listeners on its children. What is the case when managing activation is necessary?
  - In a related change, I changed that only nodes are focusable. Having lists as focusables is odd to me, I guess that is only activation implementation. Note that lists are nestable, resulting in multiple listeners and a ton of odd behaviors. If managing activation is necessary, it will probably needed to be implemented in some other way.
  - To have a seemless tab navigation from other elements on the page to component, I added a focusable empty div, that redirects to the first node in treeview.
  - Minor style changes to fix (now visible) focusing

Please review the code.

Thank you!

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @markocikos. Doing my morning `ant all` and will test this shortly.

> What is the case when managing activation is necessary?

The idea of the original implementation was to have the component in two modes: it's either active and entirely responsible for managing focus internally (especially with respect to keyboard navigation), or its inactive and doesn't do anything. If your implementation maintains (or improves) the existing behavior without needing the active/inactive state, then great. I'll let you know once I've tested it if it all looks good.

> In a related change, I changed that only nodes are focusable. Having lists as focusables is odd to me, I guess that is only activation implementation. 

Not quite. The accessibility aspects were based on [this accessible treeview pattern from the OpenAjax Alliance](http://oaa-accessibility.org/examplep/treeview1/), where lists/sublists are focusable. The original tried to implement as many of those "best practice" behaviors as possible. So again, once I've tested this I'll let you know how it looks.

**Comment by wincent** [comment]
I've had time to do a little testing now this and there are a few bugs or behavior differences to fix (I'll do a bit of investigation and see if I can tackle them):

- `Tab` is [supposed to navigate away](http://oaa-accessibility.org/examplep/treeview1/) from the treeview, but in this PR it jumps around the "+"/"-" buttons.
- Seems you can't select the first item in any list with `Space` on the keyboard (you can click with the mouse though).
- Hitting space causes the list to scroll a small amount in addition to selecting an item (this bug also happens in `master`); on this PR it will scroll by a large amount when on the first item of a list.
- On initial load, list is partially expanded (it is supposed to be collapsed if there are no selected items).

Not sure if anything else but that's what I saw in a first pass. If I can get it working I'll push something to the branch.

**Comment by markocikos** [comment]
> * On initial load, list is partially expanded (it is supposed to be collapsed if there are no selected items).

This is intentional. Expanded state of each node is set in backend, I specifically added support for this in https://github.com/wincent/liferay-portal/pull/104/commits/123b54dd5f6f271813a770443e5452f4d08c6399

> * `Tab` is [supposed to navigate away](http://oaa-accessibility.org/examplep/treeview1/) from the treeview, but in this PR it jumps around the "+"/"-" buttons.

Odd, tab behavior worked fine for me. I'll have to doublecheck it. You should not be able to tab into + and -, I set `tabIndex="-1"` for them.

**Comment by wincent** [comment]
> This is intentional ... I specifically added support

Yeah, I saw you added that. The original behavior was intended too, at the time, because that's how it used to behave in [the initial implementation that Victor and Pablo did](https://github.com/wincent/liferay-portal/pull/70) (if you [search for `hasToBeExpanded` in the diff](https://github.com/wincent/liferay-portal/pull/70/files) you find the logic there that aims to expand only nodes that have selected children). I'll double check with them that it's ok for us to let the server logic "win" in this case (I suspect it probably is).

**Comment by wincent** [comment]
Rebased and will continue over on https://github.com/wincent/liferay-portal/pull/106

**Pull request closed without merging**
