### PR TITLE
LPS-108987 Adjust colors to fit design

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
I just changed the LPS (I tought it was 10987). @wincent the first four commits (from 
bfb32a5 to 7df725f) are just a fix to make the module work (there were some import issues and I couldn't deploy).

There are more changes in other components, but I am unsure about which commits should we keep or not. I you want to, I can remove everything but the sidebar color changes.

**Comment by jbalsas** [comment]
Hey @p2kmgcl, just squash everything and keep only the necessary styling changes. No need to keep the history around, nor the "WIP" commits :D

**Comment by jbalsas** [comment]
FYI, @marcoscv-work was pretty sad about the BEM convention...

**Comment by wincent** [comment]
> FYI, @marcoscv-work was pretty sad about the BEM convention...

Specifically, [here](https://github.com/wincent/liferay-portal/pull/166#issuecomment-621681970):

> Hey guys, about the use of CSS BEM pattern, we try to follow the Boostrap concession and our own guidelines about how to write CSS, in this case, the modifier class to create a dark/light component version:
> 
> https://github.com/liferay/liferay-frontend-guidelines/blob/master/css/when_and_how_to_create_a_new_css_component.md#modifier-classes

**Comment by p2kmgcl** [comment]
@jbalsas @wincent oki doki: squash, no BEM

**Comment by p2kmgcl** [comment]
@jbalsas @wincent done. Just a single commit, no BEM, :rainbow:

**Comment by p2kmgcl** [comment]
@jbalsas @wincent now it works

**Comment by wincent** [comment]
Thanks @p2kmgcl. Code looks good to me. Thanks for cleaning this up. I'm going to pull this down and test it; in the meantime, let's have CI have a go at it.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:app-builder

**Comment by wincent** [comment]
ci:test:forms

**Comment by wincent** [comment]
(I am not even sure `ci:test:app-builder` and `ci:test:forms` are the right ones here, but I figure they are worth a shot... 😂)

**Comment by wincent** [comment]
After an `ant all`, dropping the db, clearing caches, I can't test app-builder on this PR right now because of this error (evidently unrelated to this PR):

Screenshot 2020-04-30 -193124-WEBL4jj4@2x

Going to rebase and re-`ant all` and see if that makes any difference. 😢

**Comment by wincent** [comment]
So, after a mere 90 minutes, two `ant all`s, a rebase, and 2 database drops, I managed to test this change:

Screenshot 2020-04-30 -200258-rhP0OAkJ@2x

Screenshot 2020-04-30 -200712-zoG43xm7@2x

I haven't compared it milimetricamente with the Chrome inspector, but at a glance, it looks great.

**Comment by jpince** [comment]
> So, after a mere 90 minutes, two `ant all`s, a rebase, and 2 database drops, I managed to test this change:
@wincent are you familiar with `ci:test:bundle`? Not sure if there was a specific reason you were trying to build it locally. `ci:test:bundle` is described in more detail in [this grow article](https://grow.liferay.com/people?p_p_id=com_liferay_wiki_web_portlet_WikiPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_wiki_web_portlet_WikiPortlet_struts_action=%2Fwiki%2Fview&_com_liferay_wiki_web_portlet_WikiPortlet_pageResourcePrimKey=596932&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_nodeName=Grow&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_title=CI+liferay-continuous-integration+GitHub+Commands#ci_test_Modifiers-General-Commands)
cc/ @john-co

**Comment by wincent** [comment]
> @wincent are you familiar with `ci:test:bundle`? Not sure if there was a specific reason you were trying to build it locally. `ci:test:bundle` is described in more detail in [this grow article](https://grow.liferay.com/people?p_p_id=com_liferay_wiki_web_portlet_WikiPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_wiki_web_portlet_WikiPortlet_struts_action=%2Fwiki%2Fview&_com_liferay_wiki_web_portlet_WikiPortlet_pageResourcePrimKey=596932&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_nodeName=Grow&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_title=CI+liferay-continuous-integration+GitHub+Commands#ci_test_Modifiers-General-Commands)

I've seen folks like @john-co use it many times. I've always assumed that it was intended for QA folks who have to do a lot of testing, and others like me should conserve CI resources. Normally when I test stuff I can just build a couple of modules, but in this case something was wonky with my local set-up so I had to rebuild everything. A full build normally takes me about 16 minutes, so even that is not too bad (and probably quicker than waiting for `ci:bundle`). I'll definitely add `ci:bundle` to my list of usable tools though.

**Comment by wincent** [comment]
@alexcandidos: Are you able to let us know whether those failures in the `ci:test:forms` and `ci:test:app-builder` suites might be related? (@esanzp tells me you are the QA of contact for forms and app builder stuff.)

I tested this manually, and `ci:relevant`/`ci:stable` are green, but I am not sure of the current status of those other suites and whether they are stable or not, and I am not super familiar with that part of the product in any case.

**Comment by jpince** [comment]
@wincent yes, please use `ci:test:bundle`! The CI resources are available to make you more efficient by focusing on the tasks only you can do. Even running tests if for devs, so they don't have to run it locally, or come back to fix the code later (because the test catches it in the PR). If CI isn't serving you well, or you feel bad for using resources, that's the feedback that we want to hear so we can unblock you.

So you're aware, `ci:test:bundle` only uses one slave (out of thousands), so this is next to nothing in terms of load.

Another possibility, if you typically test PRs you review, I think there's a jenkins property that can be set for your user that automatically saves the bundle used for the tests. You can ask John or the CII team if you're interested.

**Comment by jpince** [comment]
You're looking for @cvanut for forms. Cleyton, please see Greg's (wincent) request above.

@esanzp check the Virtual Stand Up for team info, I ask the teams to update the list whenever people move around, new hires join, etc. :) It's not the same as an org chart, but it's kept up to date.

**Comment by alexcandidos** [comment]
Hey @wincent , I am responsible for App Builder only, so I just cross-checked your results (https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1137259777) with the latest results of the `app-builder` routine executed on CI (https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1142871999). 

The analysis follows below:

**Known issue in App Builder suite**
- AccessAndSetPermissionsForCustomObject;
- MakeSureIsNotPossibleSaveEmptyFormView;
- PredefinedValuesArePersistedInFormView;
- RemoveFormViewFields;
- SetAppBuilderManagePermissionFor2RolesAndPerformCRUD.

**Only failing in your PR**
- CreateTableViewsWithFixedEntriesFilter;
- DeployAnAppChoosingBetweenTheExistingFormViews;
- DeployAppChoosingBetweenDifferentTableViews.

And looking at the history of these 3 tests, they are passing in other PR executions, so I would suggest you re-rerun.

Best Regards,
Alex.

**Comment by cvanut** [comment]
Hi @wincent, I analyzed your [PR results](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1137257658) with the latest run from [Forms Suite](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1142862551&testrayComponentId=427743017)

You can see Forms analysis [here](https://docs.google.com/spreadsheets/d/116eK810VT4jNxuvIG0uzbyfVPNrtqMQUnvbQDF6sd1U/edit?usp=sharing)

**Comment by wincent** [comment]
ci:test:forms

**Comment by wincent** [comment]
ci:test:app-builder

**Comment by wincent** [comment]
Thanks for the analysis on the prior run @alexcandidos and @cvanut. I re-ran as suggested by @alexcandidos, and things improved somewhat:

First run:

- ci:test:forms - 65 out of 85 jobs passed
- ci:test:app-builder - 8 out of 18 jobs passed

Second run:

- ci:test:forms - 75 out of 85 jobs passed
- ci:test:app-builder - 15 out of 18 jobs passed

Given the pattern here (10 more ci:test:forms tests passed and 7 more ci:test:app-builder tests) just by re-running with no changes, I am inclined to think that we have some CI stability issues.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
