### PR TITLE
LPS-115254 Closing the session timeout warning immediately causes it to reappear

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello @wincent,

I'm sending this through you since it seems you were the last reviewer of this file. Please let me know if it would be better for someone else to review though.

The issue is that the `sessionState` variable is only fetching one time before starting the interval function. Inside of the interval there is a call to `instance.warn()` if the `sessionState` is not `warned`. When the instance is warned the `sessionState` is then set to `warned`.

Since the variable is not reset however we will constantly trigger the warning and set `warningMoment` to `true`. This value is used in `_beforeHostWarned` for its interval function. Whenever `warningMoment` is `true` we call `banner.show()` which then displays the pop up window again.

By moving the declaration inside of the interval, `warningMoment` will be set appropriately and the popup window will remain closed if closed by the user.

Please let me know if you have any questions or concerns.

Thank you.

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @jonathanmccann.

I am not very familiar with this code and didn't write it (looks like @jonmak08 is your guy), but looking back, I see that the code was made this way in 26af37eb5a48671e87b0f629fca3041b8dedcdc4 in order to fix [LPS-88390](https://issues.liferay.com/browse/LPS-88390):

> ### When session expiration warning message is displayed, if the screen is navigated off of the message container is not properly destroyed
>
> #### Issue
>
> When a session expired warning message is displayed, after moving to a different page, the option menu is not clickable.
>
> #### Steps to reproduce
>
> 1. Login to Liferay
> 2. Wait until a warning message of session expired is displayed
> 3. When the message is displayed, navigate to another screen (e.g Content > Web contents)
> 4. Open the developer tools (using F12) and search for "lfr-notification-wrapper in" in the DOM/Elements tab
>
> #### Actual result
>
> The notification wrapper will still be present with width and height despite no notification showing up on the screen.
> 
> #### Expected result
>
> The notification will be completely removed from the DOM.

So I'm going to download a bundle and just confirm that your fix doesn't cause a regression on the other issue.

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Ok, I tested this and it seems to work. Also confirmed that there is no regression of LPS-88390. If this analysis turns out to be incorrect we can always fast-follow with a fix, so I am going to forward this.

**Comment by wincent** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
Thank you for taking the time to review this.

**Pull request closed without merging**
