### PR TITLE
LPS-110927 Update Liferay.Portlet.openWindow utility

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

Task history:

- wincent#219
- wincent#230
 - spinoff markocikos#187
- wincent#234
- wincent#239
- https://github.com/john-co/liferay-portal/pull/283
- https://github.com/wincent/liferay-portal/pull/248

Changes from https://github.com/wincent/liferay-portal/pull/248 are in added commit.

The changes fix the bug with styles when you navigate within iframe. To reproduce:
1. create few web contents
1. open configuration of a web content display app
1. click select
1. choose a web content (this updates configuration modal with new URL and content)

On return to configuration modal, styles are wrong, even hiding buttons in some cases. This is because iframe body CSS classes `dialog-iframe-popup` and `dialog-with-footer` are not set.

In original PR, we set those classes by adding namespaced `bodyCssClass` to URL, see [here](https://github.com/wincent/liferay-portal/commit/9969766d67b6868d619848739907837d79c4482b#diff-45c988fca3398d3143e41f2f53e309a7R279). This works fine for standard modal. It is migration of what we were doing in [AUI modal](https://github.com/brianchandotcom/liferay-portal/blob/36a742f82e360b07566bb7c975310571ad1bff2d/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js#L219). But, when we are changing URL within iframe, we don't add this parameter to URLs. Instead, we are hooking on AUI modal lifecycle and [manually](https://github.com/brianchandotcom/liferay-portal/blob/36a742f82e360b07566bb7c975310571ad1bff2d/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1096) adding those classes after iframe is loaded but before it is rendered. This is not possible with Clay-based modal. 

Solutions I gave up on:
- We can detect URL change in new iframe `onLoad` event, and insert classes in it. Unfortunately, this results in visual glitching as incorrect styles are shown before correct ones. I don't see how we can control `<ClayLoadingIndicator>` logic in this scenario.
- It would be possible to add `bodyCssClass` parameter to every modal URL, but highly unpractical. There are 143 uses of `.setWindowState(LiferayWindowState.POP_UP)`, identifying URLs that are meant to be open in modals.
- We could use the ever-present `portal-popup` class to duplicate styles from `dialog-iframe-popup` and `dialog-with-footer`. However, simple styles added to page will not affect `iframe` content. It would be possible to insert styles to iframe, but it is an ugly solution. Coupling that with duplication of code, I gave up on this approach.

The solutions I went with in this PR is to add `dialog-iframe-popup` and `dialog-with-footer` in base unstyled theme, in template meant to be open in modal. 
- With this, we don't have to worry about adding classes through URL, or inserting after load. Apart from simpler implementation, this cleans up API, as users of `openModal` will not need to set `bodyCssClass: 'dialog-with-footer'` manually, something that is currently done in 33 places.
- I am assuming that this template is only used for iframe modal content. It does appear so. It would not make sense to me to use template to generate HTML and insert it somewhere that is not iframe, as it is a full page HTML, with `<html>`, `<body>` etc. Even if we have use cases other than iframe, and styles affect them, we could tweak theme CSS.

Please review the code.

Thank you!

/cc @jbalsas @john-co

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Going to run relevant tests even though I know we're still waiting on integration of changes on Poshi side from @kenjiheigel — just want to see if anything has changed since the last run.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
SF error on:
```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/docroot/html/portal/render_portlet.jsp expected:<...= new StringBundler([]PropsValues.PORTLET_...> but was:<...= new StringBundler([
     [java] 		]PropsValues.PORTLET_...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:440)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
[stopwatch] [run.batch.test.action: 11:54.305 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:694: Java returned: 1
      [get] Getting: http://test-1-19/job/test-portal-source-format/3822//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20200506165132979.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20200506165132979.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null174406521.properties
m
```

**Comment by markocikos** [comment]
Closing, updated version in https://github.com/john-co/liferay-portal/pull/290

**Pull request closed without merging**
