### PR TITLE
LPS-101624, LPS-101625 Deprecate `Liferay.Util.isTablet` and `Liferay.Util.isPhone`

### PR DESCRIPTION
**Pull request by julien**
Originally discussed in [#206](https://github.com/wincent/liferay-portal/pull/206)

The goal of these changes is to mark `Liferay.Util.isTablet` and `Liferay.Util.isPhone`
as deprecated. We're also providing these functions as "modules" so that
they can easily be imported projects that use ES6.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Code looks good to me. Let's see whether CI wants to play.

**Comment by julien** [comment]
Thanks @wincent.

@John-Co, if you could have a look at this one too when you get a chance, it would be great.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
based on 
image

It looks like commits were force pushed sometime after `ci test relevant` was initiated and before the tests actually started on jenkins. Thus the branch could not be found. Rerunning the tests.

**Comment by john-co** [comment]
ci:forward

**Comment by yichenroy** [comment]
ci:forward

**Pull request closed without merging**
