### PR TITLE
LPS-110184 Fix Tree-view item style

### PR DESCRIPTION
**Pull request by eduardoallegrini**
In order to apply the correct style the faster change was this structural one but I'm not sure where we are using this component. Can you verify I'm not breaking anything, please?

There are a few minor improvements I would like to implement but since Lexicon is already working on the new version of this component, I prefer to keep it simple.

Thank you!

/cc @marcoscv-work

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Looks good to me. Tested in a few different places.

If CI is green (`ci:test:relevant`) doesn't even seem to want to start, let alone finish, will forward.

Master:

srtastart_-_Liferay_DXP

strst_-_Liferay_DXP

This PR:

rrst_-_Liferay_DXP

fwp_-_Liferay_DXP

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Given the directive to not use `ci:forward` yet (because `ci:test:relevant` hasn't been fine-tuned enough yet and is causing a traffic jam), forwarding: https://github.com/brianchandotcom/liferay-portal/pull/86778

**Comment by wincent** [comment]
Ah, [I see they turned it right back on again](https://github.com/brianchandotcom/liferay-portal/pull/86778).

**Comment by wincent** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @wincent, I will include updated test.properties to reduce scope of relevant testing.

**Comment by john-co** [comment]
rebased, added test.properties, and pushed to https://github.com/wincent/liferay-portal/pull/181

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
will retest when next master stable passes.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I see this still is still looking a bit stuck. Going to rebase it (even though I think that won't make any difference) and give it another try.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Rather than just trying again blindly, paging @john-co for help in determining whether those failures are legit or not.

**Comment by john-co** [comment]
**Testray Comparison**
**Common failures with upstream:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1075266682&testrayRunIdA=1075039552&statusB=3

- [Not related] - LocalizationWithWebContentUI#AddWCWithTranslation - Quarantine known issue https://issues.liferay.com/browse/LRQA-57212

**Unique failures:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1075266682&testrayRunIdA=1075039552&statusB=2
- [Not related] - PGBlogs#SaveBlogsEntryDraft - known flaky issue on setup portal instance macro https://issues.liferay.com/browse/LPS-106515
- [Related] - NavigationMenus#AddNavigationMenuEntriesAllTypes - investigate further if regression or test fix https://issues.liferay.com/browse/LRQA-57220
- [Related] - https://testray.liferay.com/home/-/testray/case_results/1071413077 - same as above https://issues.liferay.com/browse/LRQA-57220
- [fluke] - PortalSmoke#SmokeWithDeveloperProperties -  https://testray.liferay.com/home/-/testray/case_results/1075110618/history?tab=result&hideFilterPin=true
- [Related] - NavigationMenus#ViewSuccessMessageAfterAddingMenuItem - https://issues.liferay.com/browse/LRQA-57220

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Looks like the related issues are Test Fixes. I will resend and test with the test fix.

**Comment by john-co** [comment]
pushed to https://github.com/wincent/liferay-portal/pull/191

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
