### PR TITLE
LPS-115150 Adding tests for Global Menu

### PR DESCRIPTION
**Pull request by carloslancha**
Not fancy description this time, just adding some tests :)

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
image

**Comment by wincent** [comment]
Tests...

long-time

lg2m. I'll push a couple tweaks on top and try to forward...

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
