### PR TITLE
LPS-113200 prove Management Toolbar Creation Menu "More" button behavior

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/jbalsas/liferay-portal/pull/2172. We are updating remaining modals in `journal-web` and `document-library-web`.

The problem with the 'more' modal is explained in detail in https://issues.liferay.com/browse/LPS-113200. The goal in this PR is to ensure the default menu behavior, extension, happens only if modal is not implemented:
1. We are wrapping default behavior in `setTimeout(extendMenu, 0)`, ensuring that handler defined in modules executes first.
1. This is enough for `journal-web`, but in `document-library-web` we are opening `Liferay.Util.openModal` from AUI module, meaning it opens asynchronously. That is why we are adding `Liferay.creationMenuMoreModal` and synchronizing over it.

So, the order of execution is:
1. Handler in `frontend-taglib-clay`. We do nothing, delay its execution.
1. Handler in `document-library-web`. We set `Liferay.creationMenuMoreModal`
1. Delayed execution in `frontend-taglib-clay`. If `Liferay.creationMenuMoreModal` was set, we prevent default behavior.
1. Modal opens.

---
Test in document library:
1. Documents and Media > Doyument Types tab > Create 10 document types
1. Documents and Media tab > (+) > More
1. Close modal.
1. Documents and Media tab > (+) > More
1. Select a type. This opens a new input page.
---
Test in journal:
1. Web Content > Structures > Create 7 structures
1. Web Content tab > (+) > More
1. Close modal.
1. Web Content tab > (+) > More
1. Select a structure. This opens a new input page.
---
Test of default behavior:
1. Site Builder > Widget Templates > (+) > More 

Please review the code.

Thank you!

/cc @jbalsas @carloslancha

### CODE REVIEW

**Comment by jbalsas** [comment]
I'll take this from @wincent tomorrow! Covering for him for a little until some other affairs are resolved!

**Comment by jbalsas** [comment]
Looks like our wires just crossed, was about to pick this up myself!

**Comment by wincent** [comment]
Going to move this over to https://github.com/jbalsas/liferay-portal/pull/2190 instead because I am unlikely to be able to look at this soon enough to give you useful or meaningful feedback. I would have looked at this tonight before knocking off work but I'm afraid I ran out of time.

**Comment by wincent** [comment]
Mid-air collision, as they say.

**Pull request closed without merging**
