### PR TITLE
LPS-112494 Add t=Date.now parameter to the url

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @wincent ,

Can you review this pull request?

In [LPS-112494](https://issues.liferay.com/browse/LPS-112494) you can see the steps to reproduce this behavior.

The root cause of the issue is that we are building the logo URL based only on the file's title. So if we upload the same file twice, although the second time we are cropping the image (so we are creating a new logo), it won't be updated.

Thanks.

Regards.

/cc @rolandpakai

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Thanks @antonio-ortega. Sorry for the delay. I'm going to test this out now.

**Comment by wincent** [comment]
Tested this and it works fine.

Given that this timestamp-based approach is what we're also using in the [ adjacent `logo_editor.js` module](https://github.com/liferay/liferay-portal/blob/71ce5a795d44e17829fc648d7af8fa431349ae1d/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/logo_editor.js#L83-L86), seems reasonable.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
