### PR TITLE
LPS-114143 Update modal usages in document library

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/wincent/liferay-portal/pull/295

Changes:
- We are using `Set` in checking of previously selected items.
- We are using `useRef` for storing event handlers array.
- On event handler cleanups, we are clearing the array holding them as well.
- In 'access from desktop' modal, we are now focusing input after modal opens. For this, I needed to extend API with `onOpen`. As a bonus, we are cleaning up hidden dom structure that is rendered and transferred to modal. I spent way too much time today trying to figure out why `focus()` is not working, and it was because we had two elements with the same id in DOM.

The [unique failure](https://github.com/wincent/liferay-portal/pull/295#issuecomment-634023638) happened because that test expects id with a specific suffix on an iframe. AUI modal sets this [here](https://github.com/liferay/liferay-portal/blob/9a6f0dbd631d5248109a9eea7c4d769d51eb449f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js#L187). So far we have not encountered a case in the code where this id would be relevant. I only see it [used](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js) in internal mechanisms of modal registration and events handling, which is irrelevant for new modals. We could add setting of this id, but I recommend we rather modify or remove this CI test.

For me, `Add Folder` button works normally. Please retest it on the latest code.

@liferay-echo: There is a modal in `UIItemsBuilder`, `addPermissionsToolbarItem`, that we are modifying in this PR. Where is it in UI?

@liferay-echo: We are changing the appearance of 'select folder' modals in this PR, to be full screen. See [screenshots](https://github.com/wincent/liferay-portal/pull/295#issuecomment-634049908). This follows [Lexicon guidelines for iframe modals](https://liferay.design/lexicon/core-components/modals/#iframe-in-the-body). Please review the new appearance, maybe it needs to be tweaked or reverted.

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
> I spent way too much time today trying to figure out why `focus()` is not working, and it was because we had two elements with the same id in DOM.

😱

> We could add setting of this id, but I recommend we rather modify or remove this CI test.

I asked in the [#t-echo Slack channel](https://liferay.slack.com/archives/CL9RTSZ52/p1590596949263800) for a QA lead, but @john-co may also be able to help us identify the right person to consult with about modifying or removing this.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> > We could add setting of this id, but I recommend we rather modify or remove this CI test.
> 
> I asked in the [#t-echo Slack channel](https://liferay.slack.com/archives/CL9RTSZ52/p1590596949263800) for a QA lead, but @john-co may also be able to help us identify the right person to consult with about modifying or removing this.

@manoelcyreno: We mentioned you in Slack but I'm doing it here too because everybody loves notifications, am-i-right? 😁 Can you point us to the right person, or even be the right person? 😂

**Comment by john-co** [comment]
@manoelcyreno is covering David for Echo team QA needs while he is on leave.

**Comment by manoelcyreno** [comment]
ci:test:documents

**Comment by wincent** [comment]
Apparently:

> documents and media -> Lima team -> @austinchiang

Can you please read the question about CI above, Austin?

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/wincent/liferay-portal/pull/304

**Comment by wincent** [comment]
Thanks @austinchiang. I forwarded on to @jbalsas at https://github.com/jbalsas/liferay-portal/pull/2178 because he's more likely to get to it before I do today. Will close this one to avoid duplicates.

**Pull request closed without merging**
