### PR TITLE
LPS-114177 Enhance error detection when resolving JS modules

### PR DESCRIPTION
**Pull request by izaera**
This PR uses a newer version of the AMD loader which has enhanced the protocol between the server and the client to be able to send warnings and errors. This way, we can make the resolution fail in the client when something is wrong in the server (a missing module or dependency, f.e.) and/or notify the user about warning (non-error conditions that may lead to a future error).

The protocol is quite simple: the server sends an errors and a warnings array in the resolution reply and the loader shows messages in the JS console with the given log level (remember that the user can change the log level in control panel). Also, if an error is sent, the loader throws an exception to fail the resolution.

I have tested that the portal works correctly after this change and have also modified a JAR file manually to remove a dependency from a package.json file and it works.

### CODE REVIEW

**Comment by wincent** [comment]
Test plan looks good to me. I reviewed the JS side of this. Going to forward.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
I don't know how to read [those failure messages](https://github.com/wincent/liferay-portal/pull/292#issuecomment-633529646):

```
java.lang.AssertionError: [INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[WARNING] No archetype found in remote catalog. Defaulting to internal catalog
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
[INFO] Downloading: http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.project.templates.workspace/1.0.87/com.liferay.project.templates.workspace-1.0.87.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.920 s
[INFO] Finished at: 2020-05-25T04:17:18-07:00
[INFO] Final Memory: 19M/484M
[INFO] ----------------------------------------------------------------------...
```

etc

@izaera: Do they make any sense to you? If not, next option on my list is just to do a dumb retry.

**Comment by izaera** [comment]
@wincent I think those errors are connection failures to a maven repo when running some tests. Archetypes are maven's name for generators and it looks like maven is looking for some of them and can't find them :shrug: .

I would go with the retry...

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
