### PR TITLE
LPS-103903 Removes unnecessary Require Capabilities to speed up wiring and re-deploying processes

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by wincent** [comment]
I see [`apps/flags/flags-taglib/bnd.bnd`](https://github.com/liferay/liferay-portal/blob/962a82155b6b6a1fa4fb69f5ce246e5b02518af3/modules/apps/flags/flags-taglib/bnd.bnd#L18) also depends on the liferay.js capability. Shouldn't we remove that too, for consistency? (not really concerned about speed)

**Comment by jbalsas** [comment]
https://github.com/wincent/liferay-portal/pull/91/files#diff-15b4b751b773a9df8682463f13e132f7 ?

**Comment by wincent** [comment]
@jbalsas Reading fail.

**Comment by wincent** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/80265

**Pull request closed without merging**
