### PR TITLE
LPS-78524 Make Properties tabs in Server Admin consistent with Lexicon design

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-78524

@wincent I rebased and tested it quickly and everything seems to work. Please let me know if there are any problems

@drewbrokke @pei-jung @jonmak08 @dejuknow

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Thanks @alee8888. Looks good. I forwarded it upstream here: https://github.com/brianchandotcom/liferay-portal/pull/82044

**Pull request closed without merging**
