### PR TITLE
LPS-111943 Historical data error handling

### PR DESCRIPTION
**Pull request by dgarciasarai**
Thanks @wincent for your help and your reviews :)

Previous PRs:
* https://github.com/wincent/liferay-portal/pull/220
* https://github.com/wincent/liferay-portal/pull/222

Additional notes:

* https://github.com/wincent/liferay-portal/pull/225/commits/3d5cf57df1d9f53f97202c3179835ae077a657fb follow up commit from https://github.com/brianchandotcom/liferay-portal/pull/87816.
* https://github.com/wincent/liferay-portal/pull/225/commits/71813451a9b9de8a8ba54e6be6046ce5561f61e7 impedibug.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
🍀

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
🍀

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
