### PR TITLE
LPS-110927 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-110927

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @markocikos, it looks like the `//div[contains(@class,'modal-body')]/iframe/../div[contains(@class,'overlaymask-hidden')]` is missing from these iframes. The element was being targeted to wait for the iframe to be loaded first before having the test scope to the iframe. https://github.com/brianchandotcom/liferay-portal/pull/69752/commits/1410c41f4885ffc28480b33054c10d9ca9be25d6

It's fine if this is intentional but, is there an alternative element that we could target to let us know when the iframe is loaded?

This is also a bit tricky since not all iframes are updated such as the Add Page modal. It still has the old iframe structure.
Selection_188

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
I think this will affect a lot of other tests outside of relevant. Testing to see how stable tests will be if we remove the wait for overlaymask in https://github.com/john-co/liferay-portal/pull/282

**Comment by markocikos** [comment]
> Hi @markocikos, it looks like the `//div[contains(@class,'modal-body')]/iframe/../div[contains(@class,'overlaymask-hidden')]` is missing from these iframes. The element was being targeted to wait for the iframe to be loaded first before having the test scope to the iframe. [brianchandotcom@1410c41](https://github.com/brianchandotcom/liferay-portal/commit/1410c41f4885ffc28480b33054c10d9ca9be25d6)
> 
> It's fine if this is intentional but, is there an alternative element that we could target to let us know when the iframe is loaded? Or maybe there isn't a need to wait for it to load...I'll try modifying those specific tests to not wait for loading on the meantime.

@john-co `overlaymask-hidden` class is no longer correct, that's from AUI spinner. We are using [`<ClayLoadingIndicator>`](https://github.com/liferay/clay/blob/master/packages/clay-loading-indicator/src/index.tsx), its signature class is `loading-animation`.

When modal renders:
- it contains `iframe`, hidden with `hide` class. `iframe` starts loading.
- it contains visible loading indicator

When `iframe` loads:
- we show `iframe`, by removing `hide class`
- loading indicator is removed from dom

So, if you need to check state after `iframe` is loaded, you can use:
- `iframe` must not have `hide` class
- `iframe` must contain loaded content, for example `<body>`
- an element with `loading-animation` class must not exist

**Comment by jbalsas** [comment]
At the risk of adding an unnecessary API mostly for tooling... one additional option would be to fire some type of global event on iframe load like `Liferay.fire('iframeLoad', {src: iframeSrc})`. If we had that, other than developers being able to "maybe" use it, we could better code our iframe loads like:

```javascript
let iframeLoaded = {};

Liferay.on('iframeLoad', event => {iframeLoaded[event.src] = true;});
```

```poshi
> js: iframeLoaded[foo.html] = false;
> click a[href="foo.html"]
> waitFor iframeLoaded[foo.html] = true;
```

Just a thought...

**Comment by markocikos** [comment]
>  The element was being targeted to wait for the iframe to be loaded first...

I am concluding from this that we currently do have a way of determining that `iframe` was loaded. It [looks](https://github.com/brianchandotcom/liferay-portal/commit/1410c41f4885ffc28480b33054c10d9ca9be25d6) like we are using selenium's `waitForElementPresent`, but I have no experience with it. If it is awkward or unreliable, we could add a global event like in https://github.com/wincent/liferay-portal/pull/239#issuecomment-621064509. Otherwise, I don't think there is a need for it, until developers need it.

**Comment by jbalsas** [comment]
> Otherwise, I don't think there is a need for it, until developers need it.

This would probably make tests more robust and stable, and would avoid us hardcoding yet another implementation-dependent locator that is harder to keep than an explicit JS API. It could also help in migrating all locators together because it should be also easy to add to the legacy API so both "quack" the same way ;)

**Comment by markocikos** [comment]
See https://github.com/john-co/liferay-portal/pull/283

**Comment by markocikos** [comment]
ci:close

**Pull request closed without merging**
