### PR TITLE
LPS-112983 Deprecate `liferay-browser-selectors` (draft)

### PR DESCRIPTION
**Pull request by julien**
After analysing all the classes added to `document.documentElement` by
`Liferay.BrowserSelectors`, the ones that we want to keep on supporting
are `mobile` and `touch`.

The three usages are here:

https://github.com/liferay/liferay-portal/blob/8abc9337c7f4acd55e8ef803632f26090cafe3be/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_uploader.scss#L181-L185

https://github.com/liferay/liferay-portal/blob/8abc9337c7f4acd55e8ef803632f26090cafe3be/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/taglib/_input_move_boxes.scss#L91-L93

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/_extras.scss#L277-L282

Which are documented in the Jira ticket (with screenshots as
well as where to see them).

Since we have more than one usage, it seems that adding a new vanilla JS
`browser_selectors` module is a good option to avoid code duplication in
the three different call sites.

For the moment this new implementation only adds `mobile` and `touch` classes.

With this change, instead of invoking the `run` method of
https://github.com/liferay/liferay-portal/blob/bb9c145059ef343d2d1137062b1bcf2adb183a13/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/browser_selectors.js
we're calling the `run` function exported by the `browser_selectors.js`
file in `frontend-js-web`.

A change has also been made to
https://github.com/liferay/liferay-portal/blob/bb9c145059ef343d2d1137062b1bcf2adb183a13/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/modules.js
because some "conditionally loaded" modules, depend on the
`Liferay.BrowserSelectors.run` function to be invoked, which sets
some extra properties on AUI's `UA` module:

This is the case for:

The `liferay-input-move-boxes-touch` AUI module
that depends on `UA.touchMobile` property to be set:
https://github.com/liferay/liferay-portal/blob/bb9c145059ef343d2d1137062b1bcf2adb183a13/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/modules.js#L278

The `liferay-navigation-interaction-touch` AUI module which depends on
the `UA.touch` property to be set:
https://github.com/liferay/liferay-portal/blob/bb9c145059ef343d2d1137062b1bcf2adb183a13/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/modules.js#L394

Before this change those properties where set here
https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/browser_selectors.js#L160-L161
but now that this function is not invoked we needed a way to do that
differently.

I'm tagging this PR as a draft because I think that even though we've
discussed this a few times, we probably want to talk about some details:

For example:
Should the original AUI `liferay-browser-selectors` be marked as deprecated
and is a vanilla js replacement a good idea or would it be better to use another name for our new
implementation in `frontend-js-web`.
A "temporary" `/* eslint-disable-next-line */` comment has been added in
the original AUI `liferay-browser-selectors` module to avoid lint
errors, but of ideally it should be removed if we decide to go with our
vanilla JS replacement (in which case I assume the contents of the AUI
module would be removed)

### CODE REVIEW

**Comment by julien** [comment]
Here are some screenshots of the usages, before and after this change:

**Content and Data > Documents and Media > Multiple Files Upload**

In master:

dm-multiple-file-upload-mobile-master

With this change:

dm-multiple-file-upload-mobile-after


**Documents and Media widget configuration**

In master:

dm-configuration-mobile-master

With this change:

dm-configuration-mobile-after

**Dynamic Data List Display Widget**

In master:

ddl-widget-mobile-master

With this change:

ddl-widget-mobile-after

**Comment by jbalsas** [comment]
> I'm tagging this PR as a draft because I think that even though we've
discussed this a few times, we probably want to talk about some details:

Doesn't make sense to do this in JS, IMO. Let's move this to Java.

We already have support for this through the `bodyCssClass`, which can is already heavily extended dynamically through different `*TemplateContextContributor` classes.

Key parts:
- [TemplateContextHelper injects `bodyCssClass` as a context object for templates](https://github.com/liferay/liferay-portal/blob/9839677effcea2087d194c0ca29d591d5f1d8533/portal-impl/src/com/liferay/portal/template/TemplateContextHelper.java#L305).
- [ThemeUtil tracks all `ContextContributor` of `TYPE_THEME`](https://github.com/liferay/liferay-portal/blob/9839677effcea2087d194c0ca29d591d5f1d8533/util-taglib/src/com/liferay/taglib/util/ThemeUtil.java#L235-L238) and [invokes their prepare method](https://github.com/liferay/liferay-portal/blob/9839677effcea2087d194c0ca29d591d5f1d8533/util-taglib/src/com/liferay/taglib/util/ThemeUtil.java#L193-L197).
- Any [implementation of TemplateContextContributor.TYPE_THEME](https://github.com/liferay/liferay-portal/search?q=TemplateContextContributor.TYPE_THEME&unscoped_q=TemplateContextContributor.TYPE_THEME) can [read and write context objects such as `bodyCssClass`](https://github.com/liferay/liferay-portal/blob/2624465a50c2ad5e8b32822bb70a74b253642a63/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/theme/contributor/LayoutEditModeTemplateContextContributor.java#L51-L55)

We can simply abuse this one, or if we want to keep existing behaviour to the letter, adjust to add a `rootCssClass` to set on the `html` tag.

**Comment by jbalsas** [comment]
See https://github.com/wincent/liferay-portal/pull/294

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
