### PR TITLE
LPS-111348 Archive Marketplace Themes

### PR DESCRIPTION
**Pull request by jbalsas**
The **goal** of this PR is to archive what we call "Marketplace Themes". We started releasing these themes to the marketplace as a way to showcase the product capabilities:
- [Fjord](https://web.liferay.com/marketplace/-/mp/application/78803431)
- [Porygon](https://web.liferay.com/marketplace/-/mp/application/81920471)
- [Westeros Bank](https://web.liferay.com/marketplace/-/mp/application/78803695)

As of `7.3`, we've agreed to let the Experience Management teams decide how to better share these capabilities, so we're discontinuing these specific apps. 

I think the right initial approach is to move these apps to the `archived` folder... although we could also opt to simply delete the code...

**Steps to validate:**
- Code for the themes actually live within `modules/apps/archived`
- Build (`ant all`) runs properly and finishes successfully. The archived modules shouldn't appear in the logs
- When starting the server:
    - There are no "registered" messages in the log (`1 theme for fjord-theme is available for use
`)
    - The theme modules do not appear as active modules (`telnet localhost 11311 > lb theme`)
    - Navigating to `Control Panel > Sites > Sites >` the themes don't show as valid site templates (see screenshot)

Screen Shot 2020-04-02 at 11 48 45

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Looks like going to have to update the source matter if this is to pass:

https://github.com/liferay/liferay-portal/blob/a98356e81c2b97c152ee28ab23fcbac8d55bb36d/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JSONPackageJSONCheck.java#L75-L84

**Comment by jbalsas** [comment]
I'm adding an exclusion. Stay tuned

**Comment by wincent** [comment]
An exclusion sounds like the right approach only if we're going to:

> opt to simply delete the code

Otherwise, shouldn't we be updating the source formatter to know that themes live in two places in the repo?

**Comment by jbalsas** [comment]
I think "sourceformatting" code in `archived` completely defeats the purpose of moving the apps there. The idea of archiving something is that you're not going to be updating these anymore, and serves as a last snapshot for those still needing to somehow try to install directly from a published jar.

I lost that battle already, but it befuddles me that we still spent time and effort formatting code we don't test or release 🤷‍♂

**Comment by jbalsas** [comment]
I pushed the changes... but I see the appeal on simply removing the code... I can send that if you think that's a better approach. 

What do you think?

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by wincent** [comment]
OK, makes sense. The only thing is, we have two imperatives:

- Format All. The. Things. (ie. including `archived`, even if that doesn't make much sense), because we love consistency.
- Don't add suppressions (really the same as the previous point), again because we love consistency.

So I can see Brian not liking us adding the suppression... 🤔

> I see the appeal on simply removing the code

Given the previous, it does have an appeal, doesn't it? It seems like it lowers our maintenance burden (more than archiving does). If this turns out to be a mistake, it is easily reversible, too. So I guess I would vote for removing it if you think that's not too aggressive.

**Comment by jbalsas** [comment]
We can always get it back... let me push-force it, then...

**Comment by wincent** [comment]
ci:stop

**Comment by jbalsas** [comment]
Ok, @wincent, let's start again... I've removed everything related to the themes... and quarantined the unfortunate tests that were still using some of them (even though I repeatedly asked everyone not to use them).

@john-co... I found 3 out of 4 tests were already quarantined:
- [ConfigureDisplayPageTheme](https://github.com/liferay/liferay-portal/blob/0a6206f1ac99869c31533a697ff502d9a8a5810e/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPagesWithWebContent.testcase#L201-L203)
- [AddSiteTemplateChangeCurrentTheme](https://github.com/liferay/liferay-portal/blob/0fd6692414a3fc0189d4cd4e33c102bdb6091818/portal-web/test/functional/com/liferay/portalweb/tests/enduser/sitetemplates/cpsitetemplates/CPSitetemplates.testcase#L100-L102)
- [ExportImportThemeSettings](https://github.com/liferay/liferay-portal/blob/0fd6692414a3fc0189d4cd4e33c102bdb6091818/portal-web/test/functional/com/liferay/portalweb/tests/enduser/sitetemplates/cpsitetemplates/CPSitetemplates.testcase#L100-L102)

I went ahead and quarantined also the fourth:
- [PublishSiteCreatedBasedOnASiteTemplate](https://github.com/wincent/liferay-portal/pull/195/commits/2c1d742d6f96715431b783fce6779ad204da3919#diff-c5ab7ae639f34d2081554b8f5fcba281R340)

Please, whenever you can... make sure we don't use real apps as test artifacts. Specially if the teams writing the tests are not the owners of such applications. This happens all the times, and it locks down tests, features and apps seemingly unrelated in a pattern that's nearly impossible to unfold.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> and quarantined the unfortunate tests that were still using some of them

Looking on the bright side, you found some technical debt that we didn't know about and made a down-payment on it.

**Comment by jbalsas** [comment]
> Looking on the bright side, you found some technical debt that we didn't know about and made a down-payment on it.

Sad thing is... I knew about it... and couldn't do anything to avoid it 😭

**Comment by jbalsas** [comment]
I was looking for a "lucky" gif... and then this!!

hildenberg

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Just testing, @wincent... based on 

>      [exec] Execution failed for task ':apps:archived:frontend-theme-fjord:packageRunBuild'.

My guess is this run was the previous one that didn't actually stop... but as for why it actually ran less tests... 🤷‍♂

**Comment by wincent** [comment]
> My guess is this run was the previous one that didn't actually stop... but as for why it actually ran less tests... 🤷‍♂

Let's hope so. It may be that it ran fewer tests because as stuff passes from `brianchandotcom` to `liferay` (which can happen even when Brian isn't merging, because I believe the `stable` runs are still happening before stuff goes to `liferay`, and they might be lagging), the merge base moves forward, changing the number of things that run (especially with all the stuff we're quarantining lately).`</speculation>`

**Comment by jpince** [comment]
@jbalsas you only need to run `ci:test:relevant`, and it will run both stable and relevant (you can ask John to explain the difference). When Greg commented `ci:stop` earlier, it stopped stable, but relevant kept going since it was an entirely separate test command.

I can't confirm or deny Greg's speculation, but I am glad you guys were able to get commits through.

as a side note, you guys are having way too much fun here.

**Comment by jbalsas** [comment]
> as a side note, you guys are having way too much fun here.

You haven't seen anything... 😂

**Comment by jbalsas** [comment]
Also, @jpince 

> you only need to run ci:test:relevant, and it will run both stable and relevant

I was trying to save resources by only running the next suite if the previous one passed... although I clearly didn't do it for the first pass.

That being said, it looks like this happened:

~1. Exec `ci:test:sf`~
2. Exec `ci:test:stable`
3. Exec `ci:test:relevant`
~4. Results for `ci:test:sf`~
~5. Exec `ci:test:sf`~
~6. Results for `ci:test:sf`~
7. Run `ci:stop`
8. `ci:test:stable` is aborted

So... based on this, a second `ci:stop` would've aborted `ci:test:relevant`? It's a weird API if that's indeed stacking commands and then aborting them in order of creation, since there's no way to target specific commands.

Something like `ci:test:relevant:stop` and `ci:test:stable:stop` would make more sense... whereas I'd expect `ci:stop` to stop all testing associated with this PR on the spot...

**Comment by wincent** [comment]
Or maybe `sudo ci:stop`... 😂

**Comment by jpince** [comment]
@jbalsas you're welcome to make the suggestion in #ci. I ask a lot from them already, so I try to encourage other people to submit requests when they have ideas :grinning:. It is further complicated in that _pending_ requests cannot be cancelled either - `ci:stop` only stops test builds that have already started (i.e. CI posts "Build started.")

**Comment by john-co** [comment]
fyi, @wincent @jbalsas , request for ci:stop and specific ci:stop:[suite] has been completed in https://issues.liferay.com/browse/LRCI-1251

**Comment by wincent** [comment]
@john-co: That is an awesome tweak. `ci:stop` now feels like `sudo ci:stop`.

**Pull request closed without merging**
