### PR TITLE
LPS-110752 Create new modal utility | v5

### PR DESCRIPTION
**Pull request by markocikos**
Hey @wincent ,

This is a followup on https://github.com/dgarciasarai/liferay-portal/pull/189, implementing @dgarciasarai requests.

Changes are in separate commits:
- We are showing modal in full screen.
- Fixed grey background, by setting the missing iframe body CSS class. Setting CSS class through params, relaying on portal renderer to indert them, is a copy of what we are [currently doing](https://github.com/liferay/liferay-portal/blob/54b2b925740c9c709838f07ed91bdca46ed6593c/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js#L219).

I am not sure how to implement the loading indicator, or even if it is possible without modifying `ClayModal`. We would need to listen to when the iframe document is loaded. How to even reference iframe within `ClayModal`?

If we can't think of an easy way to do it, and if it's ok with @dgarciasarai, we can split the loading indicator to a separate task.

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
These changes look ok to me, although it kind of sucks that we have to carry forward the cruft of the body classes into the indefinite future.

> If we can't think of an easy way to do it, and if it's ok with @dgarciasarai, we can split the loading indicator to a separate task.

Sounds ok to me. Let's see what @dgarciasarai says. In the meantime I'll start running the tests on this one so that we can forward it if that's ok with her.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Just leaving the breadcrumb trail here in case we need to go back and find where/how this was reviewed in the past:

- https://github.com/wincent/liferay-portal/pull/179
- https://github.com/wincent/liferay-portal/pull/184
- https://github.com/wincent/liferay-portal/pull/185
- https://github.com/wincent/liferay-portal/pull/186
- https://github.com/dgarciasarai/liferay-portal/pull/189

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Hey @markocikos, thanks for implementing my requests :)
I tested it and this looks good to me, too. Although, we have to think about how to do the loading indicator. I think it will be a good idea to do it in the `ClayModal` component. Please, don't forget it :)

Let's wait for the CI so that we can forward it.

Thanks both @markocikos @wincent 

/cc @jbalsas

**Comment by markocikos** [comment]
> Although, we have to think about how to do the loading indicator. I think it will be a good idea to do it in the `ClayModal` component. Please, don't forget it :)

I added a task for this, https://issues.liferay.com/browse/LPS-111118

**Comment by dgarciasarai** [comment]
Great @markocikos! Thanks! :)

**Comment by dgarciasarai** [comment]
See https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1080307748
Failing tests: 
* LocalFile.KaleoformsUsecase#CompleteProcessWithUploadedDefinition
* LocalFile.WidgetPageTemplates#AddSitePageTemplate

Also, `frontent-js-web` tests seem to be failing too.

I just notify the Headless team with the other 3 failing:
* OrganizationResourceTest.testGraphQLDeleteOrganization
* OrganizationResourceTest.testGraphQLGetOrganization
* SegmentResourceTest.testGraphQLGetSiteSegmentsPage

**Comment by dgarciasarai** [comment]
@markocikos can you take a look at the `frontend-js-web` error?

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
> @markocikos can you take a look at the `frontend-js-web` error?

It was an error on our side, test needed to be updated. I added a commit and force-pushed to this branch.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
🍀

**Comment by jbalsas** [comment]
Snapshot Testing 1 - Frontend Infra 0

😂

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, @manoelcyreno, this is another one of those stuck in the never-forwarding realm... can any of you help us out? 😢 

Thanks!

**Comment by dgarciasarai** [comment]
Maybe we have to rebase it...

**Comment by jbalsas** [comment]
> Maybe we have to rebase it...

As far as I can tell, PRs run after rebasing on `liferay:master`, you need to run `ci:test:norebase` if you want to avoid it, so tests should be at least running properly if they got fixed upstream.

I'd say let's wait for @john-co and @manoelcyreno to take a look before throwing any more time here...

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @manoelcyreno, yet another PR we can't push through... should we simply send it to Brian and ask him to ignore the failures?

**Comment by manoelcyreno** [comment]
ci:stop

**Comment by manoelcyreno** [comment]
yes, please.

**Comment by jbalsas** [comment]
PR is now at https://github.com/brianchandotcom/liferay-portal/pull/87108

**Comment by jbalsas** [comment]
And autoclosed 

> Closing pull request because all liferay-portal pullrequests sent to Brian Chan must be sent by using ci:forward on a pull request that was sent to someone else.

@manoelcyreno... you tell me... 🤷‍♂

**Comment by jbalsas** [comment]
I reopened it...

**Comment by jbalsas** [comment]
ci:close

**Comment by manoelcyreno** [comment]
I reopened it...

yep, the bot will close automatically... so you need to reopen :P

**Comment by manoelcyreno** [comment]
@john-co , create the JIRA LRQA for the QAs of each team to investigate these issues, please.

**Comment by john-co** [comment]
This caused a js-unit failure at head:
https://issues.liferay.com/browse/LPS-111374

**Comment by john-co** [comment]
created https://issues.liferay.com/browse/LRCI-1181 to hopefully help prevent js-unit failures from getting lost in the pr tester results github comment.

**Pull request closed without merging**
