### PR TITLE
LPS-113578 Deprecate `module.js`

### PR DESCRIPTION
**Pull request by julien**
This file contains the configuration for AUI/YUI modules.

There are no usages of this file except that it's referenced in [AUITopHeadResources.java](https://github.com/liferay/liferay-portal/blob/9617f95b39dbb47f032785f08b71932038e1bb9e/modules/apps/frontend-js/frontend-js-aui-web/src/main/java/com/liferay/frontend/js/aui/web/internal/servlet/AUITopHeadResources.java#L84).

We can deprecate this file because, as we work through [LPS-98564](https://issues.liferay.com/browse/LPS-98564) ("Remove AUI / YUI from Liferay Portal"), eventually all the AUI modules will be deprecated or migrated.

More information about YUI's configuration can be found [here](https://yuilibrary.com/yui/docs/api/classes/config.html).

Used the following commands to find usages or references:

```
git grep -w modules.js
```

Which showed:

```
modules/apps/frontend-js/frontend-js-aui-web/src/main/java/com/liferay/frontend/js/aui/web/internal/servlet/AUITopHeadResources.java:
"/aui/aui/aui.js", "/liferay/modules.js", "/liferay/aui_sandbox.js",
```

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Nice! Thanks for the details in the description.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
