### PR TITLE
LPS-113561 Remove `Liferay.provide` in `account-admin-web`

### PR DESCRIPTION
**Pull request by julien**
As part of [LPS-113561](https://issues.liferay.com/browse/LPS-113561), we're eventually want to deprecate `Liferay.provide`, so here we're updating a simple usage: in this case the `addRow` function didn't depend on any AUI modules, so we can just declare it on the `window` object without changing the behavior. And because there are no external callers, we can avoid the pollution entirely and just inline the operation. In doing this, we fixed a bug that would allow the same domain to be added multiple times.

To test this change

- From the global menu select the "Control Panel" tab, and navigate to "Accounts".
- Click on the "+" button to create a new account
- Optionally add a name for this account
- Scroll down and find the "Valid Domains" section
- Click on the "Add" button to add a domain
- Enter a valid domain name, e.g. "liferay.com"
- Click on the "Save" button
- The "liferay.com" domain should be added to the list of "Valid Domains"

account-admin-web

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Whoops. I didn't see that you already triggered a `ci:test:relevant`. I am not going to `ci:stop` for fear of canceling the in-progress run that could usefully finish.

I am just overcome by horror that we are defining a function on the `window` called `addRow()`... not even namespaced... 🤦‍♂️ But yes, fixing that is beyond the scope of this PR.

**Comment by jbalsas** [comment]
> I am just overcome by horror that we are defining a function on the window called addRow()... not even namespaced... 🤦‍♂️ But yes, fixing that is beyond the scope of this PR.

iveseenthings

Might be simple enough to change this, though...

**Comment by wincent** [comment]
Yeah, I am already doing it.

```diff
diff --git a/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/account_entry/domains.jsp b/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/account_entry/domains.jsp
index 1ecccb7fe68d..d9ccb98a2e1d 100644
--- a/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/account_entry/domains.jsp
+++ b/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/account_entry/domains.jsp
@@ -161,7 +161,20 @@ List<String> domains = accountEntryDisplay.getDomains();
 
 					newDomains.forEach(function (domain) {
 						if (!domains.includes(domain)) {
-							addRow(domain.trim());
+							var trimmedDomain = domain.trim();
+
+							var rowColumns = [];
+
+							rowColumns.push(Liferay.Util.escape(trimmedDomain));
+							rowColumns.push(
+								'<a class="modify-link pull-right" data-rowId="' +
+									trimmedDomain +
+									'" href="javascript:;"><%= UnicodeFormatter.toString(removeDomainIcon) %></a>'
+							);
+
+							searchContainer.addRow(rowColumns, trimmedDomain);
+
+							domains.push(trimmedDomain);
 						}
 					});
 
@@ -172,19 +185,4 @@ List<String> domains = accountEntryDisplay.getDomains();
 			);
 		});
 	}
-
-	window.addRow = function (domain) {
-		var rowColumns = [];
-
-		rowColumns.push(Liferay.Util.escape(domain));
-		rowColumns.push(
-			'<a class="modify-link pull-right" data-rowId="' +
-				domain +
-				'" href="javascript:;"><%= UnicodeFormatter.toString(removeDomainIcon) %></a>'
-		);
-
-		searchContainer.addRow(rowColumns, domain);
-
-		domains.push(domain);
-	};
 </aui:script>
\ No newline at end of file
```

**Comment by julien** [comment]
@wincent I appreciate you're doing it and I next time I'll do that too because I get it's part of the task.

If you look at `Liferay.provide` usages you'll notice we're declaring lots of functions directly on `window`

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
> @wincent I appreciate you're doing it and next time I'll do that too because I get it's part of the task.
> 
> If you look at `Liferay.provide` usages you'll notice we're declaring lots of functions directly on `window`

Yeah, I knew they existed, I'm just appalled that this one doesn't have a unique-ish name.

I just pushed [one commit](https://github.com/wincent/liferay-portal/pull/316/commits/70f1577c0dfc9ed7f0c2f783b04e65fd9ba5eb05) on top of this that:

1. Avoids the pollution on `window` by inlining the code.
2. Fixes a bug in the old implementation where you could add the same domain more than once due to the bad placement of the `trim()` call.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
@julien If my commit looks ok to you, please comment with `ci:forward` — if you don't get a chance to look at it soon I'll just YOLO it.

yolo

(I did test it, including verifying that the problem with duplicate domains goes away with this fix.)

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
shipit

**Comment by julien** [comment]
@wincent I had a look and I'm OK too - thanks again. Probably going to bookmark this one for similar usages

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
