### PR TITLE
LPS-113561 Remove the unnecssary `liferay-util-window` dependency

### PR DESCRIPTION
**Pull request by julien**
As part of [LPS-113561](https://issues.liferay.com/browse/LPS-113561), we're eventually going to deprecate `Liferay.provide`.

In this change we have removed the `liferay-util-window` dependency from the [`Liferay.Sharing.share`](https://git.io/Jf1Ze) and [`Liferay.Sharing.manageCollaborators`](https://git.io/Jf1Zf) functions, because  `Liferay.Util.Window` is declared and available as a global, we don't need to declare it as a dependency.

To test these changes

For `Liferay.Sharing.share`:

- Navigate to "Content and Data > Documents and Media"
- Updload a file (an image or a text file will do)
- Once uploaded, click on the contextual menu and choose "Share"
- A modal window should open, letting you share this document with another user
- Enter the user's email address and click on the "Share" button
- A notification should be displayed letting you know the item has been shared

For `Liferay.Sharing.manageCollaborators`:

- Navigate to "Content and Data > Blogs"
- Create a new "Blog Entry"
- Click on the "Publish button"
- Click on the contextual menu next to your blog entry and choose "Manage Collaborators"
- A modal window should open letting you change your collaborators' permissions (Update, Comment or View)
- Choose a different option, and click on the "Save Button"
- A notification should be displayed letting you know the permissions have changed

### CODE REVIEW

**Comment by julien** [comment]
Adding two screenshots to help testing these changes:

For `Liferay.Sharing.share`

share

For `Liferay.Sharing.manageCollaborators`

manage-collaborators

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> because `Liferay.Util.Window` is declared and available as a global, we don't need to declare it as a dependency.

I don't know if this mirrors the process that you went through to determine this, but this is what I found:

- The `liferay-util-window` AUI module [mixes a bunch of stuff into `Liferay.Util.Window`](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js#L97), but it is not the module that defines it; it itself depends on [a number of other modules](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js#L558-L564), so while it is "global" that doesn't necessarily mean that we don't need to declare it as a dependency — the point of the dependency declaration mechanism in AUI is not only to actually load the things that we need, but to ensure we don't try using them until they are there.
- Now, some of the dependencies are in [the preload list](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/java/com/liferay/frontend/js/aui/web/internal/servlet/AUITopHeadResources.java#L96), which means that it is reasonably certain that they'll be available early on in the page load cycle, but not all of them are. (As two examples that are in the dependency list of `liferay-util-window`, I see `event-resize` in the preload list, but not `aui-url`: that means I would expect `liferay-util-window` to be available asynchronously but not immediately on page load; `git grep liferay-util-window` shows a large number of hits of places where we are waiting for it to be available and not assuming it to be already present).

So, just by looking at the module, it's not guaranteed to be available as a global at all — the real question is, *do we actually depend on it*? If the answer is "no", then we can remove the dependency declaration like you're doing here.

The code in this PR actually uses two things:

1. `Liferay.Util.PortletURL.createPortletURL`: Seems unlikely to come from `liferay-util-window` so didn't bother looking into it.
2. `Liferay.Util.openWindow`: I believe that comes [from inside the AUI `Util` module](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L665-L673); the actual assignment to `Liferay.Util.Window` is happening [here](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1671). This is a ["core" AUI module](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/java/com/liferay/frontend/js/aui/web/internal/servlet/AUITopHeadResources.java#L93), which means that [it gets loaded early no matter what](https://github.com/liferay/liferay-portal/blob/1a33288c059093e09384fad7c09c0352dd55d09f/modules/apps/frontend-js/frontend-js-aui-web/src/main/java/com/liferay/frontend/js/aui/web/internal/servlet/AUITopHeadResources.java#L69-L77), irrespective of the preload setting, which means that it will be available early on in the page lifecycle.

So from all this I conclude that: we don't depend on anything provided by `liferay-util-window`. Maybe we did in the past. Looking all the way back to when the module in this PR was originally added (1768d413bf6b2f05a2732bc337689eaf54855fef) I can't see any explicit usage of the properties provided by `liferay-util-window`. Maybe this was a copy-paste error; or maybe you used to have to explicitly rely on it in order to get `Liferay.Util.Window` defined. 🤷 

So with all that said, looks good to me.

**Comment by wincent** [comment]
I'm not going to repeat your tests seeing as you showed what happens when you follow the documented steps. (The only thing I would ask when you do these kinds of tests is that you also check the JS console for errors.) So going to (try) forward this seeing as it is almost the weekend.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
