### PR TITLE
LPS-108500 Remove interactive css classes

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Previously reviewed at: https://github.com/AliciaGarciaGarcia/liferay-portal/pull/36

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
cc/ @boton

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by wincent** [comment]
Code looks correct to me @AliciaGarciaGarcia. I have some questions:

- Do we need the conditional logic that [you have here](https://github.com/wincent/liferay-portal/blob/9e9d2a13f17aba575fb9d6a8aed6644902646b01/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card/horizontal_card_image/page.jsp)? I don't see any usage of the tag yet in this PR (am I missing something/) so I can't tell if there are really use cases why you'd need to pass an image some of the time, and arbitrary body content other times.
- I'm not super up to speed with the criteria we use for deciding when to create a new taglib and when to extend an existing taglib (ie. controlling behavior via attributes). What was your rationale in this case? Just wanting to make sure that the organization and number of [cards under this directory](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card) remains manageable.
- Does this taglib correspond to one of [the variations listed in Lexicon](https://liferay.design/lexicon/core-components/cards/cards-variation/), or is it something custom corresponding to the horizontal image cards that I can see in [the Figma link](https://www.figma.com/file/3AI2o0vhIQZKvyRwtw1mBt/lps-107343-repos-sites-on-item-selector?node-id=182%3A0) from [LPS-108500](https://issues.liferay.com/browse/LPS-108500)??

**Comment by jbalsas** [comment]
Doubling down on Greg's comments:

```
	<c:when test="<%= Validator.isNotNull(bodyContentString) %>">
		<%= bodyContentString %>
	</c:when>
```

If that was already supported, what prevented you from using the other tag as:

```
<liferay-frontend:horizontal-card-icon>
    <span class="sticker sticker-rounded">
        <span class="sticker-overlay">
            <img alt="" class="sticker-img" src="<%= image %>" />
        </span>
    </span>
</liferay-frontend:horizontal-card-icon>
```

Also, the fact that you're using `sticker-rounded` means this is a very specific case. If tomorrow the designer thinks to do a non-rounded version, we might need `HorizontalCardImageRectangular`... 

Seeing as there's only one usage of this I'd try to use the old tag first rather than adding a new one.

**Comment by AliciaGarciaGarcia** [comment]
> * Do we need the conditional logic that [you have here](https://github.com/wincent/liferay-portal/blob/9e9d2a13f17aba575fb9d6a8aed6644902646b01/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card/horizontal_card_image/page.jsp)? I don't see any usage of the tag yet in this PR (am I missing something?) so I can't tell if there are really use cases why you'd need to pass an image some of the time, and arbitrary body content other times.

About body content, It is my fault. I really did not know what was the use of _ bodyContent_ on icon so I prefer to copy, but yes it is totally removable (i think)

> * I'm not super up to speed with the criteria we use for deciding when to create a new taglib and when to extend an existing taglib (ie. controlling behavior via attributes). What was your rationale in this case? Just wanting to make sure that the organization and number of [cards under this directory](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card) remains manageable.

In this case, I created a sister from _horizontal_card_icon_ but with images and not with icons because I understood when asked Front Infra that was preferable than to extend icon and rename the class/tag and the uses, and there was no other card that we can use without changing them.
We can't use React or that is what I think (correct me if I'm wrong @boton ) so we can't use the new cards.


> * Does this taglib correspond to one of [the variations listed in Lexicon](https://liferay.design/lexicon/core-components/cards/cards-variation/), or is it something custom corresponding to the horizontal image cards that I can see in [the Figma link](https://www.figma.com/file/3AI2o0vhIQZKvyRwtw1mBt/lps-107343-repos-sites-on-item-selector?node-id=182%3A0) from [LPS-108500](https://issues.liferay.com/browse/LPS-108500)??

I think that there no one.

**Comment by boton** [comment]
@AliciaGarciaGarcia you're are right we don´t want to use react inside a `<liferay-ui:search-container-row`.

@wincent is the new custom card that you linked, LPS-108500 and another Figma.

We’ll try in this way that @jbalsas point (use the <liferay-frontend:horizontal-card-*>), remove the new tagblib and resend the PR.

I think that it will solve @wincent´s comments 1 y 2.

**Comment by wincent** [comment]
Closing this and will look at follow-up instead (https://github.com/wincent/liferay-portal/pull/173).

**Pull request closed without merging**
