### PR TITLE
LPS-112620 Initial implementation of Clay Layout Tags

### PR DESCRIPTION
**Pull request by jbalsas**
Carry over from [LPS-112620 Initial implementation of Clay Layout Tags](https://github.com/marcoscv-work/liferay-portal/pull/317)
Carry over from [LPS-112620 Adds initial clay:container tag #316](https://github.com/marcoscv-work/liferay-portal/pull/316).

**In this PR**

**Important note:** To provide some symmetry with Clay and React components, **we've decided to use `className`** as the attribute to specify CSS classes in an element rather than our legacy `cssClass`. This should make for a better and more coherent dev experience between `jsp` and `jsx`.

- [Implement clay:container tag](https://issues.liferay.com/browse/LPS-112620). Up to the final specs discussed at https://github.com/marcoscv-work/liferay-portal/pull/316#issuecomment-621905296 and based on [Define clay:container tag](https://issues.liferay.com/browse/LPS-112361)
- [Replace usages of aui:container with clay:container](https://issues.liferay.com/browse/LPS-112626).
- [Implement clay:row tag](https://issues.liferay.com/browse/LPS-112868) based on [Define clay:row tag](https://issues.liferay.com/browse/LPS-112363)
- [Replace usages of aui:row with clay:row](https://issues.liferay.com/browse/LPS-112870)
- [Replace usages of div class="row" with clay:row in JSPs](https://issues.liferay.com/browse/LPS-112872)
- [Implement clay:col tag](https://issues.liferay.com/browse/LPS-112869) based on [Define clay:col tag](https://issues.liferay.com/browse/LPS-112364)
- [Replace usages of div class="col" with clay:col in JSPs](https://issues.liferay.com/browse/LPS-112873)

## Pending

- [Replace usages of div class="container" with clay:container in JSPs](https://issues.liferay.com/browse/LPS-112628)
- [Replace usages of aui:col with clay:col](https://issues.liferay.com/browse/LPS-112871)
- ~~[Replace usages of div class="col" with clay:col in JSPs](https://issues.liferay.com/browse/LPS-112873)~~

@marcoscv-work, @eduardoallegrini, can you please continue with the pending tasks from here? Please, check the similar `container` and `row` commits to see what needs to be done, since in some cases it's necessary to add some things to `build.gradle` or `init.jsp`. **We should be able to have those done today so we can send them tomorrow in time for the stabilization period.**

@wincent, I'd say we can forward this when green and try to squeeze this in and the rest before this stabilization period so we can catch any leftovers with enough time. Can you validate this, please?

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
🤔

**Comment by jbalsas** [comment]
Forgot to change some `class` to `className` 🙈

I've ammended the commit and pushforced... retesting 🤞

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I've detected a small issue (using `sm` instead of `lg` in ColTag) and @eduardoallegrini also needs to push https://github.com/jbalsas/liferay-portal/pull/2160/commits/6acfcdc71d52615d3355e83a1d5ca241dd7f055e

I'll let tests go, see how this looks and then follow up with the fixes for a final pass...

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
soclose

**Comment by jbalsas** [comment]
Ok, so I have:
- Fixed `clay.tld` that was missing the `body-content` attribute for the new tags based on the schema definition
- [Namespaced ids](https://github.com/wincent/liferay-portal/pull/245/commits/f15008a5ebe1c059760d137d87625883ae80a422) when moving from `aui:row` to `clay:row` 

So... we can consider the previous `test:relevant` a success that caught 3 errors 👏 

I've also pushed [LPS-112873 Replaces div class='col' with clay:col in JSPs](https://github.com/wincent/liferay-portal/pull/245/commits/221265390fc70c21e0203ea86cf0bc510061d6b7), so there's that...

Let's see how this looks!

popcorn

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
despair

**Comment by wincent** [comment]
Disclaimer: I only gave this the quickest of skims but it looks good.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
So... pushed some additional fixes here and there,, so running everything again.

@John-Co, can you please analyze those 2 relevant errors? I don't think they're related, but just in case...

It's critical that we push this as soon as possible so we can get some eyes on it during the stabilization phase. The PR should be quite trivial, but it may cause some visual misalignments, so it'd be advisable to warn all Test Leads so they can let their teams know to be on the lookout.

Can you shepherd this to Brian?

Thanks!

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@jbalsas welcome back!!

And in observance of May 4th...
PR Tester Doesn't Like You

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
modules-integration test batch [Not Related] - known intermittent issue https://issues.liferay.com/browse/LPS-110102

**Comment by john-co** [comment]
cc/ @austinchiang, there's a DL modules-integration test failure

**Comment by jbalsas** [comment]
> @jbalsas welcome back!!

Thanks @jpince! Unfortunately... I'm still not back, this is just an incognito PR!!

droids

**Comment by jbalsas** [comment]
@john-co, based on the results, is this good to go?

**Comment by john-co** [comment]
need to check one thing manually, if it looks good I'll send directly to BChan.

**Comment by john-co** [comment]
cc/ @david-mesa-guiterrez the asset publisher tests look like a fluke, not able to reproduce manually. It's just weird since two tests failed on the same error.

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/88326

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
