### PR TITLE
LPS-112136 Update jQuery to v3.5.0

### PR DESCRIPTION
**Pull request by julien**
Needed for a security fix

Release notes: [https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) 

Since this is a security fix, we (frontend infra) will also need to backport this to `7.2.x` once it's merged into `master` and support will backport to `7.1.x` and `7.0.x`

According to the release notes, 

> The main change in this release is a security fix, and it’s possible you will need to change your own code to adapt. 

This doesn't directly affect DXP, because jQuery is no longer used internally, but it may require code changes in customer code in the unlikely event that they rely on the old behavior of `jQuery.htmlPrefilter`.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Once CI is green, and before doing a `ci:forward`, can you please edit the description? We [don't want any PRs without descriptions](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md#write-useful-descriptions-and-titles) (except for absurdly simple ones like "LPS-XXXXXX Fix misspelled word" which don't benefit from any additional context):

CleanShot 2020-04-21 at 13 48 39@2x

It could be something like:

> Needed for security fix.
>
> Release notes: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

For bonus points, you would also note the stuff that we discussed on Slack. I think that's important context, but if it is buried in an ancient Slack thread, nobody will benefit from it:

> Note that according to the release notes, "The main change in this release is a security fix, and it’s possible you will need to change your own code to adapt". This doesn't directly affect DXP, because jQuery is no longer used internally, but it may require code changes in customer code in the unlikely event that they rely on the old behavior of `jQuery.htmlPrefilter`.

(It is possible Brian may ask you to add an entry to [BREAKING_CHANGES.markdown](https://github.com/liferay/liferay-portal/blob/master/readme/BREAKING_CHANGES.markdown) as a result of this. Personally, I think that it is probably ok to skip it on this occasion because the odds of people running into it seem vanishingly small, but who knows?)

Whatever you put in the descripition here will get copied over by the bot. (Ideally this text would go in the commit message too, but given that CI is already running I wouldn't bother amending it at this point.)

**Comment by jpince** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> This pull contains no unique failures.

@john-co: This is another one that would benefit from https://issues.liferay.com/browse/LRCI-1208 — like you said [here](https://github.com/wincent/liferay-portal/pull/211#issuecomment-617321115), can we:

> manually determine if tests are related or are reproducible with base branch/upstream. If not related, we can directly send to BChan.

**Comment by wincent** [comment]
Actually, on reading your comment again @john-co, I think you were referring to "manual analysis" for those case where it is not clear that any failures are unique. In this case, it does seem quite clear, so I am going to try manually forwarding:

https://github.com/brianchandotcom/liferay-portal/pull/87845

**Pull request closed without merging**
