### PR TITLE
LPS-101640 VanillaJS replacement for addParams API

### PR DESCRIPTION
**Pull request by wincent**
Previously reviewed at:

- https://github.com/wincent/liferay-portal/pull/212
- https://github.com/julien/liferay-portal/pull/266

Rebased and created a new PR to see if it cures our CI woes.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Given what I described [over here](https://github.com/wincent/liferay-portal/pull/223#issuecomment-617755610), I think this is broken. Please let me know if there's anything off with my analysis, @mateomustapic — copying it here for reference:

---

Now that I've seen how `addParams` [is actually used in liferay-portal](https://github.com/wincent/liferay-portal/pull/223/commits/e2fa1e0da14ba4e78459c49ee1fc54c8445e091a) in this PR it seems that [the previous change](https://github.com/wincent/liferay-portal/pull/224) is not correct.

For example, we routinely add string params of the form `'something=other'`.

The old implementation just appends them (ie. `http://example.com/` + `something=other` becomes `http://example.com/?something=other`).

The new implementation, because it uses `SearchParams.prototype.append(string, '')` would instead produce `http://example.com/?something%3Dother=`.

So here's what I propose we do:

1. Close both this and https://github.com/wincent/liferay-portal/pull/224
2. Stack them together in one pull so that the changes to the API go in with the changes to the usage sites in one pull (if we had done that in the first place, we would have caught this problem).
3. Expand the test coverage added in #224 to catch this regression, and fix it.
4. Send a new, combined pull.

Did you manually test this? It seems like it would be difficult to test this pull in itself because it is trying to import a function that is [not even exported from `frontend-js-web` on `master` yet](https://github.com/wincent/liferay-portal/blob/e2fa1e0da14ba4e78459c49ee1fc54c8445e091a/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/index.es.js). Did your testing involve cherry-picking this one on top of the other pull?

**Comment by mateomustapic** [comment]
ey @wincent,
Julien and I discussed this and he will take this task today.  He will finish stuff you requested here and stack both PRs together.

**Pull request closed without merging**
