### PR TITLE
LPS-107374

### PR DESCRIPTION
**Pull request by julien**
Hi @wincent, 

I'm sending this just to see how CI behaves, locally there are no errors with `gradlew formatSource`, `yarn checkFormat` and `ant all`.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by wincent** [comment]
This should do it: https://github.com/julien/liferay-portal/commit/4207711e8d0649e5c9325e9cb178939ed710e90f

As we chatted on Slack, this is because the globs that apply when you run linting/fixing at a project level are not the same as the ones that apply at the top `modules/` level. Project-level globs are pretty much just "src/", "test/" — i'm going to look at tweaking the globs to avoid this kind of confusion in the future.

**Comment by wincent** [comment]
ci:test:sf

**Comment by julien** [comment]
Thanks for the quick "diagnostic" @wincent. :bowing_man: 

In the meantime, if I have PR's to send I'll probably run both the check format task from the `modules` directory and the OSGI module being changed.

**Comment by wincent** [comment]
For posterity: https://github.com/liferay/liferay-npm-tools/pull/406 — which I'll send to Brian today.

**Comment by wincent** [comment]
Here: https://github.com/brianchandotcom/liferay-portal/pull/85808

**Pull request closed without merging**
