### PR TITLE
LPS-95439 export-import-web - Replace aui-navbar with clay:navigation-bar

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey Greg, this is the PR containing the different approach we discussed. Not going for the `pattern` and instead going for the 1:1 replacement

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @kresimir-coko.

Can you help me out by telling me where I can see this in the UI?

**Comment by kresimir-coko** [comment]
> Thanks @kresimir-coko.
> 
> Can you help me out by telling me where I can see this in the UI?

Sorry I didn't get the notification for this, weird. You can find it by adding Local Staging, going to the home page while in Staging mode and click on `Publish to Live`. When that modal opens, click on top left link `advanced something something`

**Comment by wincent** [comment]
Thanks @kresimir-coko. I see now why you thought this didn't look like a very good candidate for the management toolbar, because that is for managing a list of items, whereas what we have here is very clearly a set of tabs (these screenshots from current "master"):

publish staging to live

However, one of those tabs contains a list of items ("Publish Templates"), and I suspect this is the part that Chema was calling out for migration to the management toolbar pattern:

publish templates

Having said that, I think we probably need some design input to get clarity on exactly how we want this thing to look. Moving from `aui:nav-bar` to `clay:navigation-bar` like you have in this PR seems like an improvement, but we'll still need to do the management toolbar migration mentioned in the original LPS-95439. Calling @esanzp to help connect us with the right design help, and in the meantime I am going to mark this as "changes requested" and update the JIRA ticket to reflect that we're currently blocked.

**Comment by wincent** [comment]
For context when we review the design of this, here are some screencaps of what it looks like in this PR:

x
y
z

**Comment by wincent** [comment]
@carloslancha ⬆️ these are the screenshots I mentioned in the daily.

**Comment by wincent** [comment]
Closing this one in lieu of: https://github.com/carloslancha/liferay-portal/pull/220

**Pull request closed without merging**
