### PR TITLE
LPS-113561 Avoid use of Liferay.provide in my-subscriptions-web

### PR DESCRIPTION
**Pull request by julien**
PR 3 of the 6 described here: [#320 (comment)](https://github.com/wincent/liferay-portal/pull/320#issuecomment-641223200)

Details provided in the commit messages.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by wincent** [comment]
As per Slack, we're going to try to migrate off `getWindow`.

**Comment by julien** [comment]
Here's a screenshot of how it looked before:

my-subscriptions-web-before

And how it looks after:

my-subscriptions-web-after

One this we can't do with `openModal`, is to resize the window, I'm not sure if this is a big issue here but I just wanted to point it out

**Comment by wincent** [comment]
Kind of unbelievable how it looked before...

As far as dealing with size issues goes, @markocikos may be able to lend some insight, because that is exactly the kind of issue he has had to deal with as he's migrated a bunch of AUI modals.

(Haven't looked at the code yet, but I will.)

**Comment by wincent** [comment]
@adolfopa @ambrinchaudhary: Just wanted to check with you about the state of this modal (see screenshots above) in my-subscriptions-web. The appearance of the dialog here is pretty tremendous; wanted to flag this in case we've broken things horribly with recent changes or whether it has always been like this. We don't want to make it worse, and just need to decide whether or not we need to make it better (depends on future plans for this app I guess). Can you chime in or direct us to a more appropriate person to ask?

**Comment by ambrinchaudhary** [comment]
hey @wincent, it's been a while since we don't update this component. Anyway I checked this modal in 7.2.x and there is also the same problem. But there is something here in master that is not reproducible in 7.2.x and I think makes a slight improvement. At the first render there is no padding, but switching between tabs introduces a 15px padding (to the root class _dialog-iframe-root-node_). This is something related to the modal (I saw it in other modals) and if it is fixable, that would be great. In other case, I suggest you go ahead with the pull and we may open a bug to fix this modal content.

**Comment by wincent** [comment]
Awesome. Thanks for checking that for us @ambrinchaudhary.

**Comment by markocikos** [comment]
> One this we can't do with `openModal`, is to resize the window, I'm not sure if this is a big issue here but I just wanted to point it out

There is intentionally no API in `openModal` to directly set height and width. The goal is to consistently follow [Lexicon guidelines](https://liferay.design/lexicon/core-components/modals/#size):
- we allow `size` prop to be set to `full-screen`, `lg` and `sm`, where the implementation is relayed to `ClayModal`.
- if there is an [iframe in modal](https://liferay.design/lexicon/core-components/modals/#iframe-in-the-body), we set the default size to `full-screen`. This is what caused the difference in this PR.

If there is a legitimate reason to directly set height and width, we can add the capability. But, so far, I have not seen any need for it.

**Comment by wincent** [comment]
Moved this over to https://github.com/liferay-frontend/liferay-portal/pull/16 seeing as we need to re-run tests and review the latest changes, may as well do it over there.

**Pull request closed without merging**
