### PR TITLE
LPS-111501 Update liferay-npm-scripts to v29.0.0

### PR DESCRIPTION
**Pull request by wincent**
[Release notes](https://github.com/liferay/liferay-npm-tools/tree/liferay-npm-scripts/v29.0.0):

- "import-extensions" rule catches more problems.
- Make storybook work in contexts that need frontend-js-react-web.

### CODE REVIEW

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
@izaera: I removed `modules/apps/frontend-js/frontend-js-recharts/.eslintrc.js` because we don't need it any more (see https://github.com/wincent/liferay-portal/pull/199/commits/00428d1fd745479ef55a6ac6fcc7e0725bd5061c).

**Comment by wincent** [comment]
Don't believe test failures are related. Trying again.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
First try: 123 out of 127
Second try: 124 out of 127

I'm going to give it one more go. @john-co: are you able to confirm my suspicion that these  test failures are unrelated? They seem flaky (different "unique" failures on each run.)

**Comment by wincent** [comment]
ci:forward

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1090333013&testrayRunIdA=1090489281&statusB=2

[flaky] - CPDynamicdatalists#AddFormTemplate
[flaky] - WorkflowMetrics#VerifyCustomRangeDateInput

**Comment by wincent** [comment]
First try: 123 out of 127
Second try: 124 out of 127
Third try: 125 out of 127

I guess if I try two more times I'll get to 127, right? 😂

In all seriousness, seeing as you have those two investigation tickets open @john-co, I'll let this sit here over the weekend and check in on Monday. Thank for your help!

**Comment by john-co** [comment]
[flaky] - Staging#StagingOnlyApprovedPublishToLive 
[flaky] - OAuth2#AddAndEditApplication


[not related] - WebContentDisplay#AddWithStructure

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
Trying one more time :)

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Seeing as it is the weekend and I am not to worried about CI load, I am going to retry. But I am pretty amazed at the way almost every run has a different set of "unique" failures.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
That `LocalFile.DepotApplication#Smoke` failure has come up in the last few runs, but it didn't in the first runs. I suspect it's something upstream that got merged. I'm going to try again to see if upstream has moved past that yet.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
One last try.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
I don't know whether you want to do anything more with this @john-co. I'll try again tomorrow if you don't have any luck with it today.

**Comment by john-co** [comment]
I will ignore the failing issues and try again. https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1093053147&testrayRunIdA=1093343263&statusB=3

**Comment by john-co** [comment]
testing in https://github.com/wincent/liferay-portal/pull/200

**Comment by john-co** [comment]
tests passed in #200, forwarding PR.

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
