### PR TITLE
LPS-114162 Updates Clay Packages to 05/21/2020 release

### PR DESCRIPTION
**Pull request by jbalsas**
Originally https://github.com/bryceosterhaus/liferay-portal/pull/67

This PR updates our Clay 3.x packages to their latest versions in the 05/21/2020 release. 

Details of what's included can be found in the [Bi-weekly release May 21st Milestone](https://github.com/liferay/clay/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22IFI-1671+-+Bi-weekly+release+May+21st%22)

Had to update **1 snapshot** in `segments-web` because of the [changes in `<ClayAlert>`](https://github.com/liferay/clay/issues/3231)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
Looks like there's not stopping now! 😱 

Just realized the `yarn.lock` file is not updated, which looks suspicious.

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
stopit

**Comment by jbalsas** [comment]
> GitHub API calls out of 5000 remain. GitHub API call limit will reset in 51 minutes.

hellyeah

**Comment by jbalsas** [comment]
Pushed updates to `yarn.lock`

> 1 file changed, 367 insertions(+), 348 deletions(-

**Comment by jbalsas** [comment]
Done... should I trigger tests again, @wincent? 😂

**Comment by wincent** [comment]
Beware that if you send too many bot commands you will get admonished in `#ci`.

I have no idea what state the tests are in now, but the changes look correct to me, so let's give it one more go and see what happens.

**Comment by wincent** [comment]
ci:forward

**Comment by jbalsas** [comment]
Looks like we'll need to push this manually 😢

**Comment by wincent** [comment]
On the bright side, GA was cut, so I'm not going to stress too much over a manual forward. Those test failures look like an infra failure + an unrelated Java test.

Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/89091

**Comment by jbalsas** [comment]
@bryceosterhaus, see changes, just for future reference! 😉

**Comment by wincent** [comment]
A victory, of sorts.

Screenshot 2020-05-22 -152730-4oc3IjUB@2x

**Comment by jbalsas** [comment]
yeeah

**Comment by bryceosterhaus** [comment]
@jbalsas okay I must be doing something wrong on generating the yarn lock. The steps I do are...

1. Update packages in `modules/apps/frontend-taglib/frontend-taglib-clay`
2. Run `ant format-source-all`
3. Navigate to `modules/`
4. Run `npx yarn-deduplicate yarn.lock`

Am I missing something?

**Comment by jbalsas** [comment]
You ned to run `yarn install` at some point. between `3` and `4`. 

I don't normally do `2`, but I don't think that hurts :)

**Comment by wincent** [comment]
If you don't do `2` though, what updates the package version numbers in a zillion places?

**Comment by jbalsas** [comment]
> If you don't do 2 though, what updates the package version numbers in a zillion places?

You're right, I forgot THAT did THAT!

**Pull request closed without merging**
