### PR TITLE
LPS-108002 Detail view for organic and paid search

### PR DESCRIPTION
**Pull request by dgarciasarai**
Reviewed here https://github.com/wincent/liferay-portal/pull/178

/cc @wincent @jbalsas

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by wincent** [comment]
@dgarciasarai: At this point I think we're supposed to ask QA for help to figure out what is going on with the `ci:test:relevant` failures. and see if we can get this forwarded... cc @CarlosBrichete — can you help?

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Run again relevant tests because there is only one test failing and seems flaky.

**Comment by dgarciasarai** [comment]
YESSSSS 🚀

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
