### PR TITLE
LPS-113239 FIX: Clay modals cannot be closed by clicking outside, on the sides

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @wincent, sending this over for a sanity check... also looking for @marcoscv-work input.

Just repeating myself (but avoiding you a click):

> Based on Lexicon specs there is no such thing as a modal-md size. Following the specs,
ClayModal only provides the default max width (600px) when no `size` prop is passed to
the component.
> 
> In DXP, Clay modal styles conflict with legacy YUI/AUI modals. For that reason, we
were forced to add additional styling based on modal-* classes to trump YUI's styling
based on specificity. This is the reason why we need to pass size="md" to <ClayModal>
when we want the default behaviour. Removing the size prop will cause the modal to
become left-aligned rather than centered as fixed in LPS-97981.
> 
> With this, we're also just patching the modal behaviour so modal-md gets a proper
max-width value. Once ClayModal usage is more extended than YUI's, we should be able
to revert these changes to use proper defaults and patch YUI's legacy modals instead.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Oopsies... forgot to push the proper fix :D

**Comment by wincent** [comment]
Fix makes sense to me. I also think the context in [the Jira ticket](https://issues.liferay.com/browse/LPS-113239) is helpful:

> It does work when clicking above or below. The issue is that there is an invisible div that occupies the whole width of the screen on top of the overlay.

[And](https://issues.liferay.com/browse/LPS-113239?focusedCommentId=2159623&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2159623):

> The problem is with usages of ClayModal size="md".
>
> Size "md" does not really exist, and setting it gives the modal an undefined width. Removing size="md" will give the modal the right width, but we had to add it so they'd center. Otherwise, styles collapse with YUI modals.
>
> Easiest fix would be to add width to `.modal-md` on top of `.dialog-modal .modal-md` until we can get rid of YUI modals or their usage is enough to invert the fix

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Tested with `.modal-md` styling disabled (shows breakage) and enabled (works):

Screenshot 2020-05-21 -121256-5dIB4JWy@2x

Screenshot 2020-05-21 -121150-9aIwg5Lt

**Comment by wincent** [comment]
Checked with @jbalsas about whether to forward or wait for @marcoscv-work feedback — he said to forward. We can send a follow-up if Marcos has suggestions for a different approach.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
