### PR TITLE
LPS-112763 Update liferay-npm-scripts to v31.0.0

### PR DESCRIPTION
**Pull request by wincent**
New version [release notes](https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-scripts%2Fv31.0.0).

Brings in new lints from [latest eslint-liferay-config release](https://github.com/liferay/eslint-config-liferay/releases/tag/v21.0.0), specifically:

- feat!: require blank lines before and after line comments
- feat!: enforce standard formatting for deprecation annotations

This gets up 99% of the way to where we want to go, by which I meant that:

- We put blank lines before and after line comments (`//`); and:
- Blank lines before but not after block comments (`/* ... */`)

in 95% of places. The remaining 5% consists of points where ESLint and Prettier disagree about how a comment should be formatted; this specifically occurs at the beginning of objects, arrays, blocks etc. The first 95% was cheap to get (configuration only); the remaining 5% would be expensive (requiring hacking Prettier) so I stopped at this point for now.

I'll apply the autofixes (a hundred or so) and manual fixes (a couple) in separate commits to make the automated part of this update clear.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
@john-co: I suspect the failures here are spurious because the changes here are pretty much whitespace-only. Do you think we should we do anything about these?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
- DMAutoTagging#OpenNLPSmoke - seems unrelated based on history, could be flaky or a failing test in upstream
https://testray.liferay.com/home/-/testray/case_results/1135356733/history?tab=result&hideFilterPin=true
- PagesFinder#AddChildPageViaPageFinder - failing in upstream
https://testray.liferay.com/home/-/testray/case_results/1135416126/history?tab=result&hideFilterPin=true

We should quarantine both tests so they don't affect other test runs

cc/ @austinchiang @david-gutierrez-mesa

**Comment by john-co** [comment]
@wincent, I can push this to BChan with the quarantined tests if this is ready.

**Comment by john-co** [comment]
Pushed commits to quarantine and ignore the flaky and failing test respectively in https://github.com/wincent/liferay-portal/pull/242

**Comment by john-co** [comment]
Pushed to BChan
https://github.com/wincent/liferay-portal/pull/242

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
I ended up only ignoring the PagesFinder test. The DMAutoTagging testfix was recently synced upstream.

cc/ @austinchiang @david-gutierrez-mesa

**Comment by wincent** [comment]
Thanks for shepherding this one through, @john-co!

**Pull request closed without merging**
