### PR TITLE
LPS-97472 | Remove lint suppressions from hello-soy | Do not forward, this PR breaks the portlet

### PR DESCRIPTION
**Pull request by markocikos**
Hi @wincent ,

Please do not forward, these changes completely break the portlet. I cannot figure out why:
- In no other portlet do we reference soy files directly, maybe this way of importing requires var assignment?
- It may be related to the fact that the portlet is broken even before changes, that soy may be wired in an obsolete way. See https://issues.liferay.com/browse/LPS-97761

@brunobasto could you maybe help with this one?

Thank you!

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @markocikos. Definitely seems like we should address the breakage before touching the file. Or maybe we can even skip fixing it: is this module still relevant, give that we want to de-emphasize Soy? (@jbalsas might have an opinion on that too.)

**Comment by jbalsas** [comment]
This change should be harmless based on how Soy works. I can take a look at this one, see if we can fix the portlet alltogether.

**Comment by jbalsas** [comment]
I just took a quick look into this and the module is not building properly because we're not resolving the `hello-soy-navigation-web` to `hello-soy-web` module dependency.

That's completely independent from this, so I think we can push this forward to close this and enable linting once and for all.

**Comment by wincent** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/75696

Thanks @markocikos. With this change, we have 0 warnings in liferay-portal. 🎉

Will still need to tackle the unrelated pre-existing problem in LPS-97761.

**Comment by brunobasto** [comment]
Hey guys, sorry I didn't answer sooner. But yeah, Chema's evaluation is probably correct. We need to fix that problem with hello-soy in a separate PR.

**Pull request closed without merging**
